<h1>Proveedores</h1>
<p class="t-right">
    <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/proveedores/alta"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
    </a>
</p>
<?php echo $this->form; ?>
<table class="full-width">
    <thead>
    <tr>
        <th>Nombre corto</th>
        <th>Teléfono</th>
        <th>Información</th>
        <th width="75">Acciones</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->query as $obj): ?>
    <tr>
        <td><?php echo $obj->nombre_corto; ?></td>
        <td><?php echo $obj->telefono; ?></td>
        <td><?php echo $obj->info_adicional; ?></td>


        <td>
            <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/proveedores/editar/id/" . $obj->id_proveedor); ?>">
                <img src="<?php echo $this->baseUrl("css/img/edit.png") ?>" border="0"/>
            </a>

            <a delete="true" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/proveedores/borrar/id/" . $obj->id_proveedor); ?>">
                <img src="<?php echo $this->baseUrl("css/img/delete.png") ?>" border="0"/>
            </a>
        </td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>