<h1>TIENDAS</h1>
<p class="t-right">
    <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
    </a>
</p>
<?php echo $this->form; ?>
<table class="full-width">
    <thead>
    <tr>
        <th>Id Tienda</th>
        <th>Nombre</th>
        <th>Telefono</th>
        <th>Independiente</th>
        <th>Ubicacion</th>
        <th>Telefono</th>
        <th width="75">Acciones</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->query as $obj): ?>
    <tr>
        <td><?php echo $obj->id_tienda; ?></td>
        <td><?php echo $obj->nombre; ?></td>
        <td><?php echo $obj->telefono; ?></td>
        <td><?php echo $obj->info_adicional  ?></td>
        <td><?php echo $obj->ubicacion; ?></td>
        <td><?php echo $obj->status; ?></td>

        <td>
            <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/editar/id/" . $obj->id_tienda); ?>">
                <img src="<?php echo $this->baseUrl("css/img/edit.png") ?>" border="0"/>
            </a>

            <a delete="true"
               href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/borrar/id/" . $obj->id_tienda); ?>">
                <img src="<?php echo $this->baseUrl("css/img/delete.png") ?>" border="0"/>
            </a>
        </td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>