<?php
/*$dbh = mysql_connect ("107.180.58.31:3306", "bs_prod_user01", "V16IGFPTdn!!0") or die ('I cannot connect to the database.');
mysql_select_db ("breachsmart_prod_portal_v01");
*/
//Creas una variable de tipo objeto mysqli con los datos de la bd y el charset que quieras
$mysqli = new mysqli('107.180.58.31:3306', 'bs_prod_user01', 'V16IGFPTdn!!0', 'breachsmart_prod_portal_v01');
$mysqli->set_charset("utf8");

$sql       = "SELECT ws.*,u.id_company FROM waiting_emails ws INNER JOIN campaigns_send  cs on cs.id_campaignssend=ws.id_campaignssend  INNER JOIN usuario  u on cs.id_usuario=u.id_usuario where ws.status='PENDING'";
//$resultado = mysql_query($sql, $dbh);
$res = $mysqli->query($sql);
if($res){
    while($f = $res->fetch_object()){

        $sqlc= "SELECT * FROM company where id_company=".$f->id_company;
//$resultado = mysql_query($sql, $dbh);
        $resc = $mysqli->query($sqlc);
        $smpt=$username=$password=$port=$namecompany="";
        if($resc) {
            while ($fc = $resc->fetch_object()) {
               $smpt = $fc->smtp;
               $namecompany = $fc->name;
               $username=$fc->user_smtp;
               $password=$fc->pwd_smtp;
               $port=$fc->port;
            }

        }
        $smtpConf = array(
            'auth' => 'login',
            'ssl' => 'tls',
            'username' => $username, //El de la cuenta
            'password' => $password,
            'port' => $port
        );

        $transport = new Zend_Mail_Transport_Smtp($smpt, $smtpConf);
        Zend_Mail::setDefaultTransport($transport);
        $mail = new Zend_Mail("utf-8");
       //$mail->addBcc("jorge.orihuela@tigears.com");
        $mail->addTo(trim($f->email_to));
        $mail->setFrom("jorge@illumant.com");
        $mail->setSubject($f->subject);
        $mail->setBodyHtml(wordwrap($f->body));
        $mail->addBcc("jorge@illumant.com");
        $mail->addBcc("msnod@illumant.com");
      /*  if ($pos === false) {
            $mail->addBcc("msnod@illumant.com");
            $mail->addBcc("siljak@illumant.com");
            $mail->addBcc("jorge@illumant.com");
        } else {
            $mail->addBcc("jorge@illumant.com");
        }

      */
        try{
            if($mail->send()) {
                $sqlc = "UPDATE  waiting_emails SET status='SENT', sent_date='" . date('Y-m-d: H:i:s') . "' where id_waitingemails=" . $f->id_waitingemails;
                $resc = $mysqli->query($sqlc);
                if ($resc) {
                    $sqlc = "UPDATE  campaigns_send SET date_sent='" . date('Y-m-d: H:i:s') . "', sent='1' where id_campaignssend=" . $f->id_campaignssend;
                    $resc = $mysqli->query($sqlc);
                    if ($resc) {
                        echo "Exito " . $f->email_to . ' <br/>';
                    }else {
                        echo "ERRROR update campaigns_send". ' <br/>';
                    }
                } else {
                    echo "ERRROR update waiting_emails". ' <br/>';
                }
            }else {
                echo "ERRROR al enviar mail". ' <br/>';
            }


        }catch (Exception $e){
            echo  "error".$e;
            exit;
        }

    }
}





?>