<div id="stylized" class="myform">
<h1>Iniciar Sesión</h1>
<p>Introduce tu nombre de usuario y tu contraseña para empezar</p>
<form method="post">
<table cellpadding="0" cellspacing="0" border="0">
    <tbody>
        <tr>
            <td><label>Nombre de usuario</span> </label> </td>
            <td><?= $this->form->username; ?></td>
        </tr>
        <tr>
            <td><label>Contraseña</label></td>
            <td><?= $this->form->password; ?></td>
        </tr>

    </tbody>
</table>

<div align="center">
<?= $this->form->submit; ?><br />
</div>
<div class="spacer"></div>
<hr />
<div class="clear"></div>

</form>
</div>