<h1>Devoluciones</h1>

<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<br>
<h3 class="tit">Buscar Folio de venta que desea devolver</h3>

<?php echo $this->form; ?>
<h3 class="tit">Reporte generado de Todas las ventas</h3>
<table width="100%" style="overflow:auto">
    <tr>
        <th></th>
        <th>Folio Venta</th>
        <th>Vendedor</th>
        <th>Fecha</th>
        <th>Tipo</th>
        <th>Tienda</th>
        <th>Total</th>
        <th></th>
    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj): ?>
        <tr <?php  if ($obj->cancelado) {
            echo "class='cancelada'";
        }?>
            >

            <td><a href="<?php echo $this->baseUrl("administracion/devoluciones/ver/id/" . $obj->id_venta); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->folio; ?></td>
            <td><?php echo $obj->Usuario->nombre; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td><?php echo $obj->tipo; ?></td>

            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td>$<?php if (!$obj->cancelado) {
                    $total += $obj->total;
                } echo number_format($obj->total, 2); ?></td>
            <td>
                <?php if (!$obj->cancelado): ?>
                    <a title="Cancelar venta" tooltip="true"  fancybox="true"
                       href="<?php echo $this->baseUrl("administracion/devoluciones/mostrarcancelarventa/id/" . $obj->id_venta); ?>">
                        <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
                <?php endif; ?>
            </td>


        </tr>
    <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>$ <?php echo number_format($total, 2); ?></td>
    </tr>
</table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>