
<script type="text/javascript">
    $(document).ready(function () {

        $("#buscar-producto-form").submit(function (e) {
            e.preventDefault();

            $.get(_root + "/administracion/devoluciones/cancelarproducto", $(this).serialize(), function (response) {
                //$("#table-resultados").html(response);
               // alert(response);
                if(response) {
                    alert("Producto Cancelado");
                    location.href=_root + "/ventas/reportes/devolucionesproducto";
                    $.fancybox.close();

                }else{
                    alert("Error");
                }

            });
        });
    });
</script>

<h3 class="tit">Cancelar el Producto de la Venta <?php echo $this->obj->Venta->folio; ?></h3>




<div id="table-resultados">
    <form id="buscar-producto-form">
        <table width="100%" style="overflow:auto">
            <tr>
                <th>Nombre del Producto</th>
                <td>
                    <label class="control-label"><?php echo $this->obj->nombre; ?></label>
                    <input type="hidden" name="folio" value="<?php echo $this->obj->Venta->folio; ?>">
                </td>
            </tr>
            <tr>
                <th>Tienda Origen Venta</th>
                <td> <label class="control-label"><?php echo $this->obj->Venta->Tienda->nombre; ?></label></td>
            </tr>
            <tr>
                <th>Tienda Destino Devolucion</th>
                <td>
                    <?php if($this->tipousu==2||$this->usu=="mariely"){
                       ?>
                        <div class="controls">
                            <?php echo $this->formSelect("id_tienda_destino",$this->obj->Venta->id_tienda,
                                array("style"=>"width:460px","required" => "required"),
                                Database_Model_Tienda::getAllT()
                            ); ?>
                        </div>
<?php                    }else{
                    ?>
                 <label class="control-label"><?php echo $this->tiendausu; ?></label>
                <input type="hidden" name="id_tienda_destino" id="id_tienda_destino" value="<?php echo $this->id_tiendausu; ?>">
                </td>
<?php
                    }
                    ?>

                </td>
            </tr>

            <tr>
                <th>Observaciones</th>
                <td> <input type="text" name="observaciones" value=""></td>
            </tr>
            <tr>
                <th></th>
                <td> <input type="submit" value="Cancelar"/> </td>
            </tr>
        </table>
        <input type="hidden" name="id" id="id" value="<?php echo $this->obj->id_productos_venta; ?>">
    </form>
</div>