
<script type="text/javascript">
    $(document).ready(function () {

        $("#buscar-producto-form").submit(function (e) {
            e.preventDefault();

            $.get(_root + "/ventas/administrar/cancelar", $(this).serialize(), function (response) {
                //$("#table-resultados").html(response);
               // alert(response);
                if(response) {
                    alert("Venta Cancelada");
                    location.href="#";
                    $.fancybox.close();

                }else{
                    alert("Error");
                }

            });
        });
    });
</script>

<h3 class="tit">Cancelar Toda la Venta</h3>




<div id="table-resultados">
    <form id="buscar-producto-form">
        <table width="100%" style="overflow:auto">
            <tr>
                <th>Folio Venta</th>
                <td>
                    <label class="control-label"><?php echo $this->obj->folio; ?></label>
                    <input type="hidden" name="folio" value="<?php echo $this->obj->folio; ?>">
                </td>
            </tr>
            <tr>
                <th>Tienda Origen Venta</th>
                <td> <label class="control-label"><?php echo $this->obj->Tienda->nombre; ?></label></td>
            </tr>
            <?php
            if($this->usu=='anny'||$this->usu=='Elena'||$this->tipousu==5){
            ?>
            <tr>
                <th>Tienda Destino Devolucion</th>
                <td>
                    <div class="controls">
                        <?php echo $this->formSelect("id_tienda_destino",$this->obj->id_tienda,
                            array("style"=>"width:460px","required" => "required"),
                            Database_Model_Tienda::getAllT()
                        ); ?>
                    </div>

                </td>
            </tr>
            <tr>
                    <th>Fecha Devolucion</th>
                    <td>
                        <div class="controls">
                            <input type="text" class="small-input" datepicker='past' name="fechadevolucion" id="fechadevolucion" value='<?php echo date('Y-m-d')?>'/>
                        </div>
                    </td>
                </tr>
        <?php
        }else{ ?>
                <input type="hidden" name="id_tienda_destino" id="id_tienda_destino" value="<?php echo $this->id_tiendausu; ?>">
                <input type="hidden" name="fechadevolucion" id="fechadevolucion" value="<?php echo date('Y-m-d')?>">
            
        <?php
        }
        ?>

            <tr>
                <th>Observaciones</th>
                <td> <input type="text" name="observaciones" value=""></td>
            </tr>
            <tr>
                <th></th>
                <td> <input type="submit" value="Cancelar"/> </td>
            </tr>
        </table>
        <input type="hidden" name="id" id="id" value="<?php echo $this->obj->id_venta; ?>">
    </form>
</div>