<script type="text/javascript">
    $(document).ready(function () {
        calcTotal = function () {

            var totales=document.getElementsByClassName("totales");
            var total = 0;
            for (var i = 0, len = totales.length; i < len; i++) {
                total = parseFloat(total);
                total += parseFloat(totales[i].innerHTML);
            }
            document.getElementById("total-num").innerHTML=total;
            document.getElementById("total-global").value=total;
        }

        $("#agregarprod").click(function (e) {
            e.preventDefault();
            var res =  $('#barcode').val().split("::");
            if(res.length>0){
                $('#barcode').val(res[0].trim());
            }
            var id_tienda=document.getElementById("id_tiendaanterior").value;
            var barcode=document.getElementById("barcode").value;
            var msj="id_prod="+$("#barcode").val()+"&cantidad="+$("#cantidad").val()+"&id_tienda="+id_tienda+"&barcode="+barcode;
            //alert(msj);
            
            $.get(_root + "/administracion/traspaso/getproducto", msj,
                function (response) {
                    $("table#productos").append(response);
                    calcTotal();
                });
            $("#cantidad").val(1);
            $("#barcode").val("").focus();
            return false;
        });

        $("#barcode" ).keypress(function(e) {
            if (e.which == 13) {
                e.preventDefault();
                var id_tienda=document.getElementById("id_tiendaanterior").value;
                var barcode=document.getElementById("barcode").value;
                var msj="id_prod="+$("#barcode").val().trim()+"&cantidad="+$("#cantidad").val()+"&id_tienda="+id_tienda+"&barcode="+barcode;
                //alert(msj);
                $.get(_root + "/administracion/traspaso/getproducto", msj,
                    function (response) {
                        $("table#productos").append(response);
                        calcTotal();
                    });
                $("#cantidad").val(1);
                $("#barcode").val("").focus();
                return false;
            }

        });
       




        $("#barcode").focus(
            function () {
                $(this).addClass("yellow-bg");
            }).blur(function () {
                $(this).removeClass("yellow-bg");
            });

        $("#barcode").focus();


        $("#send").click(function (e) {
            if(document.getElementById("fecha").value!=""){
                $(".borrar-td").remove();
                $("#ticket-items").val($("#productos").html());
                $(this).hide();
                calcTotal();
                $("#main-form").submit();
            }else{
                alert("Selecciona una fecha");
            }

        });


        $(".borrar-producto").live('click', function (e) {
            e.preventDefault();
            var id = $(this).attr("lineid");
            $("[lineid=" + id + "]").remove();
            calcTotal();
        });
    });
    var total1=0;
    function calculaprecio(num){
        document.getElementById("total-num").innerHTML=0;
        var precio2 = (document.getElementById("costo"+num).value *  1.16 *   document.getElementById("multiplicador").value);
       var precio=precio2.toFixed(2);
        document.getElementById("precio"+num).value=precio;
        var importe2 = (document.getElementById("costo"+num).value * document.getElementById("cantidad"+num).innerHTML);
        var importe=importe2.toFixed(2);
        document.getElementById("importe"+num).innerHTML=importe;
        document.getElementById("importe2"+num).value=importe;
       calcTotal2();
    }
    function calcTotal2(){
        var totales=document.getElementsByClassName("totales");
        var total = 0;
        for (var i = 0, len = totales.length; i < len; i++) {
            total = parseFloat(total);
            total += parseFloat(totales[i].innerHTML);
        }
        document.getElementById("total-num").innerHTML=total;
        document.getElementById("total-global").value=total;

    }

</script>
<?php


$cadena=$_SESSION['CADENA'];
?>

<h1>Traspasos</h1>
<h3 class="tit">Nuevo Traspaso a Almacen</h3>




<form action="" id="main-form" method="post">
    <table class="nostyle">
        <tr>
            <td><label>Fecha Traspaso</label></td>
            <td>
                <input type="text" class="small-input" datepicker="past" id="fecha" value="<?php echo date('Y-m-d')?>"  name="fecha" placeholder="Fecha Traspaso"/>
            </td>

        </tr>
        <tr>
            <td><label>Referencia</label></td>
            <td>
                <input type="text" class="small-field" id="referencia" name="referencia" placeholder="Agregar referencia"/>
            </td>
        </tr>

        

    </table>
    <div class="control-group" id="" style="display: ">
        <div class="control-group" id="tiendaorigen" style="display: ">
            <label class="control-label">Tienda Origen </label>
            <div class="controls">
                <?php
                    echo $this->formSelect("id_tiendaanterior",$this->id_tienda,
                        array("style"=>"width:460px","required" => "required"),
                        Database_Model_Tienda::getAll());


                ?>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Pasar a Tienda</label>
            <div class="controls">
                <?php
                    echo $this->formSelect("id_tienda","",
                        array("style"=>"width:460px","required" => "required"),
                        Database_Model_Tienda::getAll()
                    );

                ?>
            </div>
        </div>
    </div>
    <fieldset>
        <legend>Introducir producto</legend>

            <input type="hidden" id="tipousu" value="<?php echo $this->tipousu; ?>">



            <br />
            <table class="nostyle">
                <tr>
                    <td>   <label for="barcode">Código de barras</label>  </td>
                    <td>   <input type="text" id="barcode"  for='autocomplete' name="id_producto" value="<?php echo $this->codint; ?>"/>      </td>
                    <td>
                        <a fancybox="true" id="catalogo" href="<?php echo $this->baseUrl("ventas/administrar/mostrarcatalogo?id_tienda=".$this->id_tienda); ?>">Catálogo</a>
                    </td>
                </tr>
                <tr>
                    <td>       <label for="cantidad">Cantidad</label>  </td>
                    <td>    <input type="text" class="small-field" id="cantidad" name="cantidad" value="1"/>    </td>
                </tr>
                <tr>
                    <td>        <input type="button" id="agregarprod" value="Agregar"/>         </td>
                </tr>
            </table>

    </fieldset>
    <h3 class="tit">Producto</h3>
    <input type="hidden" name="total-global" id="total-global" value="0"/>

    <input type="hidden" name="ticket_items" id="ticket-items" value="0"/>

    <h3 class="total">Costo Total: $<span id="total-num"></span></h3>
    <table id="productos" class="full-width">
        <tr>
            <th>Cantidad</th>
            <th>Codigo Interno</th>
            <th>Producto</th>
            <?php if($showcostos){ ?>
            <th>Costo</th>
            <?php } ?>
            <th>Precio</th>
            <th>Precio Mayoreo</th>
            <th>Importe</th>
            <th class="borrar-td"></th>
        </tr>
    </table>
    <div style="height: 25px;"></div>
    <hr/>

    

    <div class="control-group">
        <label class="control-label">Comentarios</label>
        <div class="controls">
            <?php echo $this->formText("comentarios", $this->data["comentarios"],
                 array("style"=>"height:100px !important")
            ); ?>
        </div>
    </div>


    <div style="height: 25px;"></div>
    <input style="width: 100%" type="button" id="send" class="button" value="Registrar Traspaso">
</form>
<script>
    $("#id_tienda").change(function (e) {
        e.preventDefault();
        var id=$("#id_tienda").val();
        $("#catalogo").attr('href','<?php echo $this->baseUrl("ventas/administrar/mostrarcatalogo?id_tienda="); ?>'+id);
        return false;
    });
    $( "#barcode" ).autocomplete({
        source: [ <?php echo $cadena ?>],
        select: function(res) {
   
        }
    });
</script>


















