<h1>Traspasos de Almacen</h1>
<h3 class="tit">Ver traspaso</h3>
<a href="<?php echo $this->baseUrl("administracion/traspaso/imprimir/id/" . $this->obj->id_traspaso); ?>" target="_blank">Imprimir
    traspaso</a>
<table>
    <tr>
        <th>Vendedor</th>
        <td><?php echo $this->obj->Usuario->nombre; ?></td>
    </tr>
    <tr>
        <th>Fecha</th>
        <td><?php echo $this->obj->fecha; ?></td>
    </tr>
    <tr>
        <th>Referencia</th>
        <td><?php echo $this->obj->referencia; ?></td>
    </tr>
    <tr>
        <th>Folio</th>
        <td><?php echo $this->obj->id_traspaso; ?></td>
    </tr>
    <tr>
        <th>Comentarios</th>
        <td><?php echo $this->obj->comentarios; ?></td>
    </tr>
    <tr>
        <th>Tienda Origen</th>
        <td><?php
            $obj = Doctrine_Core::getTable("Database_Model_Tienda")->findOneBy("id_tienda", $this->obj->id_tiendaanterior);
            echo strtoupper($obj->nombre); ?></td>
    </tr>
    <tr>
        <th>Tienda Destino</th>
        <td><?php echo $this->obj->Tienda->nombre; ?></td>
    </tr>


</table>

<h3 class="tit">Artículos</h3>

<table width="100%">
    <tr>
        <th>Cantidad</th>
        <th>Cod Inter.</th>
        <th>Producto</th>
        
        <th>Precio</th>
        <?php
            if($this->datauserlogged->id_usuario=='anny'||$this->datauserlogged->id_usuario=='Elena'||$this->datauserlogged->id_usuario_tipo==5){
                echo "<th>Costo</th><th>Costo Total</th>";
            }
        ?>
        
        

    </tr>
    <?php
    $total = 0;
    $costo = 0;
    $precio = 0;
    $totalComision = 0;
    $query= Doctrine_Query::create()
        ->from("Database_Model_TraspasoProducto")
        ->where("id_traspaso=?",$this->obj->id_traspaso)
        ->execute();
    foreach ($query as $obj):
        if (!$obj->cancelado) {
            $costo+=$obj->totalcosto;
            $precio+=$obj->cantidad*$obj->precio;
        }
    ?>
        <tr <?php  if ($obj->cancelado) {
            echo "class='cancelada'";
        }?> >
            <td><?php echo $obj->cantidad; ?></td>
            <td><?php echo $obj->Producto->codinter; ?></td>
            <td><?php echo $obj->nombre; ?></td>
            <td>$<?php  echo number_format($obj->precio, 2); ?></td>
            <?php
            if($this->datauserlogged->id_usuario=='anny'||$this->datauserlogged->id_usuario=='Elena'||$this->datauserlogged->id_usuario_tipo==5){
                echo "<td>$".number_format($obj->costo, 2)."</td>";
                echo "<td>$".number_format($obj->totalcosto, 2)."</td>";
            }
            ?>
            <td>
                <?php if (!$obj->cancelado): ?>
                    <a title="Cancelar Traspaso" tooltip="true" delete="true"
                       href="<?php echo $this->baseUrl("administracion/traspaso/cancelarproducto/id/" . $obj->id_traspaso_producto); ?>">
                        <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
                <?php endif; ?>
            </td>

        </tr>
    <?php endforeach; ?>
    <tr>

        <td></td>
        <td></td>
        <td><strong>Totales</strong></td>
        <td>$<?php  echo number_format($precio, 2); ?></td>
        <?php
        if($this->datauserlogged->id_usuario=='anny'||$this->datauserlogged->id_usuario=='Elena'||$this->datauserlogged->id_usuario_tipo==5){
            echo "<td>$".number_format($costo, 2)."</td>";
        }
        ?>
    </tr>
</table>