<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Ventas</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th></th>
        <th>ID Venta</th>
        <th>Vendedor</th>
        <th>Fecha</th>
        <th>Tipo</th>
        <th>Total</th>
        <th>Tienda</th>
        <th></th>
    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj): ?>
        <tr <?php  if ($obj->cancelado) {
            echo "class='cancelada'";
        }?>
            >

            <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/" . $obj->id_venta); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->id_venta; ?></td>
            <td><?php echo $obj->Usuario->nombre; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td><?php echo $obj->tipo; ?></td>

            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td>$<?php if (!$obj->cancelado) {
                $total += $obj->total;
            } echo number_format($obj->total, 2); ?></td>
            <td>
                <?php if (!$obj->cancelado): ?>
                <a title="Cancelar venta" tooltip="true" delete="true"
                   href="<?php echo $this->baseUrl("ventas/administrar/cancelar/id/" . $obj->id_venta); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
                <?php endif; ?>
            </td>

        </tr>
        <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>$ <?php echo number_format($total, 2); ?></td>
    </tr>
</table>