<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Yo Amo Comprar</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>


    <?php
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/reset.css");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/2col.css", "screen,projection", false, array("title" => "2col"));
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/1col.css", "screen,projection", false, array("title" => "1col"));

    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/main-ie6.css", "screen", "lt IE 6");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/main.css");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/mystyle.css");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/style.css");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/jqueryui.css");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/Growl/css/growl.css");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/fancybox/jquery.fancybox-1.3.4.css");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/tipsy.css");

    //para el multiselect
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/jquery.multiselect.css");
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/jquery.multiselect.filter.css");

    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery-ui.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.functions.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.tipsy.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.validate.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.timepicker.addon.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/specific.functions.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/switcher.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/toggle.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/Growl/js/growl.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.timer.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/fancybox/jquery.fancybox-1.3.4.pack.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.jstorage.js", 'text/javascript');
    $this->headScript()->appendFile($this->baseUrl() . "/js/tablesorter/jquery.tablesorter.js", 'text/javascript');//para ordenar las tablas de los reportes

    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.multiselect.js", 'text/javascript');//para el multiselect
    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.multiselect.filter.js", 'text/javascript');//para el multiselect

    //para el datatable
    $this->headLink()->appendStylesheet($this->baseUrl() . "/css/jquery.dataTables_themeroller.css");

    $this->headScript()->appendFile($this->baseUrl() . "/js/jquery.dataTables.js", 'text/javascript'); //para el datatable
    echo $this->headLink();
    echo $this->headScript();
    ?>


    <!--ppara el vilidador de forms-->


    <script type="text/javascript">
        $(".tablesorter").tablesorter();//para ordenar las tablas de los reportes
        $(document).ready(function () {
            _root = "<?php echo $this->baseUrl(); ?>";

            $("[fancybox=true]").fancybox();
        });

    </script>
</head>
<body>
<div id="main">
    <!-- Tray -->
    <div id="tray" class="box">
        <p class="f-left box">

            <!-- Switcher -->
                    <span class="f-left" id="switcher">
                        <a href="javascript:void(0);" rel="1col" class="styleswitch ico-col1"
                           title="Display one column"><img
                            src="<?php echo $this->baseUrl(); ?>/design/switcher-1col.gif" alt="1 Column"/></a> <a
                        href="javascript:void(0)" rel="2col" class="styleswitch ico-col2"
                        title="Display two columns"><img
                        src="<?php echo $this->baseUrl(); ?>/design/switcher-2col.gif" alt=""/></a> </span></p>

        <p class="f-right">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong><a
            href="<?php echo $this->baseUrl(); ?>/login/logout" id="logout">Salir</a></strong></p>

    </div>
    <!--  /tray -->
    <hr class="noscreen"/>
    <!-- Menu -->
    <div id="menu" class="box">
        <ul class="box">
            <?php

                $profile = $this->profile();
            if($profile->permisos=="TODO"||$profile->permisos=="VENDEDOR" ) {  ?>
                <li><a href="<?php echo $this->baseUrl("ventas/administrar/alta"); ?>"><span>Nueva Venta</span></a></li>
            <?php } if($profile->permisos=="TODO"||$profile->permisos=="VENDEDOR" ||$profile->permisos=="REPORTES") {  ?>
                <li><a href="<?php echo $this->baseUrl("reportes"); ?>"><span>Reportes</span></a></li>

              <!--  <li><a href="<?php echo $this->baseUrl("facturas/administrar"); ?>"><span>Facturas</span></a></li>
              -->
            <?php
            } if($profile->permisos=="TODO") {  ?>
            <li><a href="<?php echo $this->baseUrl("administracion/usuario"); ?>"><span>Usuarios</span></a></li>
            <?php
            } if($profile->permisos=="TODO"||$profile->permisos=="VENDEDOR") {  ?>
            <li><a href="<?php echo $this->baseUrl("administracion/clientes2"); ?>"><span>Clientes</span></a></li>
            <li><a href="<?php echo $this->baseUrl("administracion/validainventario"); ?>"><span>Valida Inventario</span></a></li>
            <li><a href="<?php echo $this->baseUrl("administracion/validatraspaso"); ?>"><span>Valida Traspasos</span></a></li>
                <li><a href="<?php echo $this->baseUrl("asistencia/registro"); ?>"><span>Asistencia</span></a></li>
            <?php
            }   ?>

        </ul>
    </div>
    <!-- /menu -->
    <hr class="noscreen"/>

    <!-- Columns -->
    <div id="cols" class="box">

        <!-- Aside (Left Column) -->
        <div id="aside" class="box">
            <div id="logo" class="padding box">
                <img src="<?php echo $this->baseUrl("images/logo2.jpg"); ?>"/>
            </div>

            <div class="padding box">

                <ul>
                    <?php if($profile->permisos=="TODO"||$profile->permisos=="VENDEDOR") {  ?>
                        <li><a
                            href="<?php echo $this->baseUrl("administracion/inventarios"); ?>"><span>Entradas de Almacen</span></a>
                        </li>
                        <li><a href="<?php echo $this->baseUrl("administracion/productos/index/vertodo/0"); ?>"><span>Productos</span></a>
                        </li>
                        <li><a href="<?php echo $this->baseUrl("administracion/paquete"); ?>"><span>Paquetes</span></a>
                        </li>
                        <li><a href="<?php echo $this->baseUrl("administracion/traspaso"); ?>"><span>Traspaso de Productos</span></a>
                        </li>
                     <!--   <li><a href="<?php echo $this->baseUrl("administracion/traspasos"); ?>"><span>Traspaso de Productos 1x1</span></a>
                        </li>
                        -->
                        <li><a
                            href="<?php echo $this->baseUrl("administracion/proveedores"); ?>"><span>Proveedores</span></a>
                        </li>

                        <li><a
                                href="<?php echo $this->baseUrl("deudores/administrar"); ?>"><span>Ventas a Credito</span></a>
                        </li>

                    <?php
                    }  if($profile->permisos=="TODO"||$profile->permisos=="VENDEDOR") {  ?>
                        <li><a
                                href="<?php echo $this->baseUrl("administracion/devoluciones"); ?>"><span>Devoluciones</span></a>
                        </li>
                        <li><a
                                href="<?php echo $this->baseUrl("administracion/catalogos"); ?>"><span>Catalogos</span></a>
                        </li>
                        <li><a
                                href="<?php echo $this->baseUrl("administracion/salida"); ?>"><span>Salidas de Almacen</span></a>
                        </li>
                         <li><a
                            href="<?php echo $this->baseUrl("settings/backoffice/manage/table/gasto"); ?>"><span>Gastos</span></a>
                        </li>
                    <?php
                    }?>

                  <!--  <li>
                        <a href="<?php echo $this->baseUrl("settings/backoffice/manage/table/usuario"); ?>"><span>Usuarios</span></a>
                    </li>
 -->
                   



                </ul>

            </div>


        </div>
        <!-- /aside -->
        <hr class="noscreen"/>
        <!-- Content (Right Column) -->
        <div id="content" class="box">
            <p>
                <?php
                $profile = $this->profile();

                if ($profile) {
                    echo "Usuario: <strong>" . $profile->id_usuario . " (" . $profile->nombre . ")" .$profile->Tienda->nombre." Tipo:".$profile->UsuarioTipo->usuario_tipo. "</strong>";

                    if ($profile->super_secure) {
                        echo ' <a href="' . $this->baseUrl("supersecure") . '">ACCESO A FUNCIONES DE USUARIO SUPERSERCURE</a>';
                    }
                }
                ?>
            </p>

            <div id="messages"><?php $this->messenger(); ?></div>
            <?php
            if(!$_SESSION['CADENA']){


                $queryproductos = Doctrine_Query::create()
                    ->from("Database_Model_Producto")
                    ->where("status='ACTIVO'")
                    ->execute();

                $prod="";
                 $id_tienda=$this->profile()->id_tienda;
                foreach($queryproductos as $tipo){   
                    $ejeprecio= Doctrine_Query::create()
                        ->from("Database_Model_EntradaProducto a, a.Entrada b")
                        ->where("a.id_producto=?",$tipo->id_producto)
                        ->andWhere("b.status='ACTIVO'")
                        ->orderBy("id_entrada_producto DESC")
                        ->limit(1);

                    $precio2=0;
                    foreach($ejeprecio->execute() as $ex){
                        $precioBase=$ex["precio"];//sacamos el ultimo precio por fecha mientras no se allan vendido
                        $precio2=$ex["precio"];
                    }
                    if($precio2){
                        $precioBase=$precio2;
                    }
                           
                    $prod=$prod.",'".$tipo->codinter."::".str_replace("'", "", $tipo->nombre)." $". $precioBase."'";
                }

                $cadena = substr($prod,1);
                $_SESSION['CADENA']=$cadena;
            }
             echo $this->layout()->content; ?>
        </div>
        <!-- /content -->
    </div>
    <!-- /cols -->
    <hr class="noscreen"/>

    <!-- Footer -->
    <div id="footer" class="box">
        <p class="t-center"><a href="http://www.789.mx">www.789.mx</a></p>
    </div>
    <!-- /footer -->

</div>
<!-- /main -->
</body>
<script type="text/javascript" src="//api.filepicker.io/v1/filepicker.js"></script>

</html>