<h1>Clientes</h1>
<p class="t-right">
    <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
    </a>
</p>
<table cellspacing="0" class="full-width" id="example">
    <thead>
    <tr>
        <th>Nombre</th>
        <th>Telefono</th>
        <th>Observaciones</th>
        <th>Tienda</th>
        <th>Fecha Registro</th>
        <th width="75">Acciones</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->query as $obj): ?>
    <tr class="main-row">

        <td><?php echo $obj->nombre." ".$obj->ap_paterno." ".$obj->ap_materno; ?></td>
        <td><?php echo $obj->telefono; ?></td>
        <td><?php echo $obj->observaciones; ?></td>
        <td><?php
            $query = Doctrine_Query::create()
                ->from("Database_Model_Tienda")
                ->where("id_tienda=?",$obj->id_tienda)
                ->execute();//verificamos si es adminisrador
            $tienda="";
            foreach($query as $objt){
                $tienda=$objt->nombre;
            }

            echo $tienda; ?></td>
            <td><?php echo $obj->fecha_registro; ?></td>

        <td>
            <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/ver/id/" . $obj->id_persona); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png") ?>" border="0"/>
            </a>
            <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/editar/id/" . $obj->id_persona); ?>">
                <img src="<?php echo $this->baseUrl("css/img/edit.png") ?>" border="0"/>
            </a>
            <a title="Cancelar" tooltip="true" delete="true"
               href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName(). "/borrar/id/"   . $obj->id_persona); ?>">
                <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
        </td>
    </tr>
    
        <?php endforeach; ?>
    </tbody>
</table>

<script type="text/javascript">
  $(function() {

        var table = $('#example').dataTable( {
            "bJQueryUI": true,
            "scrollY": 200,
            "aaSorting": [[1, "asc"]],
            "scrollX": true,
            "iDisplayLength": 25,
            "bPaginate": true,
            "bAutoWidth": true,
            "sPaginationType": "full_numbers",
            "bSort": true,
            "aLengthMenu": [[5, 10, 15, 25, 50, -1], [5, 10, 15, 25, 50, "All"]]
        } );

    });


</script>