<h1>CLIENTES</h1>
<h3 class="tit">VER  CLIENTE</h3>

<form method="post" action="" class="form-horizontal">
    <fieldset>
        <legend>Datos Personales</legend>
        <div class="control-group">
            <label class="control-label">Tipo De Usuario</label>
            <div class="controls">
                <?php

                echo $this->formSelect("id_usuario_tipo", $this->data["id_usuario_tipo"],
                    array("style"=>"width:460px","onchange"=>"muestraidcliente();","required" => "required"),
                    array("1"=>"Cliente"),
                    Database_Model_UsuarioTipo::getAllArr()
                ); ?>
            </div>
        </div>
        <div id="idcliente">
            <div class="control-group">
                <label class="control-label">Nombre Comercial</label>
                <div class="controls">
                    <?php echo $this->formText("razon_social", $this->data["razon_social"]
                    ); ?>
                </div>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Celular Personal</label>
            <div class="controls">
                <?php echo $this->formText("celular", $this->data["celular"],
                    array("" => "")
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Nombre</label>
            <div class="controls">
                <?php echo $this->formText("nombre", $this->data["nombre"],
                    array("required" => "required")
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Apellido Paterno</label>
            <div class="controls">
                <?php echo $this->formText("ap_paterno", $this->data["ap_paterno"],
                    array("required" => "required")
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Apellido Materno</label>
            <div class="controls">
                <?php echo $this->formText("ap_materno", $this->data["ap_materno"],
                    array("required" => "required")
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">R.F.C.</label>
            <div class="controls">
                <?php echo $this->formText("rfc", $this->data["rfc"],
                    array()
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Fecha Nacimiento</label>
            <div class="controls">
                <?php

                echo $this->formText("fecha_nacimiento", $this->data["fecha_nacimiento"],
                    array()
                ); ?>

            </div>
        </div>
    </fieldset>

    <fieldset>
        <legend>Domicilio</legend>
        <div class="control-group">
            <label class="control-label">Calle</label>
            <div class="controls">
                <?php echo $this->formText("calle", $this->data["calle"],
                    array()
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Num Ext.</label>
            <div class="controls">
                <?php echo $this->formText("num_exterior", $this->data["num_exterior"]
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Num Int.</label>
            <div class="controls">
                <?php echo $this->formText("num_interior", $this->data["num_interior"]
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Colonia</label>
            <div class="controls">
                <?php echo $this->formText("colonia", $this->data["colonia"]
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Municipio/Delegación </label>

            <div class="controls">
                <?php echo $this->formText("ciudad", $this->data["ciudad"],
                    array()
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Estado </label>
            <div class="controls">
                <?php echo $this->formText("estado", $this->data["estado"],
                    array()
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Codigo Postal </label>

            <div class="controls">
                <?php echo $this->formText("codigo_postal", $this->data["codigo_postal"],
                    array()
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Email</label>
            <div class="controls">
                <?php echo $this->formText("email", $this->data["email"]
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Lada Telefono</label>
            <div class="controls">
                <?php echo $this->formText("lada", $this->data["lada"]
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Telefono</label>
            <div class="controls">
                <?php echo $this->formText("telefono", $this->data["telefono"]
                ); ?>
            </div>
        </div>

    </fieldset>

    <fieldset>
        <legend>Datos Bancarios</legend>
        <div class="control-group">
            <label class="control-label">Banco</label>
            <div class="controls">
                <?php echo $this->formText("banco", $this->data["banco"],
                    array()
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Cuenta</label>
            <div class="controls">
                <?php echo $this->formText("num_cuenta", $this->data["num_cuenta"]
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Dirección completa (de cuenta)</label>
            <div class="controls">
                <?php echo $this->formText("dir_cuenta", $this->data["dir_cuenta"]
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Tiempo Credito</label>
            <div class="controls">
                <?php echo $this->formText("tiempo_credito", $this->data["tiempo_credito"]
                ); ?>
            </div>
        </div>



    </fieldset>
    <fieldset>
        <legend>Otros</legend>
        <div class="control-group">
            <label class="control-label">observaciones</label>
            <div class="controls">
                <?php echo $this->formText("observaciones", $this->data["observaciones"],
                    array()
                ); ?>
            </div>
        </div>

    </fieldset>
</form>
<script>
    $(document).ready(function () {

        muestraidcliente();
    });
    $(function () {
        //$( "#on_hire_fecha" ).datepicker();
        $("#fecha_nacimiento").datepicker({
            format: 'dd-mm-yyyy'
        });

    });
    //document.getElementById("idcliente").style.display="none";
    function muestraidcliente(){

        if(document.getElementById("id_usuario_tipo").value==1){
            document.getElementById("idcliente").style.display="Inherit";
        }else{
            document.getElementById("idcliente").style.display="none";
        }
    }

</script>