<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Ventas a Credito</h3>

<table cellspacing="0" class="full-width" id="example">
    <thead>
        <tr>
            <th>Ver Venta</th>
            <th>Folio Venta</th>
            <th>Vendedor</th>
            <th>Cliente</th>
            <th>Fecha</th>
            <th>Tipo</th>
            <th>Saldo por Pagar</th>
            <th>Tienda</th>
            <th>Total</th>

            <th></th>
        </tr>
    </thead>
    <tbody>
    <?php
    $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj): ?>
        <tr <?php  if ($obj->cancelado) {
            echo "class='cancelada'";
        }?>
            >

            <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/" . $obj->id_venta); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->folio; ?></td>
            <td><?php echo $obj->Usuario->nombre; ?></td>
            <td><?php echo $obj->Persona->nombre; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td>Por Pagar<?php //echo $obj->tipo; ?></td>
            <td><?php
                $querysaldo = Doctrine_Query::create()
                    ->select("SUM(montoabono) AS saldo")
                    ->from("Database_Model_Deudores")
                    ->where("id_venta =?",$obj->id_venta)
                    ->andWhere("status = ?", "ACTIVA")
                    ->execute();
                foreach($querysaldo as $s){
                    $saldo=$s["saldo"];
                }
                echo "$".number_format($obj->total-$saldo,2);
                ?>
           </td>
            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td>$<?php if (!$obj->cancelado) {
                $total += $obj->total;
            } echo number_format($obj->total, 2); ?></td>
            <td>

                <?php if (!$obj->cancelado): ?>
                <a title="Ver Abonos" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/ver/id/" . $obj->id_venta); ?>">
                     <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a>
                <a  title="Agregar nuevo Abono" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta/id/" . $obj->id_venta); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
                </a>
                    <a title="Cancelar venta" tooltip="true"  fancybox="true"
                       href="<?php echo $this->baseUrl("administracion/devoluciones/mostrarcancelarventa/id/" . $obj->id_venta); ?>">
                        <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
                <?php endif; ?>
            </td>

        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">
     $(function() {

        var table = $('#example').dataTable( {
            "bJQueryUI": true,
            "scrollY": 200,
            "aaSorting": [[4, "desc"]],
            "scrollX": true,
            "iDisplayLength": 10,
            "bPaginate": true,
            "bAutoWidth": true,
            "sPaginationType": "full_numbers",
            "bSort": true,
            "aLengthMenu": [[5, 10, 15, 25, 50, -1], [5, 10, 15, 25, 50, "All"]]
        } );

    });
</script>
