<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Abonos a la Ventas</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>

        <th>Folio Venta</th>
        <th>Vendedor</th>
        <th>Cliente</th>
        <th>Fecha</th>
        <th>Monto</th>
        <th>Comentarios</th>
        <th></th>


    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj): ?>
        <tr <?php  if ($obj->status=="CANCELADO") {
            echo "class='cancelada'";
        }?>
            >


            <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/" . $obj->id_venta); ?>">
                <?php echo $obj->Venta->folio; ?></a></td>
            <td><?php echo $obj->Usuario->nombre; ?></td>
            <td><?php echo $obj->Persona->nombre; ?></td>
            <td><?php echo $obj->fecha_abono; ?></td>

            <td><?php  $tot+=$obj->montoabono; echo "$".number_format($obj->montoabono,2);  ?>
            </td>
            <td><?php echo $obj->comentarios; ?></td>

          <td>
                <?php if ($obj->status!="CANCELADO"): ?>
                    <a title="Cancelar abono" tooltip="true" delete="true"
                       href="<?php echo $this->baseUrl("deudores/administrar/cancelar/id/" . $obj->id_deudores); ?>">
                        <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
                <?php endif; ?>
              <a target="_blank" title="Imprimir Abono" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/imprimir/id/" . $obj->id_deudores); ?>">
                  Imprimir </a>
            </td>

        </tr>
    <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>

        <td>$ <?php echo number_format($tot, 2); ?></td>
        <td></td><td></td>

    </tr>
</table>