<h1>Categorías</h1>
<p class="t-right">
    <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
    </a>
</p>
<?php echo $this->form; ?>
<table class="full-width">
    <thead>
    <tr>
        <th>Nombre</th>
        <th>Descuento</th>
        <th>Descuento activado</th>
        <th width="75">Acciones</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->query as $obj): ?>
    <tr>
        <td><?php echo $obj->categoria; ?></td>
        <td><?php echo number_format($obj->descuento, 2); ?>%</td>
        <td><?php echo $obj->descuento_activado ? "Sí" : "No"; ?></td>


        <td>

            <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/editar/id/" . $obj->id_categoria); ?>">
                <img src="<?php echo $this->baseUrl("css/img/edit.png") ?>" border="0"/>
            </a>
            <a delete="true" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/borrar/id/" . urlencode($obj->id_categoria)); ?>">
                <img src="<?php echo $this->baseUrl("css/img/delete.png") ?>" border="0"/>
            </a>
        </td>
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>