<script type="text/javascript">
    $(document).ready(function () {
        calcTotal = function () {
            var totales=document.getElementsByClassName("totales");
            var total = 0;
            for (var i = 0, len = totales.length; i < len; i++) {
                total = parseFloat(total);
                total += parseFloat(totales[i].innerHTML);
            }
            document.getElementById("total-num").innerHTML=total.toFixed(2);
            document.getElementById("total-global").value=total.toFixed(2);

        }

        $("#agregarprod").click(function (e) {
            e.preventDefault();
            var res =  $('#barcode').val().split("::");
            if(res.length>0){
                $('#barcode').val(res[0].trim());
            }
            var msj="id_prod="+$("#barcode").val().trim()+"&cantidad="+$("#cantidad").val();
           // alert(msj);
            $.get(_root + "/administracion/inventarios/getproducto", msj,
                function (response) {
                    $("table#productos").append(response);
                    calcTotal();
                });
            $("#cantidad").val(1);
            $("#barcode").val("").focus();
            return false;
        });
        $("#barcode").keypress(function(e) {
            if (e.which == 13) {
                e.preventDefault();
                var msj="id_prod="+$("#barcode").val().trim()+"&cantidad="+$("#cantidad").val();
                // alert(msj);
                $.get(_root + "/administracion/inventarios/getproducto", msj,
                    function (response) {
                        $("table#productos").append(response);
                        calcTotal();
                    });
                $("#cantidad").val(1);
                $("#barcode").val("").focus();
                return false;
            }
        });

        $("#barcode").focus(
            function () {
                $(this).addClass("yellow-bg");
            }).blur(function () {
                $(this).removeClass("yellow-bg");
            });

        $("#barcode").focus();


        $("#send").click(function (e) {
            $(".borrar-td").remove();
            $("#ticket-items").val($("#productos").html());

                if(document.getElementById("fecha").value!=""){
                    $(this).hide();
                    $("#main-form").submit();
                }else{
                    alert("Introduce la Fecha de Entrada");
                }

        });


        $(".borrar-producto").live('click', function (e) {
            e.preventDefault();
            var id = $(this).attr("lineid");
            $("[lineid=" + id + "]").remove();
            calcTotal();
        });
    });
    var total1=0;
    function calculaprecio(num){
        document.getElementById("total-num").innerHTML=0;
        var precio2 = (document.getElementById("costo"+num).value *  1.16 *   document.getElementById("multiplicador").value);
       var precio=precio2.toFixed(2);
        document.getElementById("precio"+num).value=precio;
        var importe2 = (document.getElementById("costo"+num).value * document.getElementById("cantidad"+num).innerHTML);
        var importe=importe2.toFixed(2);
        document.getElementById("importe"+num).innerHTML=importe;
        document.getElementById("importe2"+num).value=importe;
       calcTotal2();
    }
    function calcTotal2(){
        var totales=document.getElementsByClassName("totales");
        var total = 0;
        for (var i = 0, len = totales.length; i < len; i++) {
            total = parseFloat(total);
            total += parseFloat(totales[i].innerHTML);
        }
        document.getElementById("total-num").innerHTML=total.toFixed(2);
        document.getElementById("total-global").value=total.toFixed(2);

    }

</script>
<?php
    $cadena=$_SESSION['CADENA'];
?>
<h1>Entradas</h1>
<h3 class="tit">Nueva Entrada de Almacen</h3>



<form action="" id="main-form" method="post">
    <table class="nostyle">
        <div class="control-group">
            <label class="control-label">Fecha Entrada</label>
            <div class="controls">
                <input type="text" required="required" class="small-input" datepicker="past" id="fecha" name="fecha" placeholder="Fecha entrada"/>

            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Referencia</label>
            <div class="controls">
                <input type="text" class="small-field" id="referencia" name="referencia" placeholder="Agregar referencia"/>

            </div>
        </div>


        <div class="control-group" id="" style="display: ">
            <label class="control-label">Almacen </label>
            <div class="controls">
                <?php echo $this->formSelect("id_tienda", 13,
                    array("class" => "chzn-select"),
                    Database_Model_Tienda::getAll()
                ); ?>

            </div>
        </div>
      <input type="text" name="multiplicador" value="1.5" id="multiplicador" style="display: none">




    </table>

    <fieldset>
        <legend>Introducir producto</legend>

            <input type="hidden" id="tipousu" value="<?php echo $this->tipousu; ?>">



            <br />
            <table class="nostyle">
                <tr>
                    <td>   <label for="barcode">Código de barras</label>  </td>
                    <td>   <input type="text" id="barcode"  for='autocomplete' name="id_producto" value="<?php echo $this->codint; ?>"/>      </td>
                    <td>
                        <a fancybox="true" id="catalogo" href="<?php echo $this->baseUrl("ventas/administrar/mostrarcatalogo?id_tienda=".$this->id_tienda); ?>">Catálogo</a>
                    </td>
                </tr>
                <tr>
                    <td>       <label for="cantidad">Cantidad</label>  </td>
                    <td>    <input type="text" class="small-field" id="cantidad" name="cantidad" value="1"/>    </td>
                </tr>
                <tr>
                    <td>        <input type="button" id="agregarprod" value="Agregar"/>         </td>
                </tr>
            </table>
      
    </fieldset>

    <h3 class="tit">Producto</h3>
    <input type="hidden" name="total-global" id="total-global" value="0"/>

    <input type="hidden" name="ticket_items" id="ticket-items" value="0"/>

    <h3 class="total">Costo Total: $<span id="total-num"></span></h3>
    <table id="productos" class="full-width" style="overflow: auto">
        <tr>
            <th>Cantidad</th>
            <th>Codigo Interno</th>
            <th>Producto</th>
            <th>Costo</th>
            <th>Precio</th>
            <th>Precio Mayoreo</th>
            <th>Precio Costo</th>
            <th>Importe</th>
            <th class="borrar-td"></th>
        </tr>
    </table>
    <div style="height: 25px;"></div>
    <hr/>

    <div class="control-group">
        <label class="control-label">Comentarios</label>
        <div class="controls">
            <?php echo $this->formTextarea("comentarios", $this->data["comentarios"],
                array()
            ); ?>
        </div>
    </div>
    <div style="height: 25px;"></div>
    <input style="width: 100%" type="button" id="send" class="button" value="Registrar Entrada">
</form>
<script>
    $( "#barcode" ).autocomplete({
        source: [ <?php echo $cadena ?>],
        select: function(res) {
   
        }
    });
</script>


















