<?php
$lineId = rand(1000, 100000);
if ($this->obj): 
    $idtienda   = $this->id_tienda;
    $precioBase = 0;
    $descuento  = false;
    $precio     = $this->obj->precio;
    $costo      = $this->obj->costo;
    $preciod    = $this->obj->precio_descuento;
    $ejeprecio  = Doctrine_Query::create()
        ->from("Database_Model_EntradaProducto a, a.Entrada b")
        ->where("a.id_producto=?",$this->obj->id_producto)
        //->andWhere("cantvendida<cantidad")
        ->andWhere("b.status='ACTIVO'")
        ->orderBy("id_entrada_producto DESC")
        ->limit(1);

    foreach($ejeprecio->execute() as $ex){
        $precio  = $ex["precio"];//sacamos el ultimo precio por fecha mientras no se allan vendido
        $preciod = $ex["precio_descuento"];//sacamos el ultimo precio por fecha mientras no se allan vendido 
    }

?>
<tr class="producto" lineid="<?php echo $lineId; ?>">
    <input type="hidden" name="id_producto[]" value="<?php echo $this->obj->id_producto; ?>"/>
    <input type="hidden" style="width:40px" id='cantidad_original<?php echo $lineId ?>' placeholder='0' name="cantidad_original[]" value="<?php echo $this->cantidad; ?>"/>
    <td>
        <input type="number" style="width:40px" id='cantidad<?php echo $lineId ?>' placeholder='0' name="cantidad[]" onblur='calculaprecio(<?php echo $lineId ?>)' value="<?php echo $this->cantidad; ?>"/>
    </td>
    <td class='zaragoza' style='<?php if($idtienda!=15){ echo "hidden";} ?>'>
        <input type="number" class='zaragoza' style="width:40px" id='cantidad_zaragoza<?php echo $lineId ?>' placeholder='0' name="cantidad_zaragoza[]" onblur='calculaprecio(<?php echo $lineId ?>)' value="<?php echo 0; ?>"/>
    </td>    
    <td>
        <?php echo $this->obj->codinter; ?>
    </td>
    <td>
        <?php echo $this->obj->nombre; ?>
    </td>
    <td>
        <?php
            echo "<input type='text' name='costo[]' class='small-field'  id='costo".$lineId."' onkeyup=''  style='width: 50' pattern='[0-9]+([\.|,][0-9]+)?>$' placeholder='$0.00' value='".$costo."'>";
        ?>
    </td>
    <td>
        <?php
        echo "<input type='text' name='precio[]' class='small-field' id='precio".$lineId."' style='width: 50' pattern='[0-9]+([\.|,][0-9]+)?>$' placeholder='$0.00'  value='".$precio."' >";
        ?>
    </td>
    <td>
        <?php
        if($this->tipousu==2 ){
            echo "<input type='text' name='precio_descuento[]' class='small-field' id='precio_descuento".$lineId."' style='width: 50' pattern='[0-9]+([\.|,][0-9]+)?>$' placeholder='$0.00'  value='".$preciod."' >";
        }
        ?>
    </td>
    <td>
        <?php
        $importe=$this->cantidad * $costo;
        echo "
        <input class='totales' style='width:40px' type='text' readonly value='".$importe."' name='total[]' id='importe".$lineId."' >";
        ?>
    </td>

    <td class="borrar-td">
        <a href="#" class="borrar-producto" lineid="<?php echo $lineId; ?>">Cancelar</a>
    </td>
</tr>
<?php if ($descuento): ?>
    <tr lineid="<?php echo $lineId; ?>">
        <td>
        </td>
        <td>
            <?php echo $descuento; ?>
        </td>
        <td>
        </td>
        <td>
        </td>
    </tr>
    <?php endif; ?>
<?php endif; ?>