<?php
$lineId = rand(1000, 100000);
if ($this->obj): ?>
<tr class="producto" lineid="<?php echo $lineId; ?>">
    <td>
        <?php echo "<div  id='cantidad".$lineId."' placeholder='$0.00'>".$this->cantidad."</div>";
           ?>


        <input type="hidden" name="id_producto[]" value="<?php echo $this->obj->id_producto; ?>"/>
        <input type="hidden" name="cantidad[]" value="<?php echo $this->cantidad; ?>"/>
    </td>
    <td>
        <?php echo $this->obj->codinter; ?>
    </td>
    <td>
        <?php echo $this->obj->nombre; ?>
    </td>
    <td>
        <?php
        $precioBase = 0;
        $descuento = false;
        $precio=$this->obj->precio;
        $costo=$this->obj->costo;
        $preciod=$this->obj->precio_descuento;
        $precioc=$this->obj->precio_costo;
        $ejeprecio= Doctrine_Query::create()
            ->from("Database_Model_EntradaProducto a, a.Entrada b")
            ->where("a.id_producto=?",$this->obj->id_producto)
            //->andWhere("cantvendida<cantidad")
            ->andWhere("b.status='ACTIVO'")
            ->orderBy("id_entrada_producto DESC")
            ->limit(1);

        foreach($ejeprecio->execute() as $ex){
            $precio=$ex["precio"];//sacamos el ultimo precio por fecha mientras no se allan vendido
            $preciod=$ex["precio_descuento"];//sacamos el ultimo precio por fecha mientras no se allan vendido
            $precioc=$ex["precio_costo"];//sacamos el ultimo precio por fecha mientras no se allan vendido
            $costo=$ex["costo"];//sacamos el ultimo precio por fecha mientras no se allan vendido
        }




        echo "<input type='text' name='costo[]' class='small-field'  id='costo".$lineId."' onkeyup='calculaprecio(".$lineId.")'  style='width: 50' pattern='[0-9]+([\.|,][0-9]+)?>$' placeholder='$0.00' value='".$costo."'>";
          ?>
    </td>
    <td>
        <?php
        echo "<input type='text' name='precio[]' class='small-field' id='precio".$lineId."' style='width: 50' pattern='[0-9]+([\.|,][0-9]+)?>$' placeholder='$0.00'  value='".$precio."' >";
        ?>
    </td>
    <td>
        <?php

        if($this->tipousu==2 || $this->usu=="mariely" ){
            echo "<input type='text' name='precio_descuento[]' class='small-field' id='precio_descuento".$lineId."' style='width: 50' pattern='[0-9]+([\.|,][0-9]+)?>$' placeholder='$0.00'  value='".$preciod."' >";
        }
        ?>
    </td>
    <td>
        <?php

        if($this->tipousu==2 || $this->usu=="mariely" ){
            echo "<input type='text' name='precio_costo[]' class='small-field' id='precio_costo".$lineId."' style='width: 50' pattern='[0-9]+([\.|,][0-9]+)?>$' placeholder='$0.00'  value='".$precioc."' >";
        }
        ?>
    </td>
    <td>

        <input type="hidden" value="<?php echo ($this->cantidad * $precioBase); ?>"/>
        <?php
        $importe=$this->cantidad * $costo;
        echo "<div class='totales'  id='importe".$lineId."'>".$importe."</div><input type='hidden' value='".$importe."' name='total[]' id='importe2".$lineId."' >";
        ?>
    </td>

    <td class="borrar-td">
        <a href="#" class="borrar-producto" lineid="<?php echo $lineId; ?>">Cancelar</a>
    </td>
</tr>
<?php if ($descuento): ?>
    <tr lineid="<?php echo $lineId; ?>">
        <td>
        </td>
        <td>
            <?php echo $descuento; ?>
        </td>
        <td>
        </td>
        <td>
        </td>
    </tr>
    <?php endif; ?>
<?php endif; ?>