<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Yo Amo Comprar</title>

    <script type="text/javascript">
        window.print();
    </script>

    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 11px;
        }
    </style>
</head>
<body style="text-align: center; width: 175px;">
<table width="200px"  style="align:center">
    <tr>
        <td width="50%" colspan="2" style="align:left"><strong>Yo Amo Comprar</strong>
        </td>
    </tr>

</table>



<table width="200px">
    <tr>
        <th>Folio Entrada</th>
        <td> <strong> <u><?php echo $this->obj->id_entrada; ?></u></strong></td>
    </tr>

    <tr>
        <th>Fecha</th>
        <td><?php echo $this->obj->fecha; ?></td>
    </tr>
    <tr>
        <th>Usuario</th>
        <td><?php
            echo $this->obj->id_usuario;; ?></td>
    </tr>
    <tr>
        <th>Estatus</th>
        <td><?php echo $this->obj->status; ?></td>
    </tr>
</table>

<h3>Artículos</h3>
<table width="200px">

    <tr>
        <th>Cant.</th>
        <th>Cod Inter.</th>
        <th>Prod.</th>
        
        <th>Precio</th>
        <?php
            if($this->datauserlogged->id_usuario=='anny'||$this->datauserlogged->id_usuario=='Elena'||$this->datauserlogged->id_usuario_tipo==5){
                echo "<th>Costo</th>";
            }
        ?>
        
        

    </tr>
    <?php
    $total = 0;
    $costo = 0;
    $precio = 0;
    $totalComision = 0;
    $query= Doctrine_Query::create()
        ->from("Database_Model_EntradaProducto")
        ->where("id_entrada=?",$this->obj->id_entrada)
        ->andwhere("cancelado=0")
        ->execute();
    foreach ($query as $obj):
        $costo+=$obj->totalcosto; 
        $precio+=$obj->cantidad*$obj->precio;
    ?>
        <tr >
            <td><?php echo $obj->cantidad; ?></td>
            <td><?php echo $obj->Producto->codinter; ?></td>
            <td><?php echo $obj->nombre; ?></td>
            <td>$<?php  echo number_format($obj->cantidad*$obj->precio, 2); ?></td>
            <?php
            if($this->datauserlogged->id_usuario=='anny'||$this->datauserlogged->id_usuario=='Elena'||$this->datauserlogged->id_usuario_tipo==5){
              
                echo "<td>$".number_format($obj->totalcosto, 2)."</td>";
            }
            ?>

        </tr>
    <?php endforeach; ?>
    <tr>

        <td></td>
        <td></td>
        <td><strong>Totales</strong></td>
        <td>$<?php  echo number_format($precio, 2); ?></td>
        <?php
        if($this->datauserlogged->id_usuario=='anny'||$this->datauserlogged->id_usuario=='Elena'||$this->datauserlogged->id_usuario_tipo==5){
            echo "<td>$".number_format($costo, 2)."</td>";
        }
        ?>
    </tr>
</table>
</body>
</html>


