<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Yo Amo Comprar</title>

    <script type="text/javascript">
        window.print();
    </script>

    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 11px;
        }
    </style>
</head>
<body style="text-align: center; width: 175px;">
<table width="190px"  style="align:center">
    <tr>
        <td width="50%" colspan="2" style="align:left"><strong>Yo Amo Comprar</strong>
        </td>
    </tr>

</table>



<table width="190px">
    <tr>
        <th>Folio Entrada</th>
        <td> <strong> <u><?php echo $this->obj->id_entrada; ?></u></strong></td>
    </tr>

    <tr>
        <th>Fecha</th>
        <td><?php echo $this->obj->fecha; ?></td>
    </tr>
    <tr>
        <th>Usuario</th>
        <td><?php
            echo $this->obj->id_usuario;; ?></td>
    </tr>
    <tr>
        <th>Estatus</th>
        <td><?php echo $this->obj->status; ?></td>
    </tr>
</table>

<h3>Artículos</h3>
<table width="190px">
    <tbody>
    <tr>
        <th>Cant.</th>
       <!-- <th>Codigo Interno</th>  -->
        <th style="width: 80px">&nbsp;&nbsp;&nbsp;&nbsp;Producto&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Subt.</th>
        <th>Total</th>

    </tr>
    <?php
    $total = 0;
    $costo = 0;
    $totalComision = 0;
    $query= Doctrine_Query::create()
        ->from("Database_Model_EntradaProducto")
        ->where("id_entrada=?",$this->obj->id_entrada)
        ->execute();
    $totalieps=0;
    $totaliva=0;
    $show=0;
    foreach ($query as $obj):

        ?>

        <tr  style="font-size: 12px" >
            <td><?php echo $obj->cantidad; ?></td>
           <!-- <td><?php echo $obj->Producto->codinter; ?></td>-->
            <td><?php echo ucwords(strtolower($obj->Producto->nombre)); ?></td>

            <td>$<?php  echo number_format($obj->costo, 2); ?></td>
            <td>$<?php  echo number_format($obj->costo*$obj->cantidad, 2); ?></td>

        </tr>
    <?php endforeach;
    ?>

    </tbody>
   
        <tr>
            <td colspan="4" align="left"><strong>Referencia: <?php echo $this->obj->referencia; ?></strong></td>
        </tr>
  
    <tr>
        <td colspan="4" align="right"><strong>Total Costo $<?php echo number_format($this->obj->gettotales()[1], 2); ?></strong></td>
    </tr>


</table>
</body>
</html>


