<h1>Inventarios</h1>
<p class="t-right">
    <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
    </a>
</p>
    <style type="text/css">
        .cancelada {
            opacity: .5;
        }
    </style>

    <h3 class="tit">Entradas de Almacen</h3>

    <?php echo $this->form; ?>

    <h3 class="tit">Reporte generado</h3>
    <table style="width: 100%"  >
    <tr>
        <th>Ver</th>
        <th>ID</th>
        <th>Referencia</th>
        <th>Fecha</th>
        <th>Tienda</th>
        <th>Cantidad Total</th>
        <?php
            if($this->datauserlogged->id_usuario=='anny'|| $this->datauserlogged->id_usuario=='Elena'|| $this->datauserlogged->id_usuario_tipo==5){
            echo "<th>Costo Total</th>";
            }
        ?>
        <th>Precio Total</th>
        <th>Comentarios</th>
        <th>Usuario</th>

        <th  ></th>
    </tr>
    <?php
    $total = 0;

    $costot = 0;

    $costoieps=0;
    $costoiva=0;
    $costoivat=0;
    $totalComision = 0;

    $preciop=0;
    $preciopt=0;
    $preciot=0;
    foreach ($this->query as $obj): ?>
        <tr <?php
        if ($obj->cancelado) {
            echo "class='cancelada'";
        }?>
            >

            <td><a href="<?php echo $this->baseUrl("administracion/inventarios/ver/id/" . $obj->id_entrada); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->id_entrada; ?></td>
            <td><?php echo $obj->referencia; ?></td>

            <td><?php echo $obj->fecha; ?></td>
            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td><?php
             if (!$obj->cancelado) {
                    $total += $obj->gettotales()[0];
                } echo number_format($obj->gettotales()[0], 0); ?>
            </td>
            <?php
                if($this->datauserlogged->id_usuario=='anny'||$this->datauserlogged->id_usuario=='Elena'||$this->datauserlogged->id_usuario_tipo==5){  
            ?>
                    <td>$ 
                        <?php $costot+=$obj->gettotales()[1]; 
                            echo number_format($obj->gettotales()[1], 2);
                        ?>
                    </td>
                <?php
                }
                ?>
            
            <td>$<?php $preciopt+=$obj->gettotales()[2];  echo number_format($obj->gettotales()[2], 2); ?>
            </td>
           

            <td><?php echo $obj->comentarios; ?></td>
            <td><?php echo $obj->Usuario->nombre; ?></td>
            <td>

                <a title="Validar Entrada" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta/id/" . $obj->id_entrada); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/check.png") ?>" border="0" width="25" height="25"/>
                </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <?php if (!$obj->cancelado): ?>
                    <a title="Cancelar Entrada" tooltip="true" delete="true"
                       href="<?php echo $this->baseUrl("administracion/inventarios/cancelar/id/" . $obj->id_entrada); ?>">
                        <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>

        <td><strong>Totales</strong></td>
        <td> <?php echo number_format($total, 0); ?></td>
        <?php
        if($this->datauserlogged->id_usuario=='anny'||$this->datauserlogged->id_usuario=='Elena'||$this->datauserlogged->id_usuario_tipo==5){
            echo "<td>$".number_format($costot, 2)."</td>";
        }
        ?>
        <td>$<?php echo number_format($preciopt, 2); ?></td>

        <td></td>
        <td></td>
        <td></td>
    </tr>
</table>