<h1>SUPER SECURE</h1>
<h3 class="tit">Ventas a esconder</h3>
<table width="100%">
    <tr>
        <th></th>
        <th>Vendedor</th>
        <th>Fecha</th>
        <th>Tipo</th>
        <th>Total</th>
        <th></th>
    </tr>
    <?php
        $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj): ?>
        <tr>
            <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/".$obj->id_venta); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0" /> </a></td>
            <td><?php echo $obj->Usuario->nombre; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td><?php echo $obj->tipo; ?></td>
            <td><?php $total+=$obj->total; echo number_format($obj->total, 2); ?></td>
            <td><a href="<?php echo $this->baseUrl("supersecure/ventas/esconder/id/".$obj->id_venta); ?>">
                           Esconder</a></td>
        </tr>
        <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>$ <?php echo number_format($total,2); ?></td>
        <td></td>
    </tr>
</table>