<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>Factura</title>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
</head>
<body style="position: relative;">

<span style="position: absolute; top: 10px; left: 10px;"><?php echo $this->obj->razon_social; ?></span>
<span
    style="position: absolute; top: 30px; left: 10px;"><?php echo $this->obj->calle . " " . $this->obj->num_ext . " " . $this->obj->num_int; ?></span>
<span style="position: absolute; top: 45px; left: 10px;"><?php echo $this->obj->colonia; ?></span>
<span style="position: absolute; top: 60px; left: 10px;"><?php echo $this->obj->ciudad; ?></span>
<span style="position: absolute; top: 80px; left: 10px;"><?php echo $this->obj->estado; ?></span>
<span style="position: absolute; top: 100px; left: 10px;"><?php echo $this->obj->codigo_postal; ?></span>
<span style="position: absolute; top: 100px; left: 600px;"><?php echo $this->obj->fecha; ?></span>
<span style="position: absolute; top: 900px; left: 10px;"><?php echo $this->obj->cantidad_letra; ?></span>
<span style="position: absolute; top: 900px; left: 700px;">$<?php echo number_format($this->obj->subtotal, 2); ?></span>
<span style="position: absolute; top: 950px; left: 700px;">$<?php echo number_format($this->obj->iva, 2); ?></span>
<span style="position: absolute; top: 1000px; left: 700px;">$<?php echo number_format($this->obj->total, 2); ?></span>
</body>
</html>