<h1>Reportes</h1>
<ul>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes"); ?>">Ventas</a></li>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/detalles"); ?>">Productos de Ventas</a></li>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/detallesconta"); ?>">Productos de Contabilidad</a></li>
    <!-- <li><a href="<?php echo $this->baseUrl("ventas/reportes/comisiones"); ?>">Generar Comisiones Vendedor</a></li>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/comisionesreporte"); ?>">Reporte de Comisiones Vendedor</a></li>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/corteventa"); ?>">Cortes de Venta</a></li>-->
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/creditos/credito/1"); ?>">Ventas a Credito</a></li>

    <li><a href="<?php echo $this->baseUrl("ventas/reportes/abonos"); ?>">Abonos</a></li>
    <?php
        $fecha = date('Y-m-j');
        $nuevafecha = strtotime ( '-3 day' , strtotime ( $fecha ) ) ;
        $nuevafecha = date ( 'Y-m-j' , $nuevafecha );
         
    ?>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/porcliente?from=".$nuevafecha."&to=".$fecha); ?>">Ventas por Cliente</a></li>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/porproveedor"); ?>">Ventas por proveedor</a></li>
   <li><a href="<?php echo $this->baseUrl("ventas/reportes/pormarca"); ?>">Ventas por marca</a></li>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/porproducto"); ?>">Ventas por producto</a></li>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/descuentos"); ?>">Descuentos a ventas</a></li>
   <!-- <li><a href="<?php echo $this->baseUrl("ventas/reportes/validacionentradas"); ?>">Entradas a Inventario Validadas</a></li>-->
    <!--  <li><a href="<?php echo $this->baseUrl("ventas/reportes/validaciontraspaso"); ?>">Traspasos a Inventario Validados</a></li>-->
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/alertaminimainventario"); ?>">Alertas de Minimo Inventario</a></li>
        <li><a href="<?php echo $this->baseUrl("ventas/reportes/devoluciones"); ?>">Devoluciones</a></li>
    <li><a href="<?php echo $this->baseUrl("ventas/reportes/devolucionesproducto"); ?>">Devoluciones por Productos</a></li>
   <!-- <li><a href="<?php echo $this->baseUrl("facturas/reportes/facturas"); ?>">Reporte de Facturas</a></li>-->

    <li><a href="<?php echo $this->baseUrl("gastos/reportes"); ?>">Gastos</a></li>
    <li><a href="<?php echo $this->baseUrl("asistencia/reportes/"); ?>">Asistencia</a></li>
    <li><a href="<?php echo $this->baseUrl("asistencia/reportes/grafico"); ?>">Asistencia (Gráfico)</a></li>

</ul>