<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Ventas</h3>

<?php echo $this->form; ?>

<?php $url_actual = "http://" . $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
//echo "<strong>$url_actual</strong>";
$pieces = explode("?", $url_actual);
//  count($pieces);
$pieza1="";
$pieza2="";
if(count($pieces)>1){
    $pieza1=$pieces[0]; // piece1
    $pieza2="?".$pieces[1]; // piece2
}

?>

<h3 class="tit">Reporte generado
    <a href="<?php echo $this->baseUrl("facturas/reportes/excelfacturas/".$pieza2); ?>" class="btn btn-app btn-success btn-mini">
        <i class="icon-download bigger-160"></i>
        Exportar
    </a>
</h3>

<table width="100%">
    <tr>
        <th></th>
        <th>No Folio</th>

        <th>Fecha</th>
        <th>Usuario</th>
        <th>Tienda</th>
        <th>Cliente</th>
        <th>Monto Total</th>
        <th>IVA</th>
        <th>IEPS</th>
        <th></th>
    </tr>
    <?php
    $total=$totaliva=$totalieps=0;

    foreach ($this->query as $obj): ?>
        <tr
            <?php if($obj->cancelada){
                echo 'style="opacity: .5;"';
            } ?>
            >
            <td nowrap="nowrap">
                <?php echo $obj->id_factura; ?>
                <?php if ($obj->urlxml): ?>
                    <a target="_blank" href="<?php echo $obj->urlxml; ?>">
                        XML
                    </a>
                    <a target="_blank" href="<?php echo $obj->urlpdf; ?>">
                        PDF
                    </a>
                <?php endif; ?>
            </td>
            <td><?php echo $obj->serie; ?><?php echo $obj->folio; ?></td>
            <td><?php echo $obj->fecha_registro; ?></td>

            <td><?php echo $obj->id_usuario; ?></td>
            <td><?php
                $nomtienda="";
                if($obj->id_usuario){
                    $obju = Doctrine_Core::getTable("Database_Model_Usuario")->findOneBy("id_usuario", $obj->id_usuario);
                    if($obju){
                        $nomtienda=$obju->Tienda->nombre;
                    }
                }
                echo $nomtienda; ?></td>
            <td><?php echo $obj->id_persona; ?> | <?php echo $obj->Persona->nombre; ?></td>
            <td>$<?php echo number_format($obj->total, 2); ?></td>
            <td>$<?php  echo number_format($obj->iva, 2); ?></td>
            <td>$<?php  echo number_format($obj->ieps, 2); ?></td>
            <td>
                <?php if($obj->cancelada): ?>
                    Cancelada por <?php echo $obj->id_usuariocancelacion."<br>".$obj->fecha_cancelacion?>
                <?php else:
                    $total+=$obj->total;
                    $totaliva+=$obj->iva;
                    $totalieps+=$obj->ieps;
                    ?>
                    <a delete="true"
                       href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/cancelar/id/" . $obj->id_factura); ?>">
                        <img src="<?php echo $this->baseUrl("css/img/delete.png") ?>" border="0"/>
                    </a>
                <?php endif; ?>
            </td>


        </tr>
    <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>$ <?php echo number_format($total, 2); ?></td>
        <td>$ <?php echo number_format($totaliva, 2); ?></td>
        <td>$ <?php echo number_format($totalieps, 2); ?></td>
    </tr>
</table>