<script type="text/javascript">
    $(document).ready(function () {
        calcTotal = function () {

            var totales=document.getElementsByClassName("totales");
            var total = 0;
            for (var i = 0, len = totales.length; i < len; i++) {
                total = parseFloat(total);
                total += parseFloat(totales[i].innerHTML);
            }
            document.getElementById("total-num").innerHTML=total;
            document.getElementById("total-global").value=total;
        }

        $("#barcode-form").submit(function (e) {
            e.preventDefault();
            var res =  $('#barcode').val().split("::");
            if(res.length>0){
                $('#barcode').val(res[0].trim());
            }
            var id_tienda=document.getElementById("id_tienda").value;
            var barcode=document.getElementById("barcode").value;
            var msj=$(this).serialize()+"&id_tienda="+id_tienda+"&barcode="+barcode;
            //alert(msj);
            $.get(_root + "/administracion/salida/getproducto", msj,
                function (response) {
                    $("table#productos").append(response);
                    calcTotal();
                });
            $("#cantidad").val(1);
            $("#barcode").val("").focus();
            return false;
        });

        $("#barcode").focus(
            function () {
                $(this).addClass("yellow-bg");
            }).blur(function () {
                $(this).removeClass("yellow-bg");
            });

        $("#barcode").focus();


        $("#send").click(function (e) {
            if(document.getElementById("fecha").value!=""){
                $(".borrar-td").remove();
                $("#ticket-items").val($("#productos").html());
                $(this).hide();
                calcTotal();
                $("#main-form").submit();
            }else{
                alert("Selecciona una fecha");
            }

        });


        $(".borrar-producto").live('click', function (e) {
            e.preventDefault();
            var id = $(this).attr("lineid");
            $("[lineid=" + id + "]").remove();
            calcTotal();
        });
    });
    var total1=0;
    function calculaprecio(num){
        document.getElementById("total-num").innerHTML=0;
        var precio2 = (document.getElementById("costo"+num).value *  1.16 *   document.getElementById("multiplicador").value);
       var precio=precio2.toFixed(2);
        document.getElementById("precio"+num).value=precio;
        var importe2 = (document.getElementById("costo"+num).value * document.getElementById("cantidad"+num).innerHTML);
        var importe=importe2.toFixed(2);
        document.getElementById("importe"+num).innerHTML=importe;
        document.getElementById("importe2"+num).value=importe;
       calcTotal2();
    }
function calcTotal2(){
    var totales=document.getElementsByClassName("totales");
    var total = 0;
    for (var i = 0, len = totales.length; i < len; i++) {
        total = parseFloat(total);
        total += parseFloat(totales[i].innerHTML);
    }
    document.getElementById("total-num").innerHTML=total;
    document.getElementById("total-global").value=total;

}

</script>
<?php
    $cadena=$_SESSION['CADENA'];
?>
<h1>Salidas</h1>
<h3 class="tit">Nueva Salida de Almacen</h3>

<fieldset>
    <legend>Introducir producto</legend>
    <form id="barcode-form">
        <input type="hidden" id="tipousu" value="<?php echo $this->tipousu; ?>">



        <br />
        <table class="nostyle">
            <tr>
                <td>   <label for="barcode">Código de barras</label>  </td>
                <td>   <input type="text" id="barcode" name="id_producto" value="<?php echo $this->codint; ?>"/>      </td>
                <td> <a fancybox="true" href="<?php echo $this->baseUrl("ventas/administrar/mostrarcatalogo"); ?>">Catálogo</a>  </td>
            </tr>
            <tr>
                <td>       <label for="cantidad">Cantidad</label>  </td>
                <td>    <input type="text" class="small-field" id="cantidad" name="cantidad" value="1"/>    </td>
            </tr>
            <tr>
                <td>        <input type="submit" value="Agregar"/>         </td>
            </tr>
        </table>
    </form>
</fieldset>


<form action="" id="main-form" method="post">
    <h3 class="tit">Producto</h3>
    <input type="hidden" name="total-global" id="total-global" value="0"/>

    <input type="hidden" name="ticket_items" id="ticket-items" value="0"/>

    <h3 class="total">Costo Total: $<span id="total-num"></span></h3>
    <table id="productos" class="full-width">
        <tr>
            <th>Cantidad</th>
            <th>Codigo Interno</th>
            <th>Producto</th>
            <th>Costo</th>
            <th>Precio</th>
            <th>Precio Mayoreo</th>
            <th>Importe</th>
            <th class="borrar-td"></th>
        </tr>
    </table>
    <div style="height: 25px;"></div>
    <hr/>
    <div class="control-group" id="" style="display: ">
        <div class="control-group" id="tiendaorigen" style="display: ">
            <label class="control-label">ORIGEN </label>
            <div class="controls">
                <?php

                    echo $this->formSelect("id_tienda",$this->idtienda,
                        array("style"=>"width:460px","required" => "required"),
                        Database_Model_Tienda::getAll2()
                    );

                ?>

            </div>
        </div>

    </div>
    <div class="control-group" id="" style="display: ">
        <div class="control-group" id="tiendaorigen" style="display: ">
            <label class="control-label">DESTINO </label>
            <div class="controls">
                <?php

                    echo $this->formSelect("id_tiendaanterior",14,
                        array("style"=>"width:460px","required" => "required","disabled" => "disabled"),
                        Database_Model_Tienda::getAll2()
                    );

                ?>

            </div>
        </div>

    </div>
    

    <div class="control-group">
        <label class="control-label">Comentarios</label>
        <div class="controls">
            <?php echo $this->formText("comentarios", $this->data["comentarios"],
                array()
            ); ?>
        </div>
    </div>

    <table class="nostyle">

        <tr>
            <td><label>Referencia</label></td>
            <td>
                <input type="text" class="small-field" id="referencia" name="referencia" placeholder="Agregar referencia"/>
            </td>
        </tr>

        <tr>
            <td><label>Fecha Salida</label></td>
            <td>
                <input type="text" class="small-input" datepicker="past" id="fecha" value='<?php echo date('Y-m-d')?>' name="fecha" placeholder="Fecha Salida"/>
            </td>

        </tr>

    </table>
    <div style="height: 25px;"></div>
    <input style="width: 100%" type="button" id="send" class="button" value="Registrar Salida">
</form>
<script>
    $( "#barcode" ).autocomplete({
        source: [ <?php echo $cadena ?>],
        select: function(res) {
   
        }
    });
</script>
















