<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Trepsi</title>

    <script type="text/javascript">
        window.print();
    </script>

    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 15px;
        }
    </style>
</head>
<body style="text-align: center; width: 175px;">
<table width="1000" border="0">
    <tr colspan="3" align="left">
        <td width="807">Trepsi salida de Productos</td>
        <td width="0"></td>
    </tr>
    <tr>
        <td colspan="3" align="left"><label style="font-size:14px">Mexico D.F. a &nbsp;<?php echo $this->obj->fecha; ?> </label></td>
        <td width="177"><label style="font-size:14px">Folio:<label style="color:#F00"> No.&nbsp; <?php echo $this->obj->id_salida; ?></label></label></td>
    </tr>
    <tr colspan="3" align="left">
        <td><label style="font-size:14px">Referencia:<label style="color:#120000"> No.&nbsp; <?php echo $this->obj->referencia; ?></label></label></td>
        <td width="0"></td>
    </tr>
    <tr>
        <td colspan="4" align="left"><label style="font-size:14px">Concepto &nbsp;<?php echo $this->obj->concepto; ?> </label></td>
    </tr>
    <tr>
        <td colspan="4" align="left"><label style="font-size:14px">Tienda Origen &nbsp;<?php
                $obj = Doctrine_Core::getTable("Database_Model_Tienda")->findOneBy("id_tienda", $this->obj->id_tiendaanterior);
                echo strtoupper($obj->nombre); ?> </label></td>
    </tr>
    <tr>
        <td colspan="4" align="left"><label style="font-size:14px"> Destino &nbsp; SALIDA DE INVENTARIO </label></td>
    </tr>
    <tr>
        <td colspan="4" align="left"><label style="font-size:14px">Usuario &nbsp;<?php echo $this->obj->id_usuario; ?> </label></td>
    </tr>
</table>
<h3>Artículos</h3>
<table width="1000">
    <tr>
        <th>Cod Inter.</th>
        <th>Producto</th>
        <th>Cantidad</th>
        <th>Costo</th>
        <th>Costo Total</th>
    </tr>
    <?php
    $totalieps=0;
    $totalieps1=0;
    $totaliva=0;
    $cantieps=0;
    $cantiva=0;
    $totalexento=0;
    $total = 0;
    $costo = 0;
    $totalComision = 0;
    $query= Doctrine_Query::create()
        ->from("Database_Model_SalidaProducto")
        ->where("id_salida=?",$this->obj->id_salida)
        ->execute();
    $cant=0;
    foreach ($query as $obj):
        $productot = Doctrine_Query::create()
            ->from("Database_Model_Producto")
            ->where("id_producto =?",$obj->id_producto )
            ->fetchOne();
        $impuesto = 1;
        if($productot->exento_iva>0){//puede tener ieps o estar exento
            if($productot->exento_ieps==0) {//si tiene 0 tiene ieps
                $impuesto = 1.08;
                $totalieps1 += $obj->totalcosto;
                $cantieps += $obj->cantidad;
                if ($productot->exento_ieps == 0) {
                    $totalieps += (($obj->totalcosto) / 1.08) * 0.08;
                    $totalsinimpuestoieps += ($obj->totalcosto) / 1.08;
                }
            }else{//si excentoipes=1 quiere decir qeu esta excento de impuestos
                $totalexento += ($obj->totalcosto) ;
            }
        }else{
            echo $obj->Producto->codinter;
            //echo "iva=";
            $impuesto=1.16;
            $cantiva+=$obj->cantidad;
            $totaliva+=(($obj->totalcosto)/1.16)*0.16;
            $totalsinimpuestoiva+=($obj->totalcosto)/1.16;
        }


        ?>
        <tr >

            <td><?php echo $obj->Producto->codinter; ?></td>
            <td><?php echo $obj->nombre; ?></td>
            <td align=""><?php $cant+=$obj->cantidad; echo $obj->cantidad; ?></td>
            <td align="">$<?php  echo number_format($obj->costo, 2); ?></td>

            <td align="">$<?php $costo+=$obj->totalcosto; echo number_format($obj->totalcosto, 2); ?></td>
            <td>
                <label>Imp.</label>
                <?php
                $var=$counter>0?$counter:"";
                echo "<input type='hidden' name='impuesto[]'  class='small-field  impuesto' impuesto='X-X".$var."' id value='".$impuesto."' >";
                if($impuesto==1){
                    echo "Excento";
                }
                if($impuesto==1.08){
                    echo "IEPS";
                }
                if($impuesto==1.16){
                    echo "IVA";
                }

                echo $impuesto;?>
            </td>
        </tr>
    <?php

    endforeach;
    ?>
    <tr>
        <td colspan="6"></td>
    </tr>
    <tr>
        <td colspan="1">&nbsp;</td>
        <td align=""><strong>Total</strong></td>
        <td colspan=""><?php echo number_format($cant, 0); ?></td>

        <td align=""><strong>Sub Total</strong></td>
        <td> $<?php echo number_format($costo, 2); ?></td>
    </tr>

    <tr>
        <td colspan="3"></td>
        <td><strong>Monto IVA.</strong></td>
        <td><?php echo number_format(($totaliva),2,".",",");?></td>
    </tr>
    <tr> <td colspan="3"></td>
        <td><strong>Monto IEPS.</strong></td>
        <td><?php echo number_format(($totalieps),2,".",",");?></td>
    </tr>
    <tr> <td colspan="3"></td>
        <td><strong>Monto Exento.</strong></td>
        <td><?php echo number_format(($totalexento),2,".",",");?></td>
    </tr>
    <tr> <td colspan="3"></td>
        <td><strong>Total:</strong></td>
        <td><?php echo number_format(($totalieps+$totaliva+$costo),2,".",",");?></td>
    </tr>

</table>

</body>
</html>