<h1>Salidas</h1>
<p class="t-right">
    <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
    </a> 
</p>
    <style type="text/css">
        .cancelada {
            opacity: .5;
        }
    </style>

    <h3 class="tit">Salidas de Productos</h3>

    <?php echo $this->form; ?>

    <h3 class="tit">Reporte generado</h3>
    <table width="100%">
        <tr>
            <th >Ver</th>
            <th>ID</th>
            <th>Referencia</th>
            <th>Fecha</th>
            <th>Origen</th>
            <th>Concepto</th>
            <th>Suma Total</th>
            <th>Costo Total</th>
            <th>Status</th>
            <th>Usuario</th>
            <th>Comentarios</th>
            <th ></th>
        </tr>
        <?php
        $total = 0;
        $costo = 0;
        $totalComision = 0;
        foreach ($this->query as $obj): ?>
            <tr <?php  if ($obj->cancelado) {
                echo "class='cancelada'";
            }?>
                >

                <td><a href="<?php echo $this->baseUrl("administracion/salida/ver/id/" . $obj->id_salida); ?>">
                        <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
                <td><?php echo $obj->id_salida; ?></td>
                <td><?php echo $obj->referencia; ?></td>

                <td><?php echo $obj->fecha; ?></td>
                <td><?php echo $obj->Tienda->nombre; ?></td>
                <td><?php echo $obj->concepto; ?></td>

                <td>$<?php if (!$obj->cancelado) {
                        $total += $obj->total;
                    } echo number_format($obj->total, 2); ?></td>
                <td>$<?php if (!$obj->cancelado) {
                        $costo += $obj->costo_total;
                    } echo number_format($obj->costo_total, 2); ?></td>
                <td><?php echo $obj->status; ?></td>
                <td><?php echo $obj->id_usuario; ?></td>
                <td><?php echo $obj->comentarios; ?></td>

                <td>
                    <?php if (!$obj->cancelado){?>
                        <?php if ($obj->status=="POR AUTORIZAR"){ ?>
                        <a title="Validar Salida" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/Validasalida/alta/id/" . $obj->id_salida); ?>">
                            <img src="<?php echo $this->baseUrl("css/img/check.png") ?>" border="0" width="25" height="25"/>
                        </a>
                            <a title="Cancelar Salida" tooltip="true" delete="true"
                               href="<?php echo $this->baseUrl("Validasalida/cancelar/id/" . $obj->id_salida); ?>">
                                <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>

                        <?php }else{?>
                            <a title="Cancelar Salida" tooltip="true" delete="true"
                               href="<?php echo $this->baseUrl("administracion/salida/cancelar/id/" . $obj->id_salida); ?>">
                                <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>

                       <?php } ?>

                    <?php } ?>
                </td>


            </tr>
        <?php endforeach; ?>
        <tr>
            <td></td>

            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td><strong>Totales</strong></td>
            <td>$ <?php echo number_format($total, 2); ?></td>
            <td>$ <?php echo number_format($costo, 2); ?></td>
        </tr>
    </table>