<h1>Productos Traspasos</h1>
<div align="rigth">

</div>
<p class="t-right"><input type="hidden" id="baseurl" value="<?php echo $this->baseUrl($this->request->getModuleName(). "/" .$this->request->getControllerName()."/"); ?>">
    <a title="Ver Traspasos" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/ver"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a>
</p>

<?php echo $this->form; ?>
<table class="full-width">
    <thead>
    <tr>
        <th>Cont.</th>
        <th>Codigo Inter.</th>
        <th>Nombre</th>
        <th>Marca</th>
        <th>Categoría</th>
        <th>Proveedor</th>
        <?php
        if($this->tipousu=="2"){
            ?>
            <th>Costo</th>
        <?php
        }?>
        <th>Precio</th>
        <th>Existencias</th>

    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($this->query as $obj):// de producto ?>
        <tr tooltip="true" title="Código de barras: <?php echo $obj->codbarras; ?>">

            <td><?php echo $this->counter++; ?></td>
            <td><?php echo $obj->codinter; ?></td>
            <td> <a fancybox="true" href="<?php echo $this->baseUrl("administracion/productos/detallesproducto/id/".$obj->id_producto); ?>">
                    <?php echo $obj->nombre; ?> </a>
            </td>
            <td><?php echo $obj->Marca->nombre; ?></td>
            <td><?php echo $obj->Categoria->categoria; ?></td>
            <td><?php echo $obj->Proveedor->nombre_corto; ?></td>
            <?php
            if($this->tipousu=="2"){
                ?>
                <td>$<?php echo number_format($obj->costo, 2); ?></td>
            <?php
            }?>

            <?php

            ////////////////////existencias
            if($this->tipousu=="2"){//administrador
                $query = Doctrine_Query::create()
                    ->select("ifnull(sum(existencias),0) totexistencias")
                    ->from("Database_Model_ProductoTienda")
                    ->where("id_producto=?",$obj->id_producto);
                //  echo $query->getSqlQuery();//imprime la consulta qu ese esta generando
                // ->execute();//verificamos si es adminisrador
                foreach($query->execute() as $objt){
                    $totexistencias=$objt["totexistencias"];
                }
            }else{

                $query = Doctrine_Query::create()
                    ->select("ifnull(sum(existencias),0) totexistencias")
                    ->from("Database_Model_ProductoTienda")
                    ->where("id_producto=?",$obj->id_producto)
                    ->andWhere("tienda_id_tienda=?",$this->tienda)
                    ->execute();//verificamos si es adminisrador

                foreach($query as $objt){
                    $totexistencias=$objt["totexistencias"];
                }
            }
            ////////////////////////////////precio
            $ejeprecio= Doctrine_Query::create()
                ->from("Database_Model_EntradaProducto")
                ->where("id_producto=".$obj->id_producto)
                //->andWhere("cantvendida<cantidad")
                ->andWhere("status='ACTIVO'")
                ->orderBy("id_entrada_producto DESC")
                ->limit(1);
            
            $existentes=$totexistencias;
            foreach($ejeprecio->execute() as $ex){
                $existentes=$ex["cantidad"]-$ex["cantvendida"];
                $precio2=$ex["precio"];//sacamos el ultimo precio por fecha mientras no se allan vendido
            }
            if($precio2>0){
                $precio=$precio2;
            }else{
                $precio=$obj->precio;
            }

            ?>
            <td  title="<?php echo "Existentes con este precio: ".$existentes; ?>">$<?php echo number_format($precio, 2); ?></td>
            <td><?php
                echo $totexistencias;
                // echo $obj->existencias; ?></td>


        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>