<h1>Productos Traspasos</h1>

<?php echo $this->form; ?>
<table class="full-width">
    <thead>
    <tr>
        <th>Cont.</th>
        <th>Codigo Inter.</th>
        <th>Nombre Producto</th>
        <th>Tienda Origen</th>
        <th>Tienda Destino</th>
        <th>Cantidad</th>
        <th>Fecha Traspaso</th>
        <th>Usuario</th>

    </tr>
    </thead>
    <tbody>
    <?php
    //var_dump($this->query );
    foreach ($this->query as $obj):// de producto ?>
        <tr tooltip="true" title="Código de barras: <?php echo $obj->ProductoTienda->Producto->codbarras; ?>">

            <td><?php echo $this->counter++; ?></td>
            <td><?php echo $obj->ProductoTienda->Producto->codinter; ?></td>
            <td>  <?php echo $obj->ProductoTienda->Producto->nombre; ?> </td>
            <td><?php
                $ejeprecio= Doctrine_Query::create()
                    ->from("Database_Model_Tienda")
                    ->where("id_tienda=".$obj->idtiendaanterior)
                    ->limit(1);
                $tiendaant="";
                $existentes=$totexistencias;
                foreach($ejeprecio->execute() as $ex){
                    $tiendaant=$ex["nombre"];

                }

               echo $tiendaant ?></td>
            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td><?php echo $obj->cantidad; ?></td>
            <td><?php echo $obj->fecha_traspaso; ?></td>
            <td><?php echo $obj->id_usuario; ?></td>


        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>