<h1>Reportes</h1>
<h3 class="tit">Gastos</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th>Concepto</th>
        <th>Fecha</th>
        <th>Total</th>
    </tr>
    <?php
    $total = 0;
    foreach ($this->query as $obj): ?>
        <tr>
            <td><?php echo $obj->concepto; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td><?php $total+=$obj->monto; echo number_format($obj->monto, 2); ?></td>
        </tr>
        <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td>$ <?php echo number_format($total, 2); ?></td>
    </tr>
</table>