<h1>Paquetes</h1>

    <style type="text/css">
        .cancelada {
            opacity: .5;
        }
    </style>

    <h3 class="tit">Paquetes de Productos</h3>

    <?php echo $this->form; ?>

    <h3 class="tit">Reporte generado</h3>
    <table width="100%">
        <tr>

            <th>Codigo Interno Paquete</th>
            <th>Nombre Paquete</th>
            <th>Cantidad</th>
            <th>Codigo Interno Piezas</th>
            <th>Nombre Piezas</th>
            <th>Comentarios</th>
            <th ></th>
        </tr>
        <?php
        $total = 0;
        $costo = 0;
        $totalComision = 0;
        foreach ($this->query as $obj): ?>
            <tr <?php  if ($obj->status=="BAJA") {
                echo "class='cancelada'";
            }?>
                >

               <!-- <td><a href="<?php echo $this->baseUrl("administracion/salida/ver/id/" . $obj->id_paquete); ?>">
                        <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td> -->
                <td><?php echo $obj->Producto->codinter; ?></td>
                <td><?php echo $obj->Producto->nombre; ?></td>
                <td><?php echo $obj->cantidad; ?></td>

                <td><?php
                    $obj2 = Doctrine_Core::getTable("Database_Model_Producto")->findOneBy("id_producto", $obj->id_productocompuesto);
                    if (!$obj2) {
                        echo "error";
                    }

                    echo $obj2->codinter; ?></td>
                <td><?php echo $obj2->nombre; ?></td>
                <td><?php echo $obj->comentarios; ?></td>


                <td>
                    <?php if ($obj->status!="BAJA"){?>

                            <a title="Borrar Producto" tooltip="true" delete="true"
                               href="<?php echo $this->baseUrl("administracion/paquete/cancelar/id/" . $obj->id_paquete); ?>">
                                <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>



                    <?php } ?>
                </td>



            </tr>
        <?php endforeach; ?>

    </table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>