<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Abonos</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th></th>
        <th>No Folio</th>

        <th>Cliente</th>
        <th>Vendedor</th>
        <th>Fecha</th>
        <th>Fecha Registro</th>
        <th>Tipo</th>
        <th>Tienda</th>
        <th>Total</th>
        <th>Comentarios</th>
       
            <th></th>


    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    $totdesc=0;
    $totalcancel=0;
    $totalsincom=0;
    $mayoreo=0;
    foreach ($this->query as $obj):
  
        ?>
        <tr <?php  if ($obj->status=='CANCELADO') {
            echo "class='cancelada'";
        }?> >

            <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/" . $obj->id_venta); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->Venta->folio; ?></td>
            <td><?php
                echo  $obj->Persona->nombre; ?></td>
            <td><?php echo $obj->id_usuario; ?></td>
            <td><?php echo $obj->fecha_abono; ?></td>
            <td><?php echo $obj->fecha_registro; ?></td>
            <td><?php echo $obj->Venta->tipo."<br>";
                if($obj->Venta->icredito){
                    echo "<span style='color:red'>En pago</span>";

                }
                ?></td>

            <td><?php echo $obj->Venta->Tienda->nombre; ?></td>
            <td>$<?php if ($obj->status=='ACTIVA') {
                $total += $obj->montoabono;
            } echo number_format($obj->montoabono, 2); ?></td>
            <td><?php echo $obj->comentarios; ?></td>
          
                <td>

                    <?php if ($obj->status=='ACTIVA'): ?>
                        <a title="Ver Abonos" href="<?php echo $this->baseUrl("deudores/administrar/ver/id/" . $obj->id_venta); ?>">
                            <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a>
                        <a  title="Agregar nuevo Abono" href="<?php echo $this->baseUrl("deudores/administrar/alta/id/" . $obj->id_venta); ?>">
                            <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
                        </a>
                        <a title="Cancelar Abono" tooltip="true" delete="true"
                           href="<?php echo $this->baseUrl("ventas/administrar/cancelarabono/id/" . $obj->id_deudores); ?>">
                            <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
                    <?php endif; ?>
                </td>

            


        </tr>

        <?php 
    endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>$<?php  echo number_format($total, 2); ?></strong>        </td>
        <td></td>
        <td></td>
    </tr>

</table>
<br>


</table>