<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Alertas</h1>
<h3 class="tit">Alerta de Minimo Inventario</h3>

<label>Buscar </label>
<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th>Codigo Interno</th>
        <th>Nombre</th>
        <th>Tienda</th>
        <th>Existencias</th>
        <th>Alerta Minima</th>

    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj): ?>
        <tr >

           <!-- <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/" . $obj->id_producto); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
                -->
            <td><?php echo $obj->Producto->codinter; ?></td>
            <td><?php echo $obj->Producto->nombre; ?></td>
            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td><?php echo $obj->existencias; ?></td>
            <td><?php echo $obj->alerta_minima2; ?></td>



        </tr>
        <?php endforeach; ?>

</table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>