<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Comisiones Vendedor</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th>No Folio</th>


        <th>Fecha Inicial</th>
        <th>Fecha Final</th>
        <th>Vendedor</th>
        <th>Total Ventas</th>

        <th>Dias Asistencia</th>
        <th>Desc Gtos</th>
        <th>Monto Comisionable</th>

        <th>Porcentaje Comision</th>
        <th>Total Comision</th>
        <th>Fecha Registro</th>
        <th>Usuario Alta</th>
        <th>Tienda</th>
    </tr>
    <?php
    $totalvtas = 0;
    $totalasis = 0;
    $descgastos = 0;
    $montocomi = 0;

    $totalcomi = 0;
    $totalComision = 0;
    foreach ($this->query as $obj): ?>
        <tr <?php  if ($obj->status=='BAJA') {
            echo "class='cancelada'";
        }?>
            >
            <td><?php echo $obj->Comisiones->id_comisiones; ?></td>

            <td><?php echo $obj->Comisiones->fecha_inicial; ?></td>
            <td><?php echo $obj->Comisiones->fecha_final; ?></td>
            <td><?php echo $obj->idsusuario; ?></td>
            <td><?php $totalvtas+=$obj->totalvtas; echo $obj->totalvtas; ?></td>

            <td><?php $totalasis+=$obj->totalasis; echo $obj->totalasis; ?></td>

            <td><?php $descgastos+=$obj->descgastos; echo $obj->descgastos; ?></td>

            <td><?php  $montocomi+=$obj->montocomi; echo $obj->montocomi; ?></td>

            <td><?php  echo $obj->porcen; ?></td>

            <td><?php $totalcomi+=$obj->totalcomi; echo $obj->totalcomi; ?></td>
            <td><?php echo $obj->Comisiones->fecha_registro; ?></td>
            <td><?php echo $obj->Comisiones->id_usuario; ?></td>
            <td><?php echo $obj->Tienda->nombre; ?></td>
        </tr>
        <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>$<?php echo number_format($totalvtas, 2); ?></td>
        <td><?php echo number_format($totalasis, 0); ?></td>
        <td>$<?php echo number_format($descgastos, 2); ?></td>
        <td>$<?php echo number_format($montocomi, 2); ?></td>
        <td></td>
        <td>$<?php echo number_format($totalcomi, 2); ?></td>
        <td></td>
        <td></td>   <td></td>
    </tr>
</table>