<script type="text/javascript">

</script>

<h1>Corte de Ventas</h1>

<h3 class="tit">Ver venta</h3>
<a href="<?php echo $this->baseUrl("ventas/reportes/imprimircorteventa/?from=".$_GET['from']."&to=".$_GET['to']."&id_usuario=".$_GET['id_usuario']."&id_tienda=".$_GET['id_tienda']."&Generar=Generar"); ?>" target="_blank">Imprimir
    Reporte</a>
<style type="text/css">}
    .cancelada {
        opacity: .5;
    }
</style>
<?php echo $this->form; ?>
<table>
    <tr>
        <th>Vendedor</th>
        <td><?php echo $this->usu; ?></td>
    </tr>
    <tr>
        <th>Fecha</th>
        <td><?php echo date("Y-m-d H:i:s") ?></td>
    </tr>

</table>

<h3 class="tit">Artículos</h3>
<table width="100%">
    <tr>
        <th>Tipo de Pago </th>


        <th>Tienda</th>
        <th>Vendedor</th>
        <th>Fecha</th>
        <th>Total</th>
        <th>Sumado a Total</th>
    </tr>
    <?php
    $total = 0;
    $costo = 0;
    $totalComision = 0;
    $totalabonos=0;
    $conbranza=0;
    $totcredito=0;
    $desctt=0;
    foreach ($this->querydesc as $objdesc){
        if($iddesc=$objdesc->id_descuentos){
            $desctt+=$objdesc->montodesc;
        }
    }
    $devoluciones=0;
    $listaMd=""; $listaHd=""; $listaBd="";$listaEd=""; $listaB1d=""; $listaB2d=""; $listaPd="";
    $listaMdp=""; $listaHdp=""; $listaBdp="";$listaEdp=""; $listaB1dp=""; $listaB2dp=""; $listaPdp="";
    foreach ($this->querydev as $objdev){
        if($iddev=$objdev->id_ventacancelada){
            $devoluciones+=$objdev->total;
            switch ($objdev->Venta->id_tienda) {
                case "1":
                    $listaMd += " " . $objdev->Venta->folio;
                    break;
                case "2":
                    $listaHd += " " . $objdev->Venta->folio;
                    break;
                case "3":
                    $listaBd += " " . $objdev->Venta->folio;
                    break;
                case "5":
                    $listaEd += " " . $objdev->Venta->folio;
                    break;
                case "6":
                    $listaB1d += " " . $objdev->Venta->folio;
                    break;
                case "7":
                    $listaB2d += " " . $objdev->Venta->folio;
                    break;
                case "8":
                    $listaPd += " " . $objdev->Venta->folio;
                    break;
            }

        }
    }
    foreach ($this->querydevp as $objdevp){
        if($iddevp=$objdevp->id_venta_productocancelado){
            $devoluciones+=$objdevp->total;
            switch ($objdevp->ProductosVenta->Venta->id_tienda) {
                case "1":
                    $listaMdp += " " . $objdevp->ProductosVenta->Venta->folio;
                    break;
                case "2":
                    $listaHdp += " " . $objdevp->ProductosVenta->Venta->folio;
                    break;
                case "3":
                    $listaBdp += " " . $objdevp->ProductosVenta->Venta->folio;
                    break;
                case "5":
                    $listaEdp += " " . $objdevp->ProductosVenta->Venta->folio;
                    break;
                case "6":
                    $listaB1dp += " " . $objdevp->ProductosVenta->Venta->folio;
                    break;
                case "7":
                    $listaB2dp += " " . $objdevp->ProductosVenta->Venta->folio;
                    break;
                case "8":
                    $listaPdp += " " . $objdevp->ProductosVenta->Venta->folio;
                    break;
            }
        }

    }
    foreach ($this->query as $obj){
    ?>

        <tr <?php  if ($obj->abono==0 && $obj->tipo=="Credito") {
            echo "class='cancelada'";
        }?>  >
            <td><?php
                if ($obj->abono==1 && ($obj->tipo=="Credito"||$obj->tipo=="credito")) {
                    echo "Abonos";
                    $totalabonos+=$obj->total;
                }else{
                    echo $obj->tipo;
                    if($obj->tipo=="Credito"){
                        $totcredito+=$obj->total;
                    }else{
                        $conbranza+=$obj->total;
                    }

                }
                ?></td>

            <td><?php echo $obj->nombre; ?></td>
            <td><?php echo $obj->id_usuario; ?></td>
            <td><?php  echo $obj->fecha; ?></td>
            <td>$<?php
                if ($obj->abono==0 && $obj->tipo=="Credito"){

                }else{
                 $total+=$obj->total;
                }
                echo number_format($obj->total, 2); ?>
            </td>
            <td><?php
                if ($obj->abono==0 && ($obj->tipo=="Credito"||$obj->tipo=="credito")){
                   echo  "NO";

                }else{
                  echo   "SI";

                }
             ?>
            </td>
        </tr>
    <?php }

    $querydesc= Doctrine_Query::create()
        ->select("sum(montoabono) as montoabono")
        ->from("Database_Model_Deudores")
        ->where("DATE(fecha_registro) >= '$from'")
        ->andWhere("DATE(fecha_registro) <= '$to'")
        ;
    if( $this->usu!="mariely"&&$this->tipousu!=2){
        $objuss = Doctrine_Core::getTable("Database_Model_Usuario")  ->findOneBy("id_usuario", $this->usu);
        $querydesc->andWhere("id_tienda=?",$objuss->id_tienda);
    }

    ?>
    <tr>

        <td></td>
        <td></td>
        <td></td>

        <td><strong>Totales en Caja</strong></td>
        <td>$ <?php echo number_format($total, 2); ?></td>
        <td></td>
    </tr>
</table>
<br>
<table style="width: 100%" border="0">
    <tr>

            <?php
            $cantexento = 0;
            $cantexento1=0;
            $totalexentos=0;
            $cantiva = 0;
            $totaliva=0;
            $listaM = array(); $contM=0;
            $listaH = array(); $contH=0;
            $listaB = array(); $contB=0;
            $listaE = array(); $contE=0;
            $listaB1 = array(); $contB1=0;
            $listaB2 = array(); $contB2=0;
            $listaP = array(); $contP=0;
            $totalexentos1=0;
            foreach ($this->query2 as $obj2):

                $objfol = Doctrine_Core::getTable("Database_Model_Venta")->findOneBy("id_venta", $obj2->id_venta);
                switch ($objfol->id_tienda) {
                    case "1":
                        $listaM[$contM]=$objfol->folio;
                        $contM++;
                        break;
                    case "2":
                        $listaH[$contH]=$objfol->folio;
                        $contH++;
                        break;
                    case "3":
                        $listaB[$contB]=$objfol->folio;
                        $contB++;
                        break;
                    case "5":
                        $listaE[$contE]=$objfol->folio;
                        $contE++;
                        break;
                    case "6":
                        $listaB1[$contB1]=$objfol->folio;
                        $contB1++;
                        break;
                    case "7":
                        $listaB2[$contB2]=$objfol->folio;
                        $contB2++;
                        break;
                    case "8":
                        $listaP[$contP]=$objfol->folio;
                        $contP++;
                        break;
                }

                ///sacar impuestos
                $objdescuentos = Doctrine_Core::getTable("Database_Model_Descuentos")  ->findOneBy("id_venta", $obj2->id_venta);
                if($objdescuentos->porcentajedesc>0){//si tenemos descuento

                    if($obj2->exento_iva>0){

                        $totalexentos1+=$obj2->total;
                        $cantexento1+=$obj2->cantidad;
                        if($obj2->exento_ieps==0){
                            $cantexento+=$obj2->cantidad;

                            //
                            if($obj2->id_tienda=="6"||$obj2->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                                $totalexentos+=(($obj2->total))*0.08;
                            }else{
                               // $totalexentos+=(($obj2->total)/1.08)*0.08;
                                $totalexentos+=(($obj2->total-($obj2->total*$objdescuentos->porcentajedesc/100))/1.08)*0.08;
                            }

                        }
                    }else{
                        $cantiva+=$obj2->cantidad;

                       //

                        if($obj2->id_tienda=="6"||$obj2->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                            $totaliva+=(($obj2->total))*0.16;
                        }else{
                            //$totaliva+=(($obj2->total)/1.16)*0.16;
                            $totaliva+=(($obj2->total-($obj2->total*$objdescuentos->porcentajedesc/100))/1.16)*0.16;
                        }
                    }

                }else{
                    if($obj2->exento_iva>0){
                            $totalexentos1+=$obj2->total;
                        $cantexento1+=$obj2->cantidad;
                        if($obj2->exento_ieps==0){
                            $cantexento+=$obj2->cantidad;
                            if($obj2->id_tienda=="6"||$obj2->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                                $totalexentos+=(($obj2->total)/1.08)*0.08;
                            }else{
                                $totalexentos+=(($obj2->total)/1.08)*0.08;
                            }

                        }
                    }else{
                        $cantiva+=$obj2->cantidad;

                        if($obj2->id_tienda=="6"||$obj2->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                            $totaliva+=(($obj2->total)/1.16)*0.16;
                        }else{
                            $totaliva+=(($obj2->total)/1.16)*0.16;
                        }
                    }
                }


            endforeach; ?>
        <td align="center">
            <table>
                <tr>
                    <td colspan="2"><h4>Total ingresado</h4></td>
                </tr>
                <tr>
                    <td>Total</td><td>$ <?php

                        echo number_format($conbranza+$totalabonos, 2); ?></td>
                </tr>
                <tr>
                    <td>Venta a Credito</td><td>$ <?php

                        echo number_format($totcredito, 2); ?></td>
                </tr>
                <tr>
                    <td>Descuentos</td><td style="color: red">$ <?php echo number_format($desctt, 2); ?></td>
                </tr>

                <tr>
                    <td>Total + Vta Cred.</td><td style="color: blue">$ <?php echo number_format($conbranza+$totalabonos+$totcredito, 2); ?></td>
                </tr>
            </table>
            <br>
            <table>
                <tr>
                    <td>Cobranza</td><td>$ <?php

                        echo number_format($totalabonos, 2); ?></td>
                </tr>
            </table>
            <br>
            <table>
                <tr>
                    <td>Devoluciones</td><td style="color: red">$ <?php echo number_format($devoluciones, 2); ?></td>
                </tr>
            </table>
        </td>
        <td align="center">
            <table>
                <tr>
                    <td colspan="3"><h4>Ventas por tasa</h4></td>
                </tr>
                <tr>
                    <td><?php echo $cantexento1; ?></td>  <td>EXENTO</td><td>$ <?php echo number_format($totalexentos1, 2); ?></td>
                </tr>
                <tr>
                    <td><?php echo $cantiva; ?></td>  <td>IVA AL 16%</td><td>$ <?php echo number_format(($totaliva), 2); ?></td>
                </tr>
                <tr>
                    <td><?php echo $cantexento; ?></td>  <td>IEPS 8%</td><td>$ <?php echo number_format($totalexentos, 2); ?></td>
                </tr>
            </table>
        </td>
        <td align="center">
            <table>
                <tr>
                    <td colspan="2"><h4>Rango de Folios</h4></td>
                </tr>
                <?php
                if(count($listaM)!=0){
                    ?>
                    <tr>
                        <td>Montes Urales</td> <td> <?php
                            echo $listaM[0]."-".$listaM[count($listaM)-1]; ?></td>
                    </tr>
                <?php
                }
                if(count($listaH)!=0){?>
                    <tr>
                        <td>Hacienda</td> <td> <?php
                            echo $listaH[0]."-".$listaH[count($listaH)-1]; ?></td>
                    </tr>

                <?php
                }
                if(count($listaB)!=0){?>
                    <tr>
                        <td>Bosques</td> <td> <?php
                            echo $listaB[0]."-".$listaB[count($listaB)-1]; ?></td>
                    </tr>
                <?php
                }
                if(count($listaE)!=0){?>
                    <tr>
                        <td>Expo</td> <td> <?php
                            echo $listaE[0]."-".$listaE[count($listaE)-1]; ?></td>
                    </tr>
                <?php
                }
                if(count($listaB1)!=0){?>
                    <tr>
                        <td>BODEGA1</td> <td> <?php
                            echo $listaB1[0]."-".$listaB1[count($listaB1)-1]; ?></td>
                    </tr>
                <?php
                }
                if(count($listaB2)!=0){?>
                    <tr>
                        <td>BODEGA2</td> <td> <?php
                            echo $listaB2[0]."-".$listaB2[count($listaB2)-1]; ?></td>
                    </tr>
                <?php
                }
                if(count($listaP)!=0){?>
                    <tr>
                        <td>Polanco</td> <td> <?php
                            echo $listaP[0]."-".$listaP[count($listaP)-1]; ?></td>
                    </tr>
                <?php
                }?>

            </table>
            <br>
            <table>
                <tr>
                    <td colspan="2"><strong>Folios de Devoluciones Completas</strong></td>
                </tr>
                <?php
                if($listaMd!=""){
                    ?>
                    <tr>
                        <td>Montes Urales</td> <td> <?php
                            echo $listaMd; ?></td>
                    </tr>
                <?php
                }
                if($listaHd!=""){   ?>
                    <tr>
                        <td>Hacienda</td> <td> <?php
                            echo $listaHd; ?></td>
                    </tr>

                <?php
                }
                if($listaBd!=""){?>
                    <tr>
                        <td>Bosques</td> <td> <?php
                            echo $listaBd; ?></td>
                    </tr>
                <?php
                }
                if($listaEd!=""){?>
                    <tr>
                        <td>Expo</td> <td> <?php
                            echo $listaEd; ?></td>
                    </tr>
                <?php
                }
                if($listaB1d!=""){?>
                    <tr>
                        <td>BODEGA1</td> <td> <?php
                            echo $listaB1d; ?></td>
                    </tr>
                <?php
                }
                if($listaB2d!=""){?>
                    <tr>
                        <td>BODEGA2</td> <td> <?php
                            echo $listaB2d; ?></td>
                    </tr>
                <?php
                }
                if($listaPd!=""){?>
                    <tr>
                        <td>Polanco</td> <td> <?php
                            echo $listaPd; ?></td>
                    </tr>
                <?php
                }?>

            </table>
            <br>
            <table>
                <tr>
                    <td colspan="2"><strong>Folios de Devoluciones por Producto</strong></td>
                </tr>
                <?php
                if($listaMdp!=""){
                    ?>
                    <tr>
                        <td>Montes Urales</td> <td> <?php
                            echo $listaMdp; ?></td>
                    </tr>
                <?php
                }
                if($listaHdp!=""){   ?>
                    <tr>
                        <td>Hacienda</td> <td> <?php
                            echo $listaHdp; ?></td>
                    </tr>

                <?php
                }
                if($listaBdp!=""){?>
                    <tr>
                        <td>Bosques</td> <td> <?php
                            echo $listaBdp; ?></td>
                    </tr>
                <?php
                }
                if($listaEdp!=""){?>
                    <tr>
                        <td>Expo</td> <td> <?php
                            echo $listaEdp; ?></td>
                    </tr>
                <?php
                }
                if($listaB1dp!=""){?>
                    <tr>
                        <td>BODEGA1</td> <td> <?php
                            echo $listaB1dp; ?></td>
                    </tr>
                <?php
                }
                if($listaB2dp!=""){?>
                    <tr>
                        <td>BODEGA2</td> <td> <?php
                            echo $listaB2dp; ?></td>
                    </tr>
                <?php
                }
                if($listaPdp!=""){?>
                    <tr>
                        <td>Polanco</td> <td> <?php
                            echo $listaPdp; ?></td>
                    </tr>
                <?php
                }?>

            </table>
        </td>
    </tr>
</table>











