<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Ventas a Credito</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th></th>
        <th>No Folio</th>

        <th>Cliente</th>
        <th>Vendedor</th>
        <th>Fecha</th>
        <th>Tipo</th>
        <th>Tienda</th>
        <th>Total</th>
        <th>Comentarios</th>
        <?php if($this->credito){?>
            <th></th>

        <?php  }?>

    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    $totdesc=0;
    $totalcancel=0;
    $totalsincom=0;
    $mayoreo=0;
    foreach ($this->query as $obj):
        $querydesc= Doctrine_Query::create()
            ->from("Database_Model_Descuentos")
            ->where("id_venta=?",$obj->id_venta)
            ->execute();
        $msj="";

        foreach ($querydesc as $objdesc):
            $totdesc+=$objdesc->montodesc;
            $msj.="<tr><td></td><td></td><td></td><td></td><td></td><td></td>

                <td>
                     $-".$objdesc->montodesc."
                </td>
                <td>
                     ".$objdesc->descripciondesc."
                </td>
                <td></td>
              </tr>";

        endforeach;
        $querycancel= Doctrine_Query::create()
            ->from("Database_Model_VentaProductocancelado vpc, vpc.ProductosVenta pv")
            ->where("pv.id_venta=?",$obj->id_venta)
            ->execute();
        $msj2="";

        foreach ($querycancel as $objdesc2):
            $totalcancel+=$objdesc2->total;
            $msj2.="<tr><td></td><td></td><td></td><td></td><td></td><td></td>

                <td>
                     $-".$objdesc2->total."
                </td>
                <td>
                     <label style='color:red'>Cancelado:".$objdesc2->observaciones."</label>
                </td>
                <td></td>
              </tr>";

        endforeach;
        $querysincom= Doctrine_Query::create()
            ->from("Database_Model_ProductosVenta pv")
            ->where("pv.id_venta=?",$obj->id_venta)
            ->execute();
        $msj2="";


        foreach ($querysincom as $objSINC):
            if($objSINC->ProductoTienda->Producto->id_producto==1328) {//RECARGAS
                $totalsincom += $objSINC->total;
            }

        endforeach;
        ?>
        <tr <?php  if ($obj->cancelado) {
            echo "class='cancelada'";
        }?> >

            <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/" . $obj->id_venta); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->folio; ?></td>
            <td><?php
                echo  $obj->Persona->nombre; ?></td>
            <td><?php echo $obj->id_usuario; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td><?php echo $obj->tipo."<br>";
                if($obj->icredito){
                    echo "<span style='color:red'>En pago</span>";

                }
                ?></td>

            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td>$<?php if (!$obj->cancelado) {
                $total += $obj->total;
            } echo number_format($obj->total, 2); ?></td>
            <td><?php echo $obj->comentarios; ?></td>
            <?php if($this->credito){?>
                <td>

                    <?php if (!$obj->cancelado): ?>
                        <a title="Ver Abonos" href="<?php echo $this->baseUrl("deudores/administrar/ver/id/" . $obj->id_venta); ?>">
                            <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a>
                        <a  title="Agregar nuevo Abono" href="<?php echo $this->baseUrl("deudores/administrar/alta/id/" . $obj->id_venta); ?>">
                            <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
                        </a>
                        <a title="Cancelar venta" tooltip="true" delete="true"
                           href="<?php echo $this->baseUrl("ventas/administrar/cancelar/id/" . $obj->id_venta); ?>">
                            <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
                    <?php endif; ?>
                </td>

            <?php  }?>


        </tr>

        <?php echo $msj.$msj2;
    endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>Venta:<br>RECARGAS<br>Venta sin Recargas </strong></td>
        <td><strong>$<?php  echo number_format($total-$totalcancel, 2); ?><br>
                $<?php  echo number_format($totalsincom, 2) ?>
            <br>
                $<?php echo number_format(($total-$totalcancel-$totalsincom), 2); ?>
            </strong>
        </td>
        <td></td>
        <td></td>
    </tr>

</table>
<br>

<h3 class="tit">Comisiones de Ventas</h3>
<table width="100%">
    <tr>
        <th>Usuario</th>
        <th>Total Para Bono</th>
        <th>Abonos</th>
        <th>Recargas</th>
        <th>Total Venta</th>
        <th>Por Cobrar</th>
        <th>Total General</th>
        <th>Comision</th>
    </tr>
    <?php

    $totalComision = 0;
    $totalt=0;
    $totaltvta=0;
    $totalabonos=0;
    $totalporpagar=0;
    $totalrecargas=0;
    $totalgeneral=0;

    $mayoreo=0;
    foreach ($this->querycomisiones as $obj):
        $totalrec= 0;
        $totalab=0;
        $querycomi = Doctrine_Query::create()
            ->select("sum(pv.total) as total, v.id_usuario id_usuario")
            ->from("Database_Model_ProductosVenta pv, pv.Venta v,pv.ProductoTienda pt")
            ->where("DATE(v.fecha) >= '$this->from'")
            ->andWhere("DATE(v.fecha) <= '$this->to'")
            ->andWhere("pt.id_producto!=1328")//recargas
            ->andWhere("v.cancelado=0")
            ->andWhere("v.tipo='Credito'")
            ->andWhere("v.id_usuario=?",$obj->id_usuario)
            ->andWhere("v.icredito=0")
            ->groupBy("v.id_usuario")
        ->fetchOne();
        $querymayo= Doctrine_Query::create()
            ->from("Database_Model_ProductosVenta pv, pv.Venta v,pv.ProductoTienda pt")
            ->where("DATE(v.fecha) >= '$this->from'")
            ->andWhere("v.tipo='Credito'")
            ->andWhere("DATE(v.fecha) <= '$this->to'")
            ->andWhere("v.id_usuario=?",$obj->id_usuario)
            ->execute();
        $msj2="";


        foreach ($querymayo as $objSINC):
            if($objSINC->tipoprecio=='Mayoreo'){
                $mayoreo += ($objSINC->total)/2;
            }
        endforeach;
        $queryabono = Doctrine_Query::create()
            ->select("sum(v.montoabono) as total")
            ->from("Database_Model_Deudores v")
            ->where("DATE(v.fecha_abono) >= '$this->from'")
            ->andWhere("DATE(v.fecha_abono) <= '$this->to'")
            ->andWhere("v.id_usuario=?",$obj->id_usuario)
            ->fetchOne();
        $queryrecag = Doctrine_Query::create()
            ->select("sum(pv.total) as total")
            ->from("Database_Model_ProductosVenta pv, pv.Venta v,pv.ProductoTienda pt")
            ->where("DATE(v.fecha) >= '$this->from'")
            ->andWhere("DATE(v.fecha) <= '$this->to'")
            ->andWhere("pt.id_producto=1328")//recargas
            ->andWhere("v.cancelado=0")
            ->andWhere("v.tipo='Credito'")
            ->andWhere("v.id_usuario=?",$obj->id_usuario)
            ->andWhere("v.icredito=0")
            ->groupBy("v.id_usuario")
            ->fetchOne();
        if($queryabono){
            $totalab= $queryabono->total;
            $totalabonos+=$queryabono->total;
        }
        if($queryrecag){
            $totalrec= $queryrecag->total;
            $totalrecargas+=$queryrecag->total;
        }
        ?>
        <tr>


            <td><?php echo $obj->id_usuario; ?></td>
            <td title="total de ventas menos la mitad de ventas a mayoreo"><?php
                $tott=$querycomi->total-$mayoreo;

                $totalt+=$tott;
                echo  $querycomi->total."-".$mayoreo."=".($querycomi->total-$mayoreo); ?></td>
            <td><?php  echo  $totalab; ?></td>
            <td><?php  echo  $totalrec; ?></td>
            <td><?php $totaltvta+=($tott+$totalab+$totalrec);
                echo $totalv=($tott+$totalab+$totalrec); ?></td>
            <td style="color: red"><?php $totalporpagar+=$obj->total-$totalv-$mayoreo;
                echo $totalpp=$obj->total-$totalv-$mayoreo; ?></td>
            <td style="color: blue"><?php $totalgeneral+=$totalpp+$totalv+$mayoreo;
                echo $totalgen=$totalpp+$totalv+$mayoreo; ?></td>
            <td style="color: green"><?php
                $totalComision+=$tott*0.06;
                echo $tott*0.06; ?></td>

        </tr>
    <?php endforeach; ?>
    <tr>

        <td></td>
        <td><strong>$<?php echo number_format($totalt, 2); ?></strong></td>
        <td><strong>$<?php echo number_format($totalabonos, 2); ?></strong></td>
        <td><strong>$<?php echo number_format($totalrecargas, 2); ?></strong></td>
        <td><strong>$<?php echo number_format($totaltvta, 2); ?></strong></td>
        <td style="color: red"><strong>$<?php echo number_format($totalporpagar, 2); ?></strong></td>
        <td style="color: blue"><strong>$<?php echo number_format($totalgeneral, 2); ?></strong></td>
        <td style="color: green"><strong>$<?php echo number_format($totalComision, 2); ?></strong></td>
    </tr>

</table>