<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Descuentos de Ventas</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th></th>
        <th>Folio</th>
        <th>Vendedor</th>
        <th>Cliente</th>
        <th>Fecha Descuento</th>
        <th>Descuento</th>
        <th>Total - Descuento</th>
        <th>Total Venta</th>
       
    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    $desc=0;
    $totaldescuen=0;
    foreach ($this->query as $obj): ?>
        <tr <?php  if ($obj->Venta->cancelado) {
            echo "class='cancelada'";
        }?>
            >

            <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/" . $obj->Venta->id_venta); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->Venta->folio; ?></td>
            <td><?php echo $obj->id_usuario; ?></td>
            <td><?php echo $obj->Venta->Persona->nombre; ?></td>
            <td><?php echo $obj->fecha_registro; ?></td>
            <td><?php $desc+=$obj->montodesc; echo number_format($obj->montodesc,2); ?></td>
            <td><?php  $total+=$obj->Venta->total; echo number_format($obj->Venta->total,2); ?></td>
            <td><?php $totaldescuen+=$obj->totaldesc; echo number_format($obj->totaldesc,2); ?></td>




        </tr>
        <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>$<?php echo $desc;?></td>
        <td>$<?php echo $total;?></td>
        <td>$<?php echo $totaldescuen;?></td>
    </tr>

</table>