<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes de contabilidad</h1>
<h3 class="tit">Producto Ventas</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th>No Folio</th>
        <th>Cant.</th>

        <th>Codigo</th>

        <th>Nombre</th>
        <th>Marca</th>
        <th>Vendedor</th>
        <th>Tipo</th>
        <th>Precio Unit.</th>
        <th>Total</th>
        <th>Tipo</th>
        <th>Proveedor</th>
        <th>Fecha</th>

    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    $totdesc=0;

    foreach ($this->query as $obj2){
        $querydesc= Doctrine_Query::create()
            ->from("Database_Model_Descuentos")
            ->where("id_venta=?",$obj2->id_venta)
            ->execute();
        $msj="";
        foreach ($querydesc as $objdesc):
            if(!$obj2->cancelado) {
                $totdesc += $objdesc->montodesc;
            }
                $class="";
                if ($obj2->cancelado) {
                    $class= "class='cancelada'";
                }
                $msj .= "<tr $class>
                <td></td><td></td><td></td><td></td><td></td><td></td>
                <td>Folio:" . $objdesc->Venta->folio . "</td>
                <td>
                     " . $objdesc->descripciondesc . "
                </td>
                <td>
                     $-" . $objdesc->montodesc . "
                </td>
                <td></td> <td></td>
                <td></td>
              </tr>";

        endforeach;
        $queryprod= Doctrine_Query::create()
            ->from("Database_Model_ProductosVenta pv, pv.ProductoTienda pt,pt.Producto p")
            ->where("id_venta=?",$obj2->id_venta)
            ->andwhere("p.manual=0") //quita todo lo de shelo y chantal
            ->andwhere("p.id_proveedor!=2") //quita todo lo de shelo y chantal
            ->andwhere("p.id_proveedor!=5") //quita todo lo de shelo y chantal
            ->execute();
        foreach ($queryprod as $obj) {
            if( $obj->ProductoTienda->Producto->id_proveedor==2||$obj->ProductoTienda->Producto->id_proveedor==5||$obj->ProductoTienda->Producto->id_proveedor==9){
//proveedores que no se cuentan
            }else {
                ?>
                <tr <?php  if ($obj->Venta->cancelado || $obj->cancelado) {
                    echo "class='cancelada'";
                }?> >
                    <td><?php echo $obj->Venta->folio; ?></td>
                    <td><?php echo $obj->cantidad; ?></td>
                    <td><?php echo $obj->ProductoTienda->Producto->codinter; ?></td>
                    <td><?php echo $obj->nombre; ?></td>
                    <td><?php echo $obj->ProductoTienda->Producto->Marca->nombre; ?></td>
                    <td><?php echo $obj->Venta->id_usuario; ?></td>
                    <td><?php echo $obj->Venta->tipo; ?></td>
                    <td><?php echo $obj->total / $obj->cantidad; ?></td>
                    <td>$<?php if ($obj->cancelado == 0 && $obj2->cancelado == 0) {
                            if (!$obj->Venta->icredito) { //si la venta no esta en estado de credito y adeuda
                                $total += $obj->total;
                            }

                        }
                        echo number_format($obj->total, 2); ?></td>
                    <td><?php echo $obj->Venta->tipo;
                        if ($obj->Venta->icredito) { //si la venta no esta en estado de credito y adeuda
                            echo "<BR><label STYLE='color:red'>EN LIQUIDACION</label>";
                        }
                        ?></td>
                    <td><?php echo $obj->ProductoTienda->Producto->Proveedor->nombre_corto; ?></td>
                    <td><?php echo $obj->Venta->fecha; ?></td>
                </tr>
            <?php
            }
        }
        echo $msj;
    }
     ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><strong>Subtotal:<br>Descuentos<br>Venta total</strong></td>
        <td><strong>$<?php  echo number_format($total, 2); ?> <br>
                $<?php  echo "-".number_format($totdesc, 2); ?> <br>
                $<?php  echo number_format($total-$totdesc, 2); ?>      </strong>
        </td><td></td><td></td>
        <td></td>
    </tr>

</table>
<br>
