<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Devoluciones de Ventas</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th></th>
        <th>No Folio</th>
        <th>Vendedor</th>
        <th>Fecha Venta</th>
        <th>Fecha Cancelacion</th>
        <th>Tipo</th>
        <th>Tienda</th>
        <th>Total</th>

    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj):
        $objv = Doctrine_Core::getTable("Database_Model_Venta")->findOneBy("id_venta", $obj->id_venta);

        ?>
        <tr <?php  if ($obj->Venta->cancelado) {
            echo "class=''";
        }?>
            >

            <td><a href="<?php echo $this->baseUrl("ventas/administrar/verdevolucion/id/" . $obj->id_venta); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->Venta->folio; ?></td>
            <td><?php echo $obj->id_usuario; ?></td>
            <td><?php echo $obj->Venta->fecha; ?></td>
            <td><?php

                echo $obj->fecha_registro; ?></td>
            <td><?php echo $obj->Venta->tipo; ?></td>

            <td><?php echo $obj->Venta->Tienda->nombre; ?></td>
            <td>$<?php
                $total += $objv->total;
                if (!$obj->Venta->cancelado) {

            } echo number_format($objv->total, 2); ?></td>

        </tr>
        <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td><td></td>
        <td></td>
        <td>$ <?php echo number_format($total, 2); ?></td>
    </tr>
</table>