<h1>Reportes</h1>
<h3 class="tit">Historial Actualizaciones</h3>

<?php echo $this->form; ?>
<?php
$querytipo = Doctrine_Query::create()
    ->from("Database_Model_Producto")
    ->where("status='ACTIVO'")
    ->execute();
$prod="";
foreach($querytipo as $tipo){
    $prod=$prod.",'".$tipo->id_producto."::".$tipo->nombre."'";
}

$cadena = substr($prod,1);
//echo $cadena;
?>
<script>
    $( "#autocomplete" ).autocomplete({
        source: [ <?php echo $cadena ?>]
    });
</script>

<h3 class="tit">Reporte generado</h3>
<div style="overflow:auto">
    <table cellspacing="0" class="full-width" id="example" style="overflow:auto">
        <thead>
        <tr> 
            <th>Sucursal</th>
            <th>Exist Ant.</th>
            <th>Exist.</th>
            <th>ID</th>
            <th>Cod. Interno</th>
            <th>Producto</th>
            <th>Marca</th>
            <th>Tienda</th>
            <th>Usuario</th>
            <th>Fecha</th>
        </tr>
        </thead>
        <tbody>
            <?php
            $total = 0;
            $totalComision = 0;
            $totalUtilidad = 0;
            $totalCosto = 0;
            foreach ($this->query as $obj): ?>
                <tr >
                    <td><?php echo $obj->ProductoTienda->Producto->Proveedor->nombre_corto; ?></td>
                    <td><?php echo $obj->existencia_anterior; ?></td>
                    <td><?php echo $obj->existencia; ?></td>
                    <td><?php echo $obj->ProductoTienda->Producto->id_producto; ?></td>
                    <td><?php echo $obj->ProductoTienda->Producto->codinter; ?></td>
                    <td><?php echo $obj->ProductoTienda->Producto->nombre; ?></td>

                    <td><?php echo $obj->ProductoTienda->Producto->Marca->nombre; ?></td>
                    <td><?php echo $obj->ProductoTienda->Tienda->nombre; ?></td>
                
                    <td><?php echo $obj->id_usuario; ?></td>
                    <td><?php echo $obj->fecha_registro; ?></td>
                </tr>
            <?php endforeach; ?>

        </tbody>
    </table>
</div>
<script>
    $(function() {

        var table =	$('#example').dataTable( {
            "bJQueryUI": true,
           
            "aaSorting": [[9, "asc"]],
            "scrollX": true,
            "iDisplayLength": 50,
            "bPaginate": true,
            "bAutoWidth": true,
            "sPaginationType": "full_numbers",
            "bSort": true,
            "aLengthMenu": [[5, 10, 15, 25, 50, -1], [5, 10, 15, 25, 50, "All"]]
        } );

    });
</script>