<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Cremas</title>

    <script type="text/javascript">
        window.print();
    </script>

    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 11px;
        }
    </style>
</head>
<body style="text-align: center; width: 175px;">
<table width="1000" border="0">
    <tr colspan="3" align="left">
        <td width="807">Cremas Devolucion  por Productos</td>
        <td width="0"></td>
    </tr>
    <tr>
        <td colspan="3" align="left"><label style="font-size:14px">Mexico D.F. a &nbsp;<?php echo $this->obj->fecha; ?> </label></td>
        <td width="177"><label style="font-size:14px">Folio:<label style="color:#F00"> No.&nbsp; <?php echo $this->obj->id_entrada; ?></label></label></td>
    </tr>
    <tr colspan="3" align="left">
        <td><label style="font-size:14px">Referencia:<label style="color:#120000"> No.&nbsp; <?php echo $this->obj->referencia; ?></label></label></td>
        <td width="0"></td>
    </tr>
    <tr>
        <td colspan="4" align="left"><label style="font-size:14px">Concepto &nbsp;<?php echo $this->obj->concepto; ?> </label></td>
    </tr>
    <tr>
        <td colspan="4" align="left"><label style="font-size:14px">Vendedor &nbsp;<?php echo $this->obj->Usuario->nombre; ?> </label></td>
    </tr>
</table>

<h3>Artículos</h3>

<table  width="1000">
    <tr>

        <th>No Folio Venta</th>
        <th>Vendedor</th>
        <th>Fecha Devolucion</th>
        <th>Cantidad</th>
        <th>Codigo Interno</th>
        <th>Producto</th>

        <th>Total</th>
    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj): ?>
        <tr <?php  if ($obj->ProductosVenta->cancelado) {
            echo "class=''";
        }?>
            >
            <td><?php echo $obj->ProductosVenta->folio; ?></td>
            <td><?php echo $obj->Usuario->nombre; ?></td>
            <td><?php echo $obj->fecha_registro; ?></td>
            <td><?php echo $obj->ProductosVenta->cantidad; ?></td>
            <td><?php echo $obj->ProductosVenta->ProductoTienda->Producto->codinter; ?></td>
            <td><?php echo $obj->ProductosVenta->nombre; ?></td>
            <td>$<?php if (!$obj->ProductosVenta->cancelado) {
                    $total += $obj->ProductosVenta->total;
                } echo number_format($obj->ProductosVenta->total, 2); ?></td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td>$ <?php echo number_format($total, 2); ?></td>
    </tr>

</table>


<p>

</p>
</body>
</html>


