<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Cremas</title>

    <script type="text/javascript">
        window.print();
    </script>

    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 11px;
        }
    </style>
</head>

<table width="100%">
    <tr>
        <td align="left"> <img width="80" height="60" src="<?php echo $this->baseUrl("images/logo.jpg"); ?>"/></td>
        <td style="align:right">Tienda:<?php echo $this->tienda; ?></td>
        <td style="align:right">Fecha:<?php echo date("Y-m-d H:i:s") ?></td>
    </tr>

</table>

<br>

<h1>Detalle de Corte de Ventas</h1>

<style type="text/css">}
    .cancelada {
        opacity: .5;
    }
</style>
<br>


<h3 class="tit">Artículos</h3>
<table width="100%">
    <tr>
        <th>Folio Venta </th>
        <th>Cantidad</th>
        <th>Cod inter</th>
        <th>Nombre</th>
        <th>Exento IVA</th>
        <th>Exento IEPS</th>
        <th>Total</th>
        <th>Tipo</th>
        <th>Tienda</th>
        <th>Usuario</th>
        <th>Fecha</th>
    </tr>
    <?php
    $total2 = 0;
    $costo = 0;
    $totalComision = 0;
    $totalexentos=0;
    $totalexentos1=0;
    $totaliva=0;
    $msj="";
    $desc=0;
    $totalefec=0;
    $totalamex=0;
    $totaltar=0;
    $totalcre=0;
    $totalotros=0;
    $totalefecdesc=0;
    $totaltardesc=0;
    $totalamexdesc=0;
    $totalcredesc=0;
    $totalotrosdesc=0;
    $totalsinimpuestoieps=0;
    $totalsinimpuestoiva=0;
    foreach ($this->querydesc as $objdesc):
        if($iddesc=$objdesc->id_descuentos){
            $desc+=$objdesc->montodesc;
            if($objdesc->Venta->tipo=="Efectivo"){
                $totalefecdesc+=$objdesc->montodesc;
            }
            if($objdesc->Venta->tipo=="Tarjeta"){
                $totaltardesc+=$objdesc->montodesc;
            }
            if($objdesc->Venta->tipo=="AMEX"){
                $totalamexdesc+=$objdesc->montodesc;
            }
            if($objdesc->Venta->tipo=="Credito"){
                $totalcredesc+=$objdesc->montodesc;
            }
            if($objdesc->Venta->tipo=="Otros"){
                $totalotrosdesc+=$objdesc->montodesc;
            }
            $msj.="<tr>
                <td></td><td>Folio:</td>
                <td>
                     ".$objdesc->Venta->folio."
                </td>
                <td>
                     ".$objdesc->descripciondesc."
                </td>
                <td>Monto:</td>
                <td>
                     $-".$objdesc->montodesc."
                </td>
                <td></td>

              </tr>";
        }

    endforeach;
    foreach ($this->query as $obj):  ?>
        <tr  >
            <td><?php
                $objfolio = Doctrine_Core::getTable("Database_Model_Venta")->findOneBy("id_venta", $obj->id_venta);

                echo $objfolio->folio;

                ?></td>

            <td><?php echo $obj->cantidad; ?></td>
            <td><?php echo $obj->codinter; ?></td>
            <td><?php  echo $obj->nombre; ?></td>
            <td><?php
                if($obj->exento_iva>0){
                    echo "SI";
                    //  $totalexentos+=$obj->total;
                }else{
                    echo "NO";
                    //  $totaliva+=$obj->total;
                }
                ///sacar impuestos
                $objdescuentos = Doctrine_Core::getTable("Database_Model_Descuentos")  ->findOneBy("id_venta", $obj->id_venta);
                if($objdescuentos->porcentajedesc>0){//si tenemos descuento
                    if($obj->exento_iva>0){
                        $totalexentos1+=$obj->total;
                        $cantexento+=$obj->cantidad;
                        //
                        if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                            $totalexentos+=(($obj->total))*0.08;
                            $totalsinimpuestoieps+=($obj->total);
                        }else{
                            $totalexentos+=(($obj->total-($obj->total*$objdescuentos->porcentajedesc/100))/1.08)*0.08;
                            //$totalexentos+=(($obj->total)/1.08)*0.08;
                            $totalsinimpuestoieps+=($obj->total)/1.08;
                        }


                    }else{
                        $cantiva+=$obj->cantidad;


                        if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                            $totaliva+=(($obj->total))*0.16;
                            $totalsinimpuestoiva+=($obj->total);
                        }else{
                            $totaliva+=(($obj->total-($obj->total*$objdescuentos->porcentajedesc/100))/1.16)*0.16;
                            //$totaliva+=(($obj->total)/1.16)*0.16;
                            $totalsinimpuestoiva+=($obj->total)/1.16;
                        }


                    }

                }else{
                    if($obj->exento_iva>0){


                        $totalexentos1+=$obj->total;
                        $cantexento+=$obj->cantidad;
                        if($obj->exento_ieps==0){
                            if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                                $totalexentos+=(($obj->total))*0.08;
                                $totalsinimpuestoieps+=($obj->total);
                            }else{
                                $totalexentos+=(($obj->total)/1.08)*0.08;
                                $totalsinimpuestoieps+=($obj->total)/1.08;
                            }

                        }
                    }else{
                        $cantiva+=$obj->cantidad;
                        if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                            $totaliva+=(($obj->total))*0.16;
                            $totalsinimpuestoiva+=($obj->total);
                        }else{
                            $totaliva+=(($obj->total)/1.16)*0.16;
                            $totalsinimpuestoiva+=($obj->total)/1.16;
                        }

                    }
                }
                ?></td>
            <td><?php
                if($obj->exento_iva>0) {
                    if ($obj->exento_ieps > 0) {
                        echo "SI";
                        //  $totalexentos+=$obj->total;
                    } else {
                        echo "NO";
                        //  $totaliva+=$obj->total;
                    }
                }else{
                    echo "SI";
                }
                ?>
            </td>
            <td>$<?php
                if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta

                    $total2+=$obj->total+$totaliva+$totalexentos;
                }else{
                    $total2+=$obj->total;
                }

                echo $obj->total; ?></td>
            <td><?php
                if($obj->tipo=="Efectivo"){
                    if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                        $totalefec+=$obj->total+$totaliva+$totalexentos;
                    }else{
                        $totalefec+=$obj->total;
                    }
                }
                if($obj->tipo=="Tarjeta"){
                    if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                        $totaltar+=$obj->total+$totaliva+$totalexentos;
                    }else{
                        $totaltar+=$obj->total;
                    }
                }
                if($obj->tipo=="AMEX"){
                    if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                        $totalamex+=$obj->total+$totaliva+$totalexentos;
                    }else{
                        $totalamex+=$obj->total;
                    }
                }
                if($obj->tipo=="Credito"){
                    if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                        $totalcre+=$obj->total+$totaliva+$totalexentos;
                    }else{
                        $totalcre+=$obj->total;
                    }
                }
                if($obj->tipo=="Otros"){
                    if($obj->id_tienda=="6"||$obj->id_tienda=="7"){//si son bodegas no se le descuenta el iva sino se le aumenta
                        $totalotros+=$obj->total+$totaliva+$totalexentos;
                    }else{
                        $totalotros+=$obj->total;
                    }
                }
                echo $obj->tipo; ?></td>
            <td><?php  $objtinda = Doctrine_Core::getTable("Database_Model_Tienda")->findOneBy("id_tienda", $obj->id_tienda);
                echo $objtinda->nombre; ?></td>
            <td><?php  echo $obj->id_usuario; ?></td>
            <td><?php  echo $obj->fecha; ?></td>
        </tr>
    <?php endforeach; ?>

    <?php echo $msj; ?>


</table>
<br>
<table width="100%">
    <tr>
        <td style="align:center">
            <table>
                <tr>
                    <td colspan="3"><h4>Ventas Detalles</h4></td>
                </tr>
                <tr>
                    <td>Ventas</td><td>$ <?php echo number_format($total2, 2); ?></td>
                </tr>
                <tr>
                    <td>Descuentos</td><td>$ <?php echo number_format($desc, 2); ?></td>
                </tr>
                <tr>
                    <td>Total</td><td>$ <?php echo number_format($total2-$desc, 2); ?></td>
                </tr>
            </table>
        </td>
        <td style="align:center">
            <table>
                <tr>
                    <td colspan="3"><h4>TOTAL POR TIPO</h4></td>
                </tr>
                <tr>
                    <td>Efectivo</td><td>$ <?php echo number_format($totalefec-$totalefecdesc, 2); ?></td>
                </tr>
                <tr>
                    <td>Tarjeta</td><td>$ <?php echo number_format($totaltar-$totaltardesc, 2); ?></td>
                </tr>
                <tr>
                    <td>AMEX</td><td>$ <?php echo number_format($totalamex-$totalamexdesc, 2); ?></td>
                </tr>
                <tr>
                    <td>Credito</td><td>$ <?php echo number_format($totalcre-$totalcredesc, 2); ?></td>
                </tr>
                <tr>
                    <td>Otros</td><td>$ <?php echo number_format($totalotros-$totalotrosdesc, 2); ?></td>
                </tr>

            </table>
        </td>
        <td style="align:center">
            <table>
                <tr>
                    <td colspan="3"><h4>Impuestos</h4></td>
                </tr>
                <tr>
                    <td>EXENTO</td><td>$ <?php echo number_format($totalexentos1, 2); ?></td>
                </tr>
                <tr>
                    <td>IVA</td><td>$ <?php echo number_format(($totaliva), 2); ?></td>
                </tr>
                <tr>
                    <td>IEPS</td><td>$ <?php echo number_format($totalexentos, 2); ?></td>
                </tr>
            </table>
            <br>
            <table>
                <tr>
                    <td colspan="3"><h4>Totales Antes de Impuestos</h4></td>
                </tr>
                <tr>
                    <td>EXENTO</td><td>$ <?php echo number_format($totalexentos1, 2); ?></td>
                </tr>
                <tr>
                    <td>Sin IVA</td><td>$ <?php echo number_format(($totalsinimpuestoiva), 2); ?></td>
                </tr>
                <tr>
                    <td>Sin IEPS</td><td>$ <?php echo number_format($totalsinimpuestoieps, 2); ?></td>
                </tr>
            </table>
        </td>
    </tr>
</table>