<?php
$querytipo = Doctrine_Query::create()
                     ->from("Database_Model_Persona")
                     ->where("id_usuario_tipo='1'")
                     ->orderBy("nombre asc")
                     ->execute();
$prod="";
foreach($querytipo as $tipo){
     $prod=$prod.",'".$tipo->id_persona."::".$tipo->nombre." ".$tipo->ap_paterno." ".$tipo->ap_materno."'";
}

$cadenacli = substr($prod,1);
//echo $cadena;
?>


<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Ventas por Cliente</h3>
<form method="get" action="">
<dl class="zend_form">
<dt id="from-label"><label for="from" class="required">Desde *</label></dt>
<dd id="from-element">
<input type="text" name="from" id="from" value="<?php echo $this->from; ?>" autocomplete='off' class="small-input datepicker" datepicker="past"></dd>
<dt id="to-label"><label for="to" class="required">Hasta *</label></dt>
<dd id="to-element">
<input type="text" name="to" id="to" value="<?php echo $this->to; ?>"  autocomplete='off' class="small-input datepicker" datepicker="past"></dd>
<dt id="autocomplete-label"><label for="autocomplete" class="required">Nombre del Cliente *</label></dt>
<dd id="autocomplete-element">
    <input type="text" name="autocomplete" id="autocomplete" value="" class="small-input ui-autocomplete-input" for="autocomplete" autocomplete="off" role="textbox" aria-autocomplete="list" aria-haspopup="true">
    <input type="checkbox" onclick="$('.datepicker').val('')">Mostrar todo
</dd>
<dt id="Aceptar-label">&nbsp;</dt><dd id="Aceptar-element">
<input type="submit" name="Aceptar" id="Aceptar" value="Aceptar" class="ui-button ui-widget ui-state-default ui-corner-all" role="button" aria-disabled="false"></dd></dl></form>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th></th>
        <th>No Folio</th>
        <th>Vendedor</th>
        <th>Cliente</th>
        <th>Fecha Venta</th>
        <th>Fecha Cancelacion</th>
        <th>Tipo</th>
        <th>Saldo por Pagar</th>
        <th>Tienda</th>
        <th>Total</th>

    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj):
        $objv = Doctrine_Core::getTable("Database_Model_Venta")->findOneBy("id_venta", $obj->id_venta);

        ?>
        <tr <?php  if ($obj->cancelado) {
            echo "class='cancelada'";
        }?>
            >

            <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/" . $obj->id_venta); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->folio; ?></td>
            <td><?php echo $obj->id_usuario; ?></td>
            <td><?php echo $obj->Persona->nombre." ".$obj->Persona->ap_paterno." ".$obj->Persona->ap_materno; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td><?php echo $obj->tipo; ?></td>
            <td>
                <div style="width: 70%; float:left;"><?php
                $saldoppagar=0;
                if($obj->icredito==1){
                    $querysaldo = Doctrine_Query::create()
                        ->select("SUM(montoabono) AS saldo")
                        ->from("Database_Model_Deudores")
                        ->where("id_venta =?",$obj->id_venta)
                        ->andWhere("status = ?", "ACTIVA")
                        ->execute();
                    foreach($querysaldo as $s){
                        $saldo=$s["saldo"];
                    }
                    $saldoppagar=number_format($obj->total-$saldo,2);
                }

                echo "$".$saldoppagar;

                if($obj->tipo=='Credito'){
                    ?>
                </div>
                <div style="float: left; width: 30%">
                     <a title="Ver Abonos" href="<?php echo $this->baseUrl("deudores/administrar/ver/id/" . $obj->id_venta); ?>">
                     <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a>
                </div>
                    <?php
                }
                ?>

           </td>
            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td>$<?php
                $total += $objv->total;
                if (!$obj->cancelado) {

            } echo number_format($objv->total, 2); ?></td>

        </tr>
        <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td><td></td>
        <td></td>
        <td>$ <?php echo number_format($total, 2); ?></td>
    </tr>
</table>

<script>
    $( "#autocomplete" ).autocomplete({
        source: [ <?php echo TRIM($cadenacli) ?>]
    });
</script>