<?php




$querytipo = Doctrine_Query::create()
                     ->from("Database_Model_Persona")
                     ->where("id_usuario_tipo='1'")
                     ->orderBy("nombre asc")
                     ->execute();
$prod="";
foreach($querytipo as $tipo){
     $prod=$prod.",'".$tipo->id_persona."::".$tipo->nombre." ".$tipo->ap_paterno." ".$tipo->ap_materno."'";
}

$cadenacli = substr($prod,1);
//echo $cadena;
?>


<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<h1>Reportes</h1>
<h3 class="tit">Devoluciones de Ventas</h3>

<?php echo $this->form; ?>

<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th></th>
        <th>No Folio</th>
        <th>Vendedor</th>
        <th>Cliente</th>
        <th>Fecha Venta</th>
        <th>Fecha Cancelacion</th>
        <th>Tipo</th>
        <th>Saldo por Pagar</th>
        <th>Tienda</th>
        <th>Total</th>

    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    foreach ($this->query as $obj):
        $objv = Doctrine_Core::getTable("Database_Model_Venta")->findOneBy("id_venta", $obj->id_venta);

        ?>
        <tr <?php  if ($obj->cancelado) {
            echo "class='cancelada'";
        }?>
            >

            <td><a href="<?php echo $this->baseUrl("ventas/administrar/ver/id/" . $obj->id_venta); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a></td>
            <td><?php echo $obj->folio; ?></td>
            <td><?php echo $obj->id_usuario; ?></td>
            <td><?php echo $obj->Persona->nombre." ".$obj->Persona->ap_paterno." ".$obj->Persona->ap_materno; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td><?php echo $obj->fecha; ?></td>
            <td><?php echo $obj->tipo; ?></td>
            <td>
                <div style="width: 70%; float:left;"><?php
                $querysaldo = Doctrine_Query::create()
                    ->select("SUM(montoabono) AS saldo")
                    ->from("Database_Model_Deudores")
                    ->where("id_venta =?",$obj->id_venta)
                    ->andWhere("status = ?", "ACTIVA")
                    ->execute();
                foreach($querysaldo as $s){
                    $saldo=$s["saldo"];
                }
                echo "$".number_format($obj->total-$saldo,2);
                if($obj->tipo=='Credito'){
                    ?>
                </div>
                <div style="float: left; width: 30%">
                     <a title="Ver Abonos" href="<?php echo $this->baseUrl("deudores/administrar/ver/id/" . $obj->id_venta); ?>">
                     <img src="<?php echo $this->baseUrl("css/img/view.png"); ?>" border="0"/> </a>
                </div>
                    <?php
                }
                ?>

           </td>
            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td>$<?php
                $total += $objv->total;
                if (!$obj->cancelado) {

            } echo number_format($objv->total, 2); ?></td>

        </tr>
        <?php endforeach; ?>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td><td></td>
        <td></td>
        <td>$ <?php echo number_format($total, 2); ?></td>
    </tr>
</table>

<script>
    $( "#autocomplete" ).autocomplete({
        source: [ <?php echo $cadenacli ?>]
    });
</script>