


<h1>Reportes</h1>
<h3 class="tit">Ventas por Producto</h3>


<?php echo $this->form; ?>

<?php
$querytipo = Doctrine_Query::create()
    ->from("Database_Model_Producto")
    //->where("id_tienda=?",$obj->id_tienda)
    ->execute();
$prod="";
foreach($querytipo as $tipo){
     $prod=$prod.",'".$tipo->codinter."::".str_replace("'", "",$tipo->nombre)."'";
}

$cadena = substr($prod,1);
//echo $cadena;
?>
<script>
    $( "#autocomplete" ).autocomplete({
        source: [ <?php echo $cadena ?>]
    });
</script>



<h3 class="tit">Reporte generado</h3>
<table width="100%">
    <tr>
        <th>Cantidad</th>
        <th>Cod. Interno</th>
        <th>Producto</th>
        <th>Tienda</th>
        <th>Total</th>
        <th>Costo</th>
        <th>Utilidad</th>
        <th>Fecha</th>
    </tr>
    <?php
    $total = 0;
    $totalComision = 0;
    $totalUtilidad = 0;
    $totalCosto = 0;
    foreach ($this->query as $obj): ?>
        <tr>

            <td><?php echo $obj->total_cantidad; ?></td>
            <td><?php echo $obj->ProductoTienda->Producto->codinter; ?></td>
            <td><?php echo $obj->ProductoTienda->Producto->nombre; ?></td>
            <td><?php echo $obj->Venta->Tienda->nombre; ?></td>

            <td>$<?php $totalt+= ($obj->total_cantidad * $obj->total_total); $total = ($obj->total_cantidad * $obj->total_total); echo number_format(($obj->total_cantidad * $obj->total_total), 2, ".", ""); ?></td>

            <td>$<?php $totalCosto += ($obj->total_cantidad * $obj->ProductoTienda->Producto->costo); echo number_format(($obj->total_cantidad * $obj->ProductoTienda->Producto->costo), 2, ".", ""); ?></td>
            <td>$<?php $totalUtilidad += $total - ($obj->total_cantidad * $obj->ProductoTienda->Producto->costo); echo number_format($total - ($obj->total_cantidad * $obj->ProductoTienda->Producto->costo), 2, ".", ""); ?></td>
            <td><?php echo $obj->Venta->fecha; ?></td>
        </tr>
        <?php endforeach; ?>
    <tr>

        <td></td>
        <td></td>
        <td></td>

        <td align="right">Total:</td>
        <td>$<?php echo number_format($totalt, 2); ?></td>
        <td>$<?php echo number_format($totalCosto, 2); ?></td>
        <td>$<?php echo number_format($totalUtilidad, 2); ?></td>
        <td></td>
    </tr>
</table>