<h1>Reportes</h1>
<h3 class="tit">Ventas por proveedor</h3>

<?php echo $this->form; ?>
<?php
$querytipo = Doctrine_Query::create()
    ->from("Database_Model_Proveedor")
    //->where("id_usuario_tipo=3")
    ->execute();
$prod="";
foreach($querytipo as $tipo){
    $prod=$prod.",'".$tipo->id_proveedor."::".$tipo->nombre_corto."'";
}

$cadena = substr($prod,1);
//echo $cadena;
?>
<script>
    $( "#autocomplete" ).autocomplete({
        source: [ <?php echo $cadena ?>]
    });
</script>

<h3 class="tit">Reporte generado</h3>
<div style="overflow:auto">
<table cellspacing="0" class="full-width" id="example" style="overflow:auto">
    <thead>
    <tr>
        <th>Tienda</th>
        <th>Prov</th>
        <th>Cant</th>
        <th>Cod. Interno</th>
        <th>Producto</th>
        <th>Marca</th>
        <th>Precio U.</th>
        <th>Total</th>
		 <th>Costo U.</th>
        <th>Costo</th>
        <th>Utilidad</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $total = 0;
    $totalComision = 0;
    $totalUtilidad = 0;
    $totalCosto = 0;
    foreach ($this->query as $obj): ?>
        <tr >
            <td><?php echo $obj->Venta->Tienda->nombre; ?></td>
            <td><?php echo $obj->ProductoTienda->Producto->Proveedor->nombre_corto; ?></td>
            <td><?php echo $obj->total_cantidad; ?></td>
            <td><?php echo $obj->ProductoTienda->Producto->codinter; ?></td>
            <td><?php echo $obj->ProductoTienda->Producto->nombre; ?></td>

            <td><?php echo $obj->ProductoTienda->Producto->Marca->nombre; ?></td>
          
            <td><?php
					$totalunit= ($obj->total_total/$obj->total_cantidad);
                echo number_format($totalunit, 2); ?></td>
            <td><?php
            
				$total=$obj->total_total;
                if(!$obj->Venta->icredito){
                    $totalt += $total;
                }
                echo number_format($total, 2, ".", ""); ?></td>
			<td><?php
			$ejecosto= Doctrine_Query::create()
                    ->from("Database_Model_EntradaProducto a, a.Entrada b")
                    ->where("a.id_producto=?",$obj->ProductoTienda->id_producto)
                    ->andWhere("b.status='ACTIVO'")
                    //  ->andWhere("a.cantvendida<a.cantidad")
                    ->orderBy("id_entrada_producto desc")
                    ->limit(1);

                // echo $ejecosto->getSqlQuery();//imprime la consulta qu ese esta generando

                $costoBase=0;
                foreach($ejecosto->execute() as $excosto){
                    $costoBase=$excosto["costo"];//sacamos el ultimo precio por fecha mientras no se allan vendido
                }
                echo number_format(($costoBase), 2, ".", ""); ?></td>
            <td><?php
                $costot=$obj->total_cantidad * $costoBase;
                $totalCosto += $costot; 
				
				echo number_format(($costot), 2, ".", ""); ?>
				</td>
           
            <td><?php
				$utilidad=$total-($costot);
				$totalUtilidad += $utilidad;
			echo number_format($utilidad, 2, ".", ""); ?>
			</td>
        </tr>
    <?php endforeach; ?>

    </tbody>
    </table>
    <table cellspacing="0" class="full-width" id="">
        <tr>
            <th>Prov</th>
            <th>Cant</th>
            <th>ID prod</th>
            <th>Cod</th>
            <th>Producto</th>

            <th>Tienda</th>

            <th>Precio U.</th>
            <th>Total</th>
            <th>Costo U.</th>
            <th>Costo</th>
            <th>Utilidad</th>
        </tr>
        <?php
        $totaldes=0;
        if($this->idproveedor==1 || $this->idproveedor=="") {
            foreach ($this->querydesc as $objD): ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td>DESCUENTOS APLICADOS</td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>

                    <td>$-<?php $totalUtilidad = $totalUtilidad - ($objD->total_descuentos);
                        echo number_format(($objD->total_descuentos), 2, ".", "");
                        $totaldes += $objD->total_descuentos;

                        ?>
                    </td>

                </tr>
            <?php endforeach;
        }
        $totalexce=0;
        foreach ($this->queryexce as $obj):
            $totalexce+=$obj->total_total;
        endforeach;
        ?>


    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td align="right">Total:</td>
        <td></td>
        <td>$<?php
            $totatgral=$totalt-$totaldes;
            echo number_format($totatgral, 2); ?></td>
		<td></td>
        <td>$<?php echo number_format($totalCosto, 2); ?></td>
		
        <td>$<?php echo number_format($totalUtilidad, 2); ?>
          <?php
           $this->dias=$this->dias+1;
             // $bonos=($totatgral/4000)*100;
           //echo "<br>$-".number_format($bonos,2)." bonos";
            $totalgerente=$this->dias*150;
            $totalvendedor=($this->dias*100);
            echo "<br>$-".number_format($totalgerente,2)." pago sueldos";
            
            $totalcomi=$totatgral*0.06;
            echo "<br>$-".number_format($totalcomi,2)." comisiones";

            $totalgastos=(400+100+150+1000+200); //400 internet, 200 impuestos, 150 contabilidad, 1000 renta, 170 luz, 2000 gastos de surtir
         
            echo "<br><font title='400 internet, 200 impuestos, 150 contabilidad, 1000 renta, 170 luz, 2000 gastos de surtir'>$".number_format($promgastosxdia,2)." gastos generales</font>";
          $totalgralutilidad=number_format($totalUtilidad-$totalgerente-$totalcomi,2);
          echo "<br><strong>$".$totalgralutilidad." Utilidad tienda</strong>";
            ?>
        </td>
    </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td align="right">Total Excedentes:</td>
            <td></td>
            <td>$<?php
                echo number_format($totalexce, 2); ?></td>
            <td></td>
            <td>$<?php
                $totalexcepago=$totalexce*0.4;
                echo number_format($totalexcepago, 2); ?></td>

            <td><?php
                $totalexceutilidad=$totalexce*0.35;
                $totalgralutilidad=$totalgralutilidad+$totalexceutilidad;
                echo "<strong>$".number_format($totalexceutilidad,2)." Utilidad YAC STUDIO al 0.35%</strong>";
                echo "<br><strong>$".number_format($totalgralutilidad,2)." Utilidad General</strong>";
                ?>
            </td>
        </tr>
</table>
</div>
<script>
    $(function() {

        var table =	$('#example').dataTable( {
            "bJQueryUI": true,
           
            "aaSorting": [[1, "desc"]],
            "scrollX": true,
            "iDisplayLength": 50,
            "bPaginate": true,
            "bAutoWidth": true,
            "sPaginationType": "full_numbers",
            "bSort": true,
            "aLengthMenu": [[5, 10, 15, 25, 50, -1], [5, 10, 15, 25, 50, "All"]]
        } );

    });
</script>