<h1>Usuarios</h1>
<p class="t-right">
    <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
    </a>
</p>
<?php echo $this->form; ?>
<table class="full-width">
    <thead>
    <tr>
        <th>ID</th>
        <th>Nombre</th>
        <th>Tipo Usuario</th>
        <th>Sucursal</th>
        <th>Permisos</th>
        <th>Status</th>
        <th width="75">Acciones</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->query as $obj): ?>
    <tr class="main-row">
        <td><?php echo $obj->id_usuario; ?></td>
        <td><?php echo $obj->nombre; ?></td>
        <td><?php echo $obj->UsuarioTipo->usuario_tipo; ?></td>
        <td><?php
            $query = Doctrine_Query::create()
                ->from("Database_Model_Tienda")
                ->where("id_tienda=?",$obj->id_tienda)
                ->execute();//verificamos si es adminisrador
            $tienda="";
            foreach($query as $objt){
                $tienda=$objt->nombre;
            }

            echo $tienda; ?></td>


        <td><?php echo $obj->permisos; ?></td>
        <td><?php echo $obj->status; ?></td>
        <td>
            <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/ver/id/" . $obj->id_usuario); ?>">
                <img src="<?php echo $this->baseUrl("css/img/view.png") ?>" border="0"/>
            </a>
            <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/editar/id/" . $obj->id_usuario); ?>">
                <img src="<?php echo $this->baseUrl("css/img/edit.png") ?>" border="0"/>
            </a>
            <a title="Cancelar" tooltip="true" delete="true"
               href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName(). "/borrar/id/"   . $obj->id_usuario); ?>">
                <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/> </a>
        </td>
    </tr>
    
        <?php endforeach; ?>
    </tbody>
</table>

<div id="tnt_pagination">
    <?php// echo $this->paginator; ?>
</div>