

<h3 class="tit">Datos del cliente</h3>
<form id="buscar-producto-form">
    
   <fieldset>
 <table style="width: 100%"><tr><td>
    <legend>Datos Personales</legend>
    <div class="control-group">
        <label class="control-label">Tipo De Usuario</label>
        <div class="controls">
            <?php echo $this->formSelect("id_usuario_tipo", $this->data["id_usuario_tipo"],
                array("style"=>"width:460px","required" => "required"),
                array("1"=>"Cliente"),
                Database_Model_UsuarioTipo::getAllArrusu($this->tipousu)
            ); ?>
        </div>
    </div>
     <div class="control-group">
         <label class="control-label">Nombre</label>
         <div class="controls">
             <?php echo $this->formText("nom_cli", $this->data["nombre"],
                 array("" => "")
             ); ?>
         </div>
     </div>
    <div class="control-group">
        <label class="control-label">Apellido Paterno</label>
        <div class="controls">
            <?php echo $this->formText("ap_pat", $this->data["ap_paterno"],
                array("" => "")
            ); ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Apellido Materno</label>
        <div class="controls">
            <?php echo $this->formText("ap_mat", $this->data["ap_materno"],
                array("" => "")
            ); ?>
        </div>
    </div>
     <div class="control-group">
        <label class="control-label">Telefono</label>
        <div class="controls">
            <?php echo $this->formText("tel_cli", $this->data["telefono"]
            ); ?>
        </div>
    </div>
    <div class="control-group">
        <label class="control-label">Observaciones</label>
        <div class="controls">
            <?php echo $this->formText("coment_cli", $this->data["observaciones"],
                array()
            ); ?>
        </div>
    </div>


    </td>
   </tr>
</table>
</fieldset>
    <input type="button" onclick="save();" id="buttsub" value="Guardar"/>
</form>
