
<script type="text/javascript">
    $(document).ready(function () {
        calcTotal = function () {
            var totales = $(".totales");
            var total = 0;
            for (var i = 0, len = totales.length; i < len; i++) {
                total = parseFloat(total);
                total += parseFloat($(totales[i]).val());
            }

            $("#total-num").html(total);
            $("#total-global").val(total);
        }

        $(document).keydown(function(event) {
            if (event.ctrlKey==true && (event.which == '106' || event.which == '74')) {
                // alert('thou. shalt. not. PASTE!');
                event.preventDefault();
            }
        });
      
        $("#barcode-form").submit(function (e) {

            e.preventDefault();
              var res =  $('#barcode').val().split("::");
             if(res.length>0){
                $('#barcode').val(res[0].trim());
             }
            $.get(_root + "/ventas/administrar/getproducto", $(this).serialize(),
                function (response) {
                    $("table#productos").append(response);
                    calcTotal();
                });


            $("#cantidad").val(1);
            $("#barcode").val("").focus();
            return false;
        });

        $("#barcode").focus(
            function () {
                $(this).addClass("yellow-bg");
            }).blur(function () {
                $(this).removeClass("yellow-bg");
            });

        $("#barcode").focus();

        $("#solicitar-descuento-gerencial").click(function (e) {
            e.preventDefault();

            $("#descuento-gerencial").toggle();

            return false;
        });

        $("#mandar-solicitud").click(function (e) {
            e.preventDefault();

            var idusu=document.getElementById("id_usuariodesc").value;
            var pass=document.getElementById("passworddesc").value;
            var msj=$("#main-form").serialize()+"&id_usuario="+idusu+"&password="+pass;
            if (idusu==2 ) {
                alert("Selecciona un cliente");
            }else{


                var $monto = parseFloat($("#monto").val());
                if ($monto > 0 ) {
                    $.get(_root + "/ventas/administrar/descuentogerencial", msj, function (response) {
                        $("table#productos").append(response);
                        document.getElementById("passworddesc").value = "";
                        document.getElementById("id_usuariodesc").value = "";
                        document.getElementById("mandar-solicitud").style.display = "none";
                        calcTotal();

                    });
                } else {
                    alert("El monto no es correcto");
                }
            }
            return false;
        });
        $("#cancelar-solicitud").click(function (e) {
            e.preventDefault();
            $("[lineid=descuento-gerencial]").remove();
            calcTotal();
            document.getElementById("mandar-solicitud").style.display ="Inherit";
            return false;
        });

        $("#send").click(function (e) {


            $(".borrar-td").remove();
            $("#ticket-items").val($("#productos").html());

            if ($("#tipo").val() != "") {
                $(this).hide();
                $("#main-form").submit();

            } else {
                $("#tipo").focus();
                alert("Hay que escoger una forma de pago");
            }
        });


        $(".borrar-producto").live('click', function (e) {
            e.preventDefault();

            var id = $(this).attr("lineid");
            $("[lineid=" + id + "]").remove();
            calcTotal();
        });

        $("#pago-recibido").keyup(function (){
            var total = parseFloat($("#total-global").val());
            var pagoRecibido = parseFloat($(this).val());

            $("#cambio").val(pagoRecibido-total);
        });
    });
    function consignacion(){

        $("#consignacion").toggle();
    }
</script>
<?php


$cadena=$_SESSION['CADENA'];
?>

<h1>Ventas</h1>
<h3 class="tit">Nueva venta</h3>

<fieldset>
    <legend>Introducir producto</legend>
    <form id="barcode-form">
        
        <table class="nostyle">
             <tr>
                <td>
                    <label >Sucursal</label>
                </td>
                <td>
                 <input type="hidden" id="tipousu" value="<?php echo $this->tipousu; ?>">
                <?php if($this->tipousu==2 || $this->tipousu==5){?>
                    <div class="control-group" id="tiendaorigen" style="display: ">
                        <div class="controls">
                            <?php echo $this->formSelect("id_tienda",$this->id_tienda,
                                array("style"=>"width:460px","required" => "required","class"=>"selectnvo"),
                                Database_Model_Tienda::getAllT()
                            ); ?>
                        </div>
                    </div>
                <?php  }else{?>

                    <div class="controls">
                        <input type="hidden" id="id_tienda" value="<?php echo $this->id_tienda; ?>">
                    </div>
                <?php  }
                ?>
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    <label>TIPO PRECIO</label>
                </td>
                <td>
                    <select name="tipoprecio" id="tipoprecio" class="selectnvo">
                        <option value="Normal">Normal</option>
                        <option value="Mayoreo">Mayoreo</option>
                        <option value="Promocumple">Promo Cumpleaños</option>
                    </select>
                </td>
                <td>
                </td>
            </tr>
            <tr>
                <td>
                    <label >Código de barras</label>
                </td>
                <td>
                    <input type="text" id="barcode"   for='autocomplete' name="id_producto"/>
                </td>
                <td>
                    <a fancybox="true" class="ui-button ui-widget ui-state-default ui-corner-all" style="height: 30px; width: 80px;" id="catalogo" href="<?php echo $this->baseUrl("ventas/administrar/mostrarcatalogo?id_tienda=".$this->id_tienda); ?>">Catálogo</a>
                </td>
            </tr>

            <tr>
                <td>
                    <label for="cantidad">Cantidad</label>
                </td>
                <td>
                    <input type="text" class="small-field" id="cantidad" name="cantidad" value="1"/>
                </td>

            </tr>

            <tr>
                <td>
                    <input type="submit"   value="Agregar"/>
                </td>
            </tr>
        </table>
    </form>
</fieldset>


<form action="" id="main-form" method="post">
    <label class="control-label">Cliente:</label>
    <div class="controls">
        <?php echo $this->formSelect("id_persona", 2,
            array("style"=>"width: 200px; height: 30px;","required" => "required","class"=>"selectnvo"),

            Database_Model_Persona::getAllArrCli()
        ); ?>
   
        <a fancybox="true" class="ui-button ui-widget ui-state-default ui-corner-all" style="height: 20px; width: 80px;" id="newcli" href="<?php echo $this->baseUrl("ventas/administrar/addpopup"); ?>">Add new</a>
    </div>


    <h3 class="tit">Producto</h3>
    <input type="hidden" name="total-global" id="total-global" value="0"/>

    <input type="hidden" name="ticket_items" id="ticket-items" value="0"/>

    <h3 class="total">Total: $<span id="total-num"></span></h3>
    <table id="productos" class="full-width">
        <tr>
            <th>Cantidad</th>
            <th>Codigo Interno</th>
            <th>Producto</th>
            <th>Subtotal</th>
            <th>Total</th>
            <th class="borrar-td"></th>
        </tr>
    </table>
    <div style="height: 25px;"></div>
    <hr/>

    <table class="nostyle">
        <tr>
            <td><label>Tipo de pago</label></td>
            <td>
                <select name="tipo" class="selectnvo" id="tipo">
                    <option value="Efectivo">Efectivo</option>
                    <option value="Tarjeta Credito">Tarjeta Credito</option>
                    <option value="Tarjeta Debito">Tarjeta Debito</option>
                    <option value="Credito">Credito</option>
                    <option value="Otro">Otro</option>
                </select>
            </td>
        </tr>
         <tr id="contabono" style="display: none">
            <td><label>Monto del Abono</label></td>
            <td>
                <input type="text" class="small-field" id="abono" name="abono" value="0" placeholder=""/>
            </td>
        </tr>
        <tr id="contcredencial" style="display: none">
            <td><label>Numero Identificacion</label></td>
            <td>
                <input type="text" class="small-field" id="credencial" name="credencial" placeholder=""/>
            </td>
        </tr>
        <tr>
            <td><label>Pago recibido</label></td>
            <td>
                <input type="text" class="small-field" id="pago-recibido" placeholder="$0.00"/>
            </td>
        </tr>
        <tr>
            <td><label>Cambio</label></td>
            <td>
                <input type="text" class="small-field" id="cambio" readonly="readonly" placeholder="$0.00"/>
            </td>
        </tr>

        <tr>
            <td><label>Descuento gerencial</label></td>
            <td>
                <a href="#" id="solicitar-descuento-gerencial">Mostrar/esconder solicitud</a>

                <div id="descuento-gerencial" style="display: none;">
                    <table class="nostyle">
                        <tr>
                            <td>
                                <label>Monto en $</label>
                            </td>
                            <td><input type="text" id="monto" class="small-field" name="monto"/></td>
                        </tr>
                        <tr>
                            <td>
                                <label>Usuario</label>
                            </td>
                            <td><input type="text" class="small-field" name="id_usuario" id="id_usuariodesc"/></td>
                        </tr>
                        <tr>
                            <td>
                                <label>Contraseña</label>
                            </td>
                            <td><input type="password" class="small-field" name="password" id="passworddesc"/></td>
                        </tr>
                        <tr>
                            <td><input type="button" id="cancelar-solicitud" class="submit" value="Cancelar"/></td>
                            <td>
                                <input type="button" id="mandar-solicitud" class="submit" value="Solicitar"/>
                            </td>
                        </tr>
                    </table>
                </div>

            </td>
        </tr>
        <tr>
            <td><label>Comentarios Venta</label></td>
            <td>
                <input type="text" class="" id="comentarios" name="comentarios"  placeholder=""/>
            </td>
        </tr>
        <?php if($this->profile()->id_usuario_tipo==2 || $this->profile()->id_usuario_tipo==5){?>
            <tr>
                <td>
                    <label>Fecha Venta</label>
                </td>
                <td><input type="text" class="small-input" datepicker='past' name="fecha" id="" value='<?php echo date('Y-m-d')?>'/></td>


            </tr>
            <tr>
                <td>
                    <label>Vendedor</label>
                </td>
                <td> <?php
                    $arr = array();
                    foreach (Doctrine_Query::create()
                                 ->from("Database_Model_Usuario")
                                 ->where("id_usuario_tipo in(2,4,5)")
                                ->andWhere("status='ACTIVO'")
                                 ->execute() as $obju) {
                        $arr[$obju->id_usuario] = $obju->id_usuario;
                    }

                    echo $this->formSelect("id_usuario", $this->profile()->id_usuario,
                        array("style"=>"width:260px","class"=>"selectnvo"),
                        $arr
                    ); ?>
                </td>
            </tr>
        <?php  }?>


    </table>
    <div style="height: 25px;"></div>
    <input style="width: 100%" type="button" id="send" class="button" value="Registrar ">
</form>
<script>
    if(document.getElementById("tipousu").value==2 || document.getElementById("tipousu").value==5 ){
        document.getElementById("tiendaorigen").style.display="Inherit";
    }
    $(".selectnvo").multiselect({
        multiple: false,
        header: "Selecciona una opcion",
        noneSelectedText: "Seleccionar",
        selectedList: 1
    }).multiselectfilter();
    $("#id_tienda").change(function (e) {
        e.preventDefault();
        var id=$("#id_tienda").val();
        $("#catalogo").attr('href','<?php echo $this->baseUrl("ventas/administrar/mostrarcatalogo?id_tienda="); ?>'+id);
        return false;
    });
    $("#tipo").change(function (e) {
        e.preventDefault();
        var id=$("#tipo").val();
        if(id=="Tarjeta Credito"|| id=="Tarjeta Debito") {
            $("#contcredencial").show();
        }else{
            $("#contcredencial").hide();
        }
        if(id=="Credito") {
            $("#contabono").show();
        }else{
            $("#contabono").hide();
        }

        return false;
    });
</script>
<script>
      
   $(document).ready(function () {

            save= function(){
                var nomcli=$('#nom_cli').val();
                var appat=$('#ap_pat').val();
                var apmat=$('#ap_mat').val();
                var telcli=$('#tel_cli').val();
                var comentcli=$('#coment_cli').val();
                if(nomcli && telcli){
                    $.post("<?php echo $this->baseUrl("ventas/administrar/saveaddpopup"); ?>",
                        {
                            nombre: nomcli,
                            ap_paterno: appat,
                            ap_materno: apmat,
                            telefono: telcli,
                            observaciones: comentcli
                        },
                        function (response) {
                          
                            if(response>0){
                                //alert("Group successfully added");
                                $('#id_persona').append($('<option>', {
                                    value: response,
                                    text: nomcli,
                                    selected:true
                                }));  
                                $(".selectnvo").multiselect({
                                    multiple: false,
                                    header: "Selecciona una opcion",
                                    noneSelectedText: "Seleccionar",
                                    selectedList: 1
                                }).multiselectfilter();
                                   $.fancybox.close();
                            }else{
                                alert("Oopss error al agregar cliente"+response);
                            }
                        }
                    );
                }else{
                    alert("El nombre y telefono es requerido");
                }

            }
        });
    $( "#barcode" ).autocomplete({
        source: [ <?php echo $cadena ?>],
        select: function(res) {
   
        }
    });
   

</script>