<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Trepsi</title>

    <script type="text/javascript">
        window.print();
    </script>

    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 11px;
        }
    </style>
</head>
<body style="text-align: center; width: 175px;">
<table width="190px"  style="align:center">
    <tr>
        <td width="19%" align="left"> <img width="100" height="60" src="<?php echo $this->baseUrl("images/logo.jpg"); ?>"/></td>
        <td width="81%" style="align:center"><strong>Trepsi S.A. DE C.V.</strong><br/>
            <label style="font-size: 10px">   AV PALO SOLO NO.14<br/>
            52471500<br/></label></td>
    </tr>
    <tr>
        <td colspan="2" align="left"><label style="font-size: 10px">HUIXQUILUCAN, ESTADO DE MEXICO, MEXICO<br/>
            R.F.C: TRE 960930-U8A<br/>
           </label>
          &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong  style="font-size: 12px" > Folio:</strong> <?php echo $this->obj->folio; ?></td>
    </tr>

</table>



<table width="170px">
    <tr>
        <th>Tienda</th>
        <td><?php

            echo $this->tienda; ?></td>
    </tr>
    <tr>
        <th>Fecha</th>
        <td><?php echo $this->obj->fecha; ?></td>
    </tr>
    <tr>
        <th>CAJERO</th>
        <td><?php echo $this->obj->Usuario->nombre; ?></td>
    </tr>
    <tr>
        <th>CLIENTE</th>
        <td><?php echo $this->obj->Persona->nombre; ?></td>
    </tr>

</table>



<p>
    TICKET DE VENTA POR REGALO<br>
    Cond. de Cambio:<br>
    Presentar este ticket obligarorio
    <br>
    Producto en perfectas condiciones
    <br>
    No hay devolución en efectivo
</p>
</body>
</html>


