<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Yo Amo Comprar</title>

    <script type="text/javascript">
        window.print();
    </script>

    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 11px;
        }
    </style>
</head>
<body style="text-align: center; width: 175px;">
<table width="190px"  style="align:center">
    <tr>
        <td width="100%" align="left" colspan="2">
            <img width="100%" height="90" src="<?php echo $this->baseUrl("images/logo.jpg"); ?>"/>
        </td>
    </tr>
    <tr>
        <td width="50%" colspan="2" style="align:left"><strong>Yo Amo Comprar</strong>
        </td>
    </tr>
        <tr>
            <td colspan="2">
                <label style="font-size: 10px"> <?php echo $this->obj->Tienda->ubicacion?><br/>Zitacuaro,Mich., Mexico<br/>
                    <strong> Tel.</strong>7151108800
                </label>
            </td>
    </tr>
    <tr>
        <td colspan="2" align="center"><label style="font-size: 10px">
                <strong> R.F.C:</strong>AARL921226DJ6
        </label>
        </td>
    </tr>

</table>



<table width="190px">
    <tr>
        <th>Folio</th>
        <td> <strong> <u><?php echo $this->obj->folio; ?></u></strong></td>
    </tr>

    <tr>
        <th>Fecha</th>
        <td><?php echo $this->obj->fecha; ?></td>
    </tr>
    <tr>
        <th>Cajero</th>
        <td><?php
            echo $this->obj->id_usuario;; ?></td>
    </tr>
    <tr>
        <th>Cliente</th>
        <td><?php echo $this->obj->Persona->nombre; ?></td>
    </tr>
    <tr>
        <th>Tipo Pago</th>
        <td><?php echo $this->obj->tipo; ?></td>
    </tr>
    <?php if($this->obj->tipo=="Credito") {
           $querysaldo = Doctrine_Query::create()
                    ->select("SUM(montoabono) AS saldo")
                    ->from("Database_Model_Deudores")
                    ->where("id_venta =?",$this->obj->id_venta)
                    ->andWhere("status = ?", "ACTIVA")
                    ->execute();
                    $saldo=0;
                foreach($querysaldo as $s){
                    $saldo=$s["saldo"];
                }

        ?>
        <tr>
            <th>Abono Inicial</th>
            <td><?php echo $saldo; ?></td>
        </tr>
    <?php
    }
    ?>




</table>

<h3>Artículos</h3>
<table width="190px">
    <?php //echo $this->obj->ticket_items; ?>
    <tbody>
    <tr>
        <th>Cant.</th>
       <!-- <th>Codigo Interno</th>  -->
        <th style="width: 70px">&nbsp;&nbsp;&nbsp;&nbsp;Producto&nbsp;&nbsp;&nbsp;&nbsp;</th>
        <th>Subt.</th>
        <th>Total</th>

    </tr>
    <?php
    $total = 0;
    $costo = 0;
    $totalComision = 0;
    $query= Doctrine_Query::create()
        ->from("Database_Model_ProductosVenta")
        ->where("id_venta=?",$this->obj->id_venta)
        ->execute();

    $querydesc= Doctrine_Query::create()
        ->from("Database_Model_Descuentos")
        ->where("id_venta=?",$this->obj->id_venta)
        ->execute();
    $msj="";
    foreach ($querydesc as $objdesc):
        $msj.="<tr><td></td>
                <td colspan='2'>
                     ".$objdesc->descripciondesc."
                </td>
                <td>
                     $-".$objdesc->montodesc."
                </td>
                <td></td>
              </tr>";

    endforeach;
    $totalieps=0;
    $totaliva=0;
    $show=0;
    foreach ($query as $obj):
        if($obj->ProductoTienda->Producto->ieps>0){
            $totalieps+=$obj->total*0.08;
         }
        if($obj->ProductoTienda->Producto->exento_iva==1){
            //$totaliva+=$obj->total*$query->ProductoTienda->Producto->ieps;
        }else{
            $totaliva+=$obj->total*0.16;
        }
    if(ucwords(strtolower($obj->nombre))=="Excedente") {
        $show++;
    }
        ?>

        <tr  style="font-size: 12px" >
            <td><?php echo $obj->cantidad; ?></td>
           <!-- <td><?php echo $obj->ProductoTienda->Producto->codinter; ?></td>-->
            <td><?php echo ucwords(strtolower($obj->nombre)); ?></td>

            <td>$<?php  echo number_format($obj->total/$obj->cantidad, 0); ?></td>
            <td>$<?php  echo number_format($obj->total, 0); ?></td>

        </tr>
    <?php endforeach;
    echo $msj;?>

    </tbody>
    <?php if($show) {
        ?>
        <tr>
            <td colspan="4" align="left"><strong>Comentarios: <?php echo $this->obj->comentarios; ?></strong></td>
        </tr>
    <?php
    }
    ?>

   <!-- <?php
    if($this->tienda){
        ?>
        <tr>
            <td colspan="4" align="right"><strong>Sub Total</strong> $<?php echo number_format($this->obj->total/1.16, 2); ?></td>
        </tr>
       <tr>
        <td colspan="4" align="right"><strong>IVA: </strong>
            $<?php echo number_format($this->obj->total-($this->obj->total/1.16) , 2); ?></td>
    </tr>
    <?php
    }
    ?>
    -->
    <tr>
        <td colspan="4" align="right"><strong>Total $<?php echo number_format($this->obj->total, 2); ?></strong></td>
    </tr>


</table>
<p style="    width: 190px;">
     <?php if($this->obj->tipo=="Credito") { ?>
    GRACIAS POR SU COMPRA<br>USTED CUENTA CON 30 DIAS A PARTIR DE HOY PARA RECOGER SU PRODUCTO, AL FINALIZAR EL PERIODO DE TIEMPO EL ABONO NO ES REEMBOLSABLE.
        <?php }ELSE{ ?>
              GRACIAS POR SU COMPRA<br>REVISE SU PRODUCTO,
    SALIDA LA MERCANCIA NO SE ACEPTAN DEVOLUCIONES

        <?php }?>
</p>
</body>
</html>


