<?php
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/reset.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/2col.css", "screen,projection", false, array("title" => "2col"));
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/1col.css", "screen,projection", false, array("title" => "1col"));

$this->headLink()->appendStylesheet($this->baseUrl() . "/css/main-ie6.css", "screen", "lt IE 6");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/main.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/mystyle.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/style.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/jqueryui.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/Growl/css/growl.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/fancybox/jquery.fancybox-1.3.4.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/tipsy.css");
//para el multiselect
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/jquery.multiselect.css");
$this->headLink()->appendStylesheet($this->baseUrl() . "/css/jquery.multiselect.filter.css");



$this->headScript()->appendFile($this->baseUrl() . "/js/jquery.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/jquery-ui.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/jquery.functions.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/jquery.tipsy.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/jquery.validate.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/jquery.timepicker.addon.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/specific.functions.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/switcher.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/toggle.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/Growl/js/growl.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/jquery.timer.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/fancybox/jquery.fancybox-1.3.4.pack.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/fancybox/jquery.easing-1.3.pack.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/jquery.jstorage.js", 'text/javascript');
$this->headScript()->appendFile($this->baseUrl() . "/js/tablesorter/jquery.tablesorter.js", 'text/javascript');//para ordenar las tablas de los reportes
$this->headScript()->appendFile($this->baseUrl() . "/js/jquery.multiselect.js", 'text/javascript');//para el multiselect
$this->headScript()->appendFile($this->baseUrl() . "/js/jquery.multiselect.filter.js", 'text/javascript');//para el multiselect


echo $this->headLink();
echo $this->headScript();
?>



        <?php

            $arr = array();
            //$arr["2"]="Publico en General";
            //$arr["10052"]="Venta de Mayoreo";
            foreach (Doctrine_Query::create()
                         ->from("Database_Model_Persona")
                         ->where("id_usuario_tipo='1'")//sean clientes
                        ->andwhere("status='ACTIVO'")//venta de mayoreo
                         ->orderBy("id_persona desc")
                         ->execute() as $obj) {

                $arr[$obj->id_persona] = $obj->razon_social."/".$obj->nombre . " " . $obj->ap_paterno . " " . $obj->ap_materno;
            }


        echo $this->formSelect("id_persona", "",
            array("style"=>"width:460px","required" => "required","class"=>"selectnvocli"),
            $arr

        ); ?>


<script>
    $(".selectnvocli").multiselect({
        multiple: false,
        header: "Selecciona una opcion",
        noneSelectedText: "Seleccionar",
        selectedList: 1
    }).multiselectfilter();


</script>
