<h1> Devoluciones de Ventas</h1>
<h3 class="tit">Ver venta Folio No <?php echo $this->obj->folio; ?></h3>
<a href="<?php echo $this->baseUrl("ventas/administrar/imprimird/id/" . $this->obj->id_venta); ?>" target="_blank">Imprimir
    ticket devolucion</a>
<?php
if($this->obj->icredito==1){
?>

<fieldset>
    <div class="control-group" id="tiendaorigen" >
        <label class="control-label">Esta venta esta en estado de Credito </label>
        <div class="controls">
            <a href="<?php echo $this->baseUrl("deudores/administrar/alta/id/" . $this->obj->id_venta); ?>" target="_blank">Registrar Abono</a>
        </div>
    </div>
</fieldset>
<?php } ?>
<table>
    <tr>
        <th>Vendedor</th>
        <td><?php echo $this->obj->Usuario->nombre; ?></td>
    </tr>
    <tr>
        <th>Fecha</th>
        <td><?php echo $this->obj->fecha; ?></td>
    </tr>
    <tr>
        <th>Tipo de pago</th>
        <td><?php echo $this->obj->tipo; ?></td>
    </tr>
   
    <tr>
        <th>Total</th>
        <td>$<?php echo number_format($this->obj->total, 2); ?></td>
    </tr>


</table>

<h3 class="tit">Artículos</h3>


<table class="full-width">
    <tbody>
    <tr  >
        <th>Cantidad</th>
        <th>Codigo Interno</th>
        <th>Producto</th>
        <th>Subtotal</th>
        <th>Total</th>

    </tr>
    <?php
    $total = 0;
    $costo = 0;
    $totalComision = 0;
    $query= Doctrine_Query::create()
        ->from("Database_Model_ProductosVenta")
        ->where("id_venta=?",$this->obj->id_venta)
        ->execute();

    $querydesc= Doctrine_Query::create()
        ->from("Database_Model_Descuentos")
        ->where("id_venta=?",$this->obj->id_venta)
        ->execute();
    $msj="";
    foreach ($querydesc as $objdesc):
        $msj.="<tr><td></td>
                <td>
                     ".$objdesc->descripciondesc."
                </td>
                <td>
                     $-".$objdesc->montodesc."
                </td>
                <td></td>
              </tr>";

    endforeach;

    foreach ($query as $obj):


        ?>

        <tr >
            <td><?php echo $obj->cantidad; ?></td>
            <td><?php echo $obj->ProductoTienda->Producto->codinter; ?></td>
            <td><?php echo $obj->nombre; ?></td>

            <td>$<?php  echo number_format($obj->total/$obj->cantidad, 2); ?></td>
            <td>$<?php  echo number_format($obj->total, 2); ?></td>

        </tr>
    <?php endforeach;
    echo $msj;?>

    </tbody>
</table>