<script type="text/javascript">
    $(document).ready(function (){
        $("#barcodeform").submit(function (e){
            e.preventDefault();
            $("#codbarras").val($("#barcode").val());
            $("#barcode").val("");
            return false;
        });

        $("#costo").keyup(function (e){
            var impuesto=$("#impuesto").val();
            if(impuesto=="IVA"){
                var valimpuesto=1.16;
            }
            if(impuesto=="IEPS"){
                var valimpuesto=1.08;
            }
            if(impuesto=="EXENTO"){
                var valimpuesto=1;
            }
            if(impuesto==""){
                alert("No se ha seleccionado un impuesto para este producto");
                var valimpuesto=0;
            }

            var precio = (parseFloat($(this).val())*  valimpuesto*   parseFloat($("#multiplicador").val()));
            var preciod = (parseFloat($(this).val())*  1.3 );
            var precioc = (parseFloat($(this).val())*  1.1 );
            $("#precio").val(precio.toFixed(2));
            $("#precio_descuento").val(preciod.toFixed(2));
            $("#precio_costo").val(precioc.toFixed(2));

        });
        $("#impuesto").change(function () {
            var impuesto=$("#impuesto").val();
            var precio_anterior= $("#precio_anterior").val();
            if(impuesto=="IVA"){
                $("#exento_iva").val(0);
                $("#exento_ieps").val(1);
            }
            if(impuesto=="IEPS"){
                $("#exento_iva").val(1);
                $("#exento_ieps").val(0);
            }
            if(impuesto=="EXENTO"){
                $("#exento_iva").val(1);
                $("#exento_ieps").val(1);
            }



        });
    });
</script>
<script type="text/javascript">
    $(document).ready(function () {

        $("#button").click(function () {
            var costo_anterior=$("#costo_anterior").val();
            var precio_anterior= $("#precio_anterior").val();
            var precio_descuento_anterior=$("#precio_descuento_anterior").val();
            var costo=$("#costo").val();
            var precio= $("#precio").val();
            var precio_descuento=$("#precio_descuento").val();
            var msj="";
            if(costo_anterior==costo){
            }else{
                msj+=" \n El costo se ha modificado de:"+costo_anterior+" por:"+costo;
            }
            if(precio_anterior==precio){
            }else{
                msj+=" \n El precio se ha modificado de:"+precio_anterior+" por:"+precio;
            }
            if(precio_descuento_anterior==precio_descuento){
            }else{
                msj+=" \n El precio mayoreo se ha modificado de:"+precio_descuento_anterior+" por:"+precio_descuento;
            }

            var iframe = document.createElement("IFRAME");
            iframe.setAttribute("src", 'data:text/plain,');
            document.documentElement.appendChild(iframe);
            if(window.frames[0].window.confirm("Estas seguro de guardar estos cambios?"+msj)){
                document.form.submit();
            }else{
                // what to do if answer "NO"
            }


        });
        $("#impuesto").change(function () {
            var impuesto=$("#impuesto").val();
            var precio_anterior= $("#precio_anterior").val();
            if(impuesto=="IVA"){
                $("#exento_iva").val(0);
                $("#exento_ieps").val(1);
            }
            if(impuesto=="IEPS"){
                $("#exento_iva").val(1);
                $("#exento_ieps").val(0);
            }
            if(impuesto=="EXENTO"){
                $("#exento_iva").val(1);
                $("#exento_ieps").val(1);
            }


        });
    });
</script>
<h1>Productos</h1>
<h3 class="tit">ALTA PRODUCTO</h3>

<form action="" id="barcodeform">
    <input type="text" id="barcode" />
    <input type="submit" value="Usar" />
</form>
<form method="post" action="" enctype="multipart/form-data">

    <fieldset>
        <legend>Datos del producto</legend>
        <?php echo $this->form->id_categoria;
        echo $this->form->id_proveedor;
        echo $this->form->id_marca;
        echo $this->form->codbarras;
        echo $this->form->codinter;
        echo $this->form->nombre;

        ////////////////////////////////precio
        $ejeprecio= Doctrine_Query::create()
            ->from("Database_Model_EntradaProducto a, a.Entrada b")
            ->where("a.id_producto=?",$this->data["id_producto"])
            //->andWhere("cantvendida<cantidad")
            ->andWhere("b.status='ACTIVO'")
            ->orderBy("id_entrada_producto DESC")
            ->limit(1);


        $existentes=$totexistencias;
        $precio2=null;
        $preciocosto=null;
        $preciodesc2="";
        $id_entrada=0;
        foreach($ejeprecio->execute() as $ex){
            $existentes=$ex["cantidad"]-$ex["cantvendida"];
            $precio2=$ex["precio"];//sacamos el ultimo precio por fecha mientras no se allan vendido
            $preciocosto=$ex["precio_costo"];
            $preciodesc2=$ex["precio_descuento"];
            $id_entrada=$ex["id_entrada_producto"];
        }
        if($precio2){
            $precio=$precio2;
        }else{
            $precio=$this->data["precio"];
        }
        if($preciodesc2>0){
            $preciodesc=$preciodesc2;
        }else{
            $preciodesc=$this->data["precio_descuento"];
        }
        if($preciocosto>0){
            $preciocosto=$preciocosto;
        }else{
            $preciocosto=$this->data["precio_costo"];
        }
        $ejecosto= Doctrine_Query::create()
            ->from("Database_Model_EntradaProducto a, a.Entrada b")
            ->where("a.id_producto=?",$this->data["id_producto"])
            ->andWhere("b.status='ACTIVO'")
            // ->andWhere("a.cantvendida<a.cantidad")
            ->orderBy("id_entrada_producto desc")
            ->limit(1);
        $costoBase0=$this->data["costo"];
        // echo $ejecosto->getSqlQuery();//imprime la consulta qu ese esta generando
        $costoBase=0;
        $costoBase1=null;
        foreach($ejecosto->execute() as $excosto){
            $costoBase1=$excosto["costo"];//sacamos el ultimo precio por fecha mientras no se allan vendido
        }
        if($costoBase1){
            $costoBase=$costoBase1;
        }else{
            $costoBase=$costoBase0;
        }
        ?>
        <div class="control-group">
            <label class="control-label">Selecciona Impuesto</label>
            <div class="controls">
                <?php echo $this->formSelect("impuesto","",
                    array("style"=>"width:500px","required" => "required"),
                    array(""=>"Seleciona","IVA"=>"IVA","IEPS" => "IEPS","EXENTO" => "EXENTO")
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Costo</label>
            <div class="controls">
                <?php echo $this->formText("costo",$costoBase , array("style"=>"width:460px")); ?>
            </div>
        </div>

        <?php
        echo $this->form->condiciones;
        echo $this->form->multiplicador;

        ?>
        <div class="control-group">
            <label class="control-label">Precio *</label>
            <div class="controls">
                <input type="hidden" name="id_entrada_producto" value="<?php echo $id_entrada; ?>" >
                <?php echo $this->formText("precio",$precio , array("style"=>"width:460px")); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Precio Mayoreo</label>
            <div class="controls">
                <?php echo $this->formText("precio_descuento",$preciodesc , array("style"=>"width:460px")); ?>
            </div>
        </div>

        <?php



        echo $this->form->exento_iva;
        echo $this->form->exento_ieps;
        echo $this->form->paquete;
        echo $this->form->alerta_minima;

        ?>
        <div class="control-group">
            <label class="gfield_label" for="input_4_96">Imagen del producto</label>
            <div class="ginput_complex ginput_container">
                <span class="ginput_full">
                    <input name="imagen" id="imagen" type="file" value="" class="medium" tabindex="73"></span>
            </div>
        </div>
        <?php
        echo $this->form->Aceptar;


        ?>
    </fieldset>

</form>