
    <table cellspacing="0" class="full-width" id="example">
    <thead>
    <tr>
        <th>Cont.</th>
        <th>Codigo Inter.</th>
        <th>Nombre</th>
        <th>Marca</th>
        <th>Categoría</th>
        <th>Proveedor</th>
        <?php
        if($this->tipousu=="5"||($this->usu=='anny' || $this->usu=='Elena')){
        ?>
        <th>Costo</th>
        <?php
        }?>
        <th>Precio</th>
        <th>Mayoreo</th>
        <th>Exist. Tienda||Gral.</th>
        
        <th>Act.</th>

        <th >Acciones</th>
    </tr>
    </thead>
    <?php
    $cont=1;
    foreach ($this->query as $key => $obj):// de producto
        

       ?>
        <tr tooltip="true" title="Código de barras: <?php echo $obj["codinter"]; ?>">

            <td><?php echo $key; ?></td>
            <td><?php echo $obj["codinter"]; ?></td>
            <td> 
                <a fancybox="true" href="<?php echo $this->baseUrl("administracion/productos/detallesproducto/id/".$obj["id_producto"]); ?>">
                    <?php echo $obj["nombre"]; ?> </a>
            </td>
            <td><?php echo $obj["marca"]; ?></td>
            <td><?php echo $obj["categoria"]; ?></td>
            <td><?php echo $obj["proveedor"]; ?></td>
            <?php
                if($this->tipousu=="5"||($this->usu=='anny' || $this->usu=='Elena')){
            ?>
                <td>$<?php echo number_format($obj["costo"], 2); ?></td>
            <?php
            }?>
            <td  title="<?php echo "Existentes con este precio: ".$obj["existencias"]; ?>">$<?php echo number_format($obj["precio"], 2); ?></td>
            <td  title="<?php echo "Existentes con este precio: ".$obj["existencias"]; ?>">$<?php echo number_format($obj["preciomayoreo"], 2); ?></td>
            <?php
                if($this->tipousu=="5"){
            ?>
                <td><input type='text' class="productotienda" style="width:20px"  idproductotienda="<?php echo $obj["id_producto"]; ?>" value="<?php echo $obj["existenciastienda"]; ?>">||<?php echo $obj["existencias"]; ?></td>
            <?php
            }else{
            ?>
                <td><?php echo $obj["existenciastienda"]; ?>||<?php echo $obj["existencias"]; ?></td>
            <?php
            }?>
           
            <td>
                <?php
                if($obj["fecha_actualizacion"]){
                    echo $obj["fecha_actualizacion"]."<br>".$obj["usuario_actualizacion"]; 
                }else{
                    if($this->tipousu=="5"){
                    ?>
                        <input type='button' class='validar' idproductotienda="<?php echo $obj["id_producto"]; ?>" value='Validar' existencias="<?php echo $obj["existenciastienda"]; ?>">
                    <?php
                    }
                }
                
                ?>
            </td>
           
            <td>
                <a  target="_blank" title="Agregar nueva Entrada" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/inventarios/alta/id/" . $obj["id_producto"]); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
                </a>
                <?php
                if($obj["paquete"]=='SI'){ ?>
                    <a  title="Crear un paquete" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/paquete/alta/id/" . $obj["id_producto"]); ?>">
                        <img width="25" height="25" src="<?php echo $this->baseUrl("css/img/box.png") ?>" border="0"/>
                    </a>
            <?php } ?>

                <a target="_blank" title="Editar Producto" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/editar/id/" . $obj["id_producto"]); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/edit.png") ?>" border="0"/>
                </a>
                <a title="Baja Produco" delete="true"
                href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/borrar/id/" . $obj["id_producto"]); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/delete.png") ?>" border="0"/>
                </a>
            </td>
        </tr>
        <?php 
    endforeach; ?>
  </tbody>
</table>