
<h3 class="tit">Detalles</h3>


<table style="width: 100%; border:1;" id="table-resultados" >
    <tr>
        <th>Codigo Inter.</th>
        <th>Nombre</th>
        <th>Marca</th>
        <th>Categoria</th>
        <th>Proveedor</th>
        <th>Cantidad</th>
        <?php
        if($this->tipousu=="2" || $this->tipousu=="5" ){
            ?>
            <th>Costo</th>
        <?php
        }?>
        <th>Precio</th>
        <th>Tienda</th>
        <th>Acciones</th>
    </tr>

    <?php

    $query = Doctrine_Query::create()
        //->select("t.id_producto id_producto")
        ->from("Database_Model_ProductoTienda t")
        ->where("id_producto = ?", $this->id)
        ->andWhere("tienda_id_tienda!=14")
        //  ->orderBy("t.nombre ASC")
        ->execute();
    foreach ($query as $obj): ?>
        <tr>
            <td><?php echo $obj->Producto->codinter; ?></td>
            <td><?php echo $obj->Producto->nombre; ?></td>
            <td><?php echo $obj->Producto->Marca->nombre; ?></td>
            <td><?php echo $obj->Producto->Categoria->categoria; ?></td>
            <td><?php echo $obj->Producto->Proveedor->nombre_corto; ?></td>
            <td><?php echo $obj->existencias; ?></td>
            <?php
            if($this->tipousu=="2" || $this->tipousu=="5"){
                ?>
                <td>$<?php echo number_format($obj->Producto->costo, 2); ?></td>
            <?php
            }

            $ejeprecio= Doctrine_Query::create()
                ->from("Database_Model_EntradaProducto a, a.Entrada b")
                ->where("a.id_producto=?",$this->id)
                //->andWhere("cantvendida<cantidad")
                ->andWhere("b.status='ACTIVO'")
                ->orderBy("id_entrada_producto DESC")
                ->limit(1);
            $precio=0;
            foreach($ejeprecio->execute() as $ex){
                $precio=$ex["precio"];//sacamos el ultimo precio por fecha mientras no se allan vendido
            }
            if($precio>0){
                //$precio=$obj->precio;
            }else{
                $precio=$obj->Producto->precio;
            }




            ?>
            <td>$<?php echo number_format($precio, 2); ?></td>
            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td>
                <a  title="Traspasar  Productos de esta tienda" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/traspaso/alta/id/" .$obj->id_producto); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
                </a>
                <a  target="_blank" title="Ver Kardex" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/productos/kardex/id/" .$obj->id_productotienda); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/view.png") ?>" border="0"/>
                </a>
            </td>
           
        </tr>

    <?php endforeach;?>
</table>