<script type="text/javascript">
    $(document).ready(function (){
        $("#barcodeform").submit(function (e){
           e.preventDefault();

            $("#codbarras").val($("#barcode").val());

            $("#barcode").val("");
            return false;
        });

        $("#costo").keyup(function (e){
            var precio = (parseFloat($(this).val())*  parseFloat($("#condiciones").val()) )*   parseFloat($("#multiplicador").val());
            var preciod = (parseFloat($(this).val())*  1.3 );
            var precioc = (parseFloat($(this).val())*  1.1 );
            $("#precio").val(precio.toFixed(2));
            $("#precio_descuento").val(preciod.toFixed(2));
            $("#precio_costo").val(precioc.toFixed(2));

        });

    });
</script>
<h1>Productos</h1>
    <h3 class="tit">EDITAR PRODUCTO</h3>

        <form action="" id="barcodeform">
            <input type="text" id="barcode" />
            <input type="submit" value="Usar" />
        </form>
<form method="post">

        <fieldset>
            <legend>Datos del producto</legend>
            <?php echo $this->form->id_categoria;
            echo $this->form->id_proveedor;
            echo $this->form->id_marca;
            echo $this->form->codbarras;
            echo $this->form->codinter;
            echo $this->form->nombre;

            ////////////////////////////////precio
            $ejeprecio= Doctrine_Query::create()
                ->from("Database_Model_EntradaProducto a, a.Entrada b")
                ->where("a.id_producto=?",$this->data["id_producto"])
                //->andWhere("cantvendida<cantidad")
                ->andWhere("b.status='ACTIVO'")
                ->orderBy("id_entrada_producto DESC")
                ->limit(1);


            $existentes=$totexistencias;
            $precio2=null;
            $preciocosto=null;
            $preciodesc2="";
            $id_entrada=0;
            foreach($ejeprecio->execute() as $ex){
                $existentes=$ex["cantidad"]-$ex["cantvendida"];
                $precio2=$ex["precio"];//sacamos el ultimo precio por fecha mientras no se allan vendido
                $preciocosto=$ex["precio_costo"];
                $preciodesc2=$ex["precio_descuento"];
                $id_entrada=$ex["id_entrada_producto"];
            }
            if($precio2){
                $precio=$precio2;
            }else{
                $precio=$this->data["precio"];
            }
            if($preciodesc2>0){
                $preciodesc=$preciodesc2;
            }else{
                $preciodesc=$this->data["precio_descuento"];
            }
            if($preciocosto>0){
                $preciocosto=$preciocosto;
            }else{
                $preciocosto=$this->data["precio_costo"];
            }
            $ejecosto= Doctrine_Query::create()
                ->from("Database_Model_EntradaProducto a, a.Entrada b")
                ->where("a.id_producto=?",$this->data["id_producto"])
                ->andWhere("b.status='ACTIVO'")
               // ->andWhere("a.cantvendida<a.cantidad")
                ->orderBy("id_entrada_producto desc")
                ->limit(1);
            $costoBase0=$this->data["costo"];
            // echo $ejecosto->getSqlQuery();//imprime la consulta qu ese esta generando
            $costoBase=0;
            $costoBase1=null;
            foreach($ejecosto->execute() as $excosto){
                $costoBase1=$excosto["costo"];//sacamos el ultimo precio por fecha mientras no se allan vendido
            }
            if($costoBase1){
                $costoBase=$costoBase1;
            }else{
                $costoBase=$costoBase0;
            }




?>
            <div class="control-group">
                <label class="control-label">Costo</label>
                <div class="controls">
            <?php echo $this->formText("costo",$costoBase , array("style"=>"width:460px")); ?>
                 </div>
            </div>

<?php
            echo $this->form->condiciones;
            echo $this->form->multiplicador;

?>
            <div class="control-group">
                <label class="control-label">Precio *</label>
                <div class="controls">
                    <input type="hidden" name="id_entrada_producto" value="<?php echo $id_entrada; ?>" >
                    <?php echo $this->formText("precio",$precio , array("style"=>"width:460px")); ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Precio Mayoreo</label>
                <div class="controls">
                    <?php echo $this->formText("precio_descuento",$preciodesc , array("style"=>"width:460px")); ?>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label">Precio Costo</label>
                <div class="controls">
                    <?php echo $this->formText("precio_costo",$preciocosto , array("style"=>"width:460px")); ?>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">Imagen</label>
                <div class="controls">
                    <?php echo $this->filepicker("imagen",$this->data['imagen']);
            if($this->data['imagen'] !=''){
                $t="<a href='".$this->data['imagen']."' target='_blank'>Ver</a>";
            }else{
                $t='Sin Imagen';
            }
            echo $t;
            ?>

                </div>
            </div>

 <?php



            echo $this->form->exento_iva;
            echo $this->form->exento_ieps;
            echo $this->form->ieps;
            echo $this->form->paquete;
            echo $this->form->alerta_minima;
            echo $this->form->paquete;
            echo $this->form->Aceptar;


            ?>

        </fieldset>

</form>