<script type="text/javascript">
    $(document).ready(function (){
        $("#barcodeform").submit(function (e){
            e.preventDefault();
            $("#codbarras").val($("#barcode").val());
            $("#barcode").val("");
            return false;
        });

        $("#costo").keyup(function (e){
            var precio = (parseFloat($(this).val())*  parseFloat($("#iva").val()) )*   parseFloat($("#multiplicador").val());
            $("#precio").val(precio);
        });
    });
</script>
<h1>Productos</h1>
<h3 class="tit">Registrar Nueva Entrada</h3>

<form method="post" action="" class="form-horizontal">
    <fieldset>
        <legend>Entrada de Productos</legend>
        <div class="control-group">
            <label class="control-label">Producto</label>
            <div class="controls">
                <?php echo $this->formSelect("id_producto", $this->idprod,
                    array("style"=>"width:460px","required" => "required"),
                    Database_Model_Producto::getAllArr()
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Tienda</label>
            <div class="controls">
                <?php echo $this->formSelect("id_tienda", $this->data["id_tienda"],
                    array("style"=>"width:460px","required" => "required"),
                    Database_Model_Tienda::getAll2()
                ); ?>
            </div>
        </div>

        <div class="control-group">
            <label class="control-label">Cantidad</label>
            <div class="controls">
                <?php echo $this->formText("cantidad", $this->data["cantidad"],
                    array("required" => "required")
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Costo</label>
            <div class="controls">$
                <?php echo $this->formText("costo", $this->data["costo"],
                    array("" => "")
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Multiplicador IVA.</label>
            <div class="controls">
                <?php echo $this->formText("iva", 1.16,
                    array("" => "")
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Multiplicador</label>
            <div class="controls">
                <?php echo $this->formText("multiplicador", 1.5,
                    array("" => "")
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Precio</label>
            <div class="controls">$
                <?php echo $this->formText("precio", $this->data["precio"],
                    array("" => "")
                ); ?>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label">Comentarios</label>
            <div class="controls">
                <?php echo $this->formTextarea("comentarios", $this->data["comentarios"],
                    array()
                ); ?>
            </div>
        </div>

    </fieldset>


    <div class="form-actions">
        <input type="submit" value="Aceptar">

    </div>
</form>


<?php echo $this->form; ?>
<table class="full-width">
    <thead>
    <tr>
        <th>Cont.</th>
        <th>Cod Barras</th>
        <th>Nombre</th>
        <th>Cantidad</th>
        <th>Costo</th>
        <th>Precio</th>
        <th>Tienda</th>
        <th>Comentarios</th>
        <th>Usuario Alta</th>
        <th>Fecha Registro</th>

        <th width="75">Acciones</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach ($this->query as $obj): ?>
        <tr tooltip="true" title="Código de barras: <?php echo $obj->Producto->codbarras; ?>">
            <td><?php echo $this->counter++; ?></td>
            <td><?php echo $obj->Producto->codbarras; ?></td>
            <td><?php echo $obj->Producto->nombre; ?></td>
            <td><?php echo $obj->cantidad; ?></td>
            <td>$<?php echo number_format($obj->costo,2); ?></td>
            <td>$<?php echo number_format($obj->precio,2); ?></td>
            <td><?php echo $obj->Tienda->nombre; ?></td>
            <td><?php echo $obj->comentarios; ?></td>
            <td><?php echo $obj->Usuario->nombre; ?></td>
            <td><?php echo $obj->fechare_gistro; ?></td>

            <td>


                <a delete="true"
                   href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/borrarentradaprod/id/" . $obj->id_entrada_producto); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/delete.png") ?>" border="0"/>
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>

<script>
    $(function () {
        //$( "#on_hire_fecha" ).datepicker();
        $("#fecha_nacimiento").datepicker({
            format: 'dd-mm-yyyy'
        });
    });
    document.getElementById("idcliente").style.display="none";
    function muestraidcliente(){

       if(document.getElementById("id_usuario_tipo").value==1){
        document.getElementById("idcliente").style.display="Inherit";
       }else{
           document.getElementById("idcliente").style.display="none";
       }
    }

</script>