
<h3 class="tit">Historial</h3>

<table style="width: 100%; border:1;" id="table-resultados" >
    <tr>
        <th>ID</th>
        <th>Codigo</th>
        <th>Nombre</th>
        <th>Existencia Anterior</th>
        <th>Existencia</th>
        <th>Tienda</th>
        <th>Usuario</th>
        <th>Fecha</th>
        <th>Acciones</th>
    </tr>

    <?php
  
    foreach ($this->query as $key => $obj){ ?>
        <tr>
            <td><?php echo $obj->id_historialinventario; ?></td>
            <td><?php echo $obj->ProductoTienda->Producto->codinter; ?></td>
            <td><?php echo $obj->ProductoTienda->Producto->nombre; ?></td>
            <td style="text-align:center"><?php echo $obj->existencia_anterior; ?></td> 
            <td style="text-align:center"><?php echo $obj->existencia; ?></td>
            <td><?php echo $obj->ProductoTienda->Tienda->nombre; ?></td>
            <td><?php echo $obj->id_usuario; ?></td>
            <td><?php echo $obj->fecha_registro; ?></td>
            <td>
                <a  target="_blank" title="Ver Kardex" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/productos/kardex/id/" .$obj->id_productotienda); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/view.png") ?>" border="0"/>
                </a>
            </td>
           
        </tr>

    <?php }?>
</table>