<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Cremas</title>

    <script type="text/javascript">
        window.print();
    </script>

    <style type="text/css">
        body {
            font-family: Arial;
            font-size: 15px;
        }
    </style>
</head>
<body style="text-align: center; width: 175px;">
<table width="1000" border="0" style="font-size: 18px">
    <tr colspan="3">
        <td width="400"  align="left">Inventario de Todos los productos</td>
        <td width="0"  align="right"> <label style="font-size:14px">Mexico D.F. a &nbsp;<?php echo date('Y-m-d h:i:s'); ?> </label></td>
    </tr>
    <tr>
        <td colspan="3" align="left"></td>
        <td width="177"><label style="font-size:14px"><label style="color:#F00"></label></label></td>
    </tr>
    <tr colspan="3" align="left">
        <td><label style="font-size:14px"><label style="color:#120000"> </label></label></td>
        <td width="0"></td>
    </tr>
    <tr>
        <td colspan="4" align="left"><label style="font-size:14px"></label></td>
    </tr>
    <tr>
        <td colspan="4" align="left"><label style="font-size:14px">Usuario: &nbsp;<?php echo $this->profile()->nombre; ?> </label></td>
    </tr>
</table>
<h3>Lista</h3>
<table class="full-width" border="1">
        <thead>
        <tr>
            <th>Cont.</th>
            <th>Codigo Inter.</th>
            <th>Nombre</th>
            <th>Marca</th>
            <th>Categoría</th>
            <th>Proveedor</th>
            <?php
            if($this->tipousu=="5"||($this->usu=='anny' || $this->usu=='tavo' || $this->usu=='Elena')){
            ?>
            <th>Costo</th>
            <?php
            }?>
            <th>Precio</th>
            <th>Mayoreo</th>
            <th>Exist. Tienda||Gral.</th>
            
            <th>Act.</th>

        </tr>
        </thead>
        <tbody id='table-resultados'>
        <?php
        $cont=1;
        foreach ($this->query as $key => $obj):// de producto
            

        ?>
            <tr tooltip="true" title="Código de barras: <?php echo $obj["codinter"]; ?>">

                <td><?php echo $key; ?></td>
                <td><?php echo $obj["codinter"]; ?></td>
                <td> 
                    <a fancybox="true" href="<?php echo $this->baseUrl("administracion/productos/detallesproducto/id/".$obj["id_producto"]); ?>">
                        <?php echo $obj["nombre"]; ?> </a>
                </td>
                <td><?php echo $obj["marca"]; ?></td>
                <td><?php echo $obj["categoria"]; ?></td>
                <td><?php echo $obj["proveedor"]; ?></td>
                <?php
                    if($this->tipousu=="5"||($this->usu=='anny' || $this->usu=='tavo' || $this->usu=='Elena')){
                ?>
                    <td>$<?php echo number_format($obj["costo"], 2); ?></td>
                <?php
                }?>
                <td  title="<?php echo "Existentes con este precio: ".$obj["existencias"]; ?>">$<?php echo number_format($obj["precio"], 2); ?></td>
                <td  title="<?php echo "Existentes con este precio: ".$obj["existencias"]; ?>">$<?php echo number_format($obj["preciomayoreo"], 2); ?></td>
                <?php
                    if($this->tipousu=="5"){
                ?>
                    <td><input type='text' class="productotienda" style="width:20px" idproductotienda="<?php echo $obj["id_producto"]; ?>" value="<?php echo $obj["existenciastienda"]; ?>">||<?php echo $obj["existencias"]; ?></td>
                <?php
                }else{
                ?>
                    <td><?php echo $obj["existenciastienda"]; ?>||<?php echo $obj["existencias"]; ?></td>
                <?php
                }?>
            
                <td>
                    <?php
                    if($obj["fecha_actualizacion"]){
                        echo $obj["fecha_actualizacion"]."<br>".$obj["usuario_actualizacion"]; 
                    }else{
                        if($this->tipousu=="5"){
                        ?>
                            <input type='button' class='validar' idproductotienda="<?php echo $obj["id_producto"]; ?>" value='Validar' existencias="<?php echo $obj["existenciastienda"]; ?>">
                        <?php
                        }
                    }
                    
                    ?>
                </td>
            
               
            </tr>
            <?php 
        endforeach; ?>
        </tbody>
    </table>

</body>
</html>