<script>
    function ProductosTienda(){

        var tienda=document.getElementById("id_tienda").value;
        var baseurl=document.getElementById("baseurl").value;
       
       if(tienda!=4){
           location.href = baseurl+"productotienda/id_tienda/"+tienda;
       }
    }
</script>
<style>
    .toggler { width: 100px;  }
    #button { padding: .5em 1em; text-decoration: none; }
    #effect { width: 240px; height: 135px; padding: 0.4em; position: relative; }
    #effect h3 { margin: 0; padding: 0.4em; text-align: center; }
</style>
<h1>Productos</h1>
<p class="t-right"><input type="hidden" id="baseurl" value="<?php echo $this->baseUrl($this->request->getModuleName(). "/" .$this->request->getControllerName()."/"); ?>">
    <a title="Nuevo Producto" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
    </a>
</p>
<?php
if($this->tipousu){
?>
  

<div class="control-group">
    <div class="controls">
        <?php $url_actual = "http://" . $_SERVER["SERVER_NAME"] . $_SERVER["REQUEST_URI"];
        //echo "<strong>$url_actual</strong>";
        $pieces = explode("?", $url_actual);
        $pieces[0]; // piece1
        $pieces[1]; // piece2
        $todos="vertodo=0&";
        if($this->vertodo){
            $todos="vertodo=1&";

        }
        ?>
        <a href="<?php echo $this->baseUrl("administracion/productos/excelproducto?".$todos.$pieces[1]); ?>" class="btn btn-app btn-success btn-mini">
            <i class="icon-download bigger-160"></i>
            Exportar Todo
        </a>&nbsp;&nbsp;&nbsp;&nbsp;

        <a target="_blank" href="<?php echo $this->baseUrl("administracion/productos/imprimirtodo?".$todos.$pieces[1]); ?>" class="btn btn-app btn-success btn-mini">
            <i class="icon-download bigger-160"></i>
           Imprimir Todo
        </a>

    </div>
</div>
    </form>
    <!--ppara el vilidador de forms
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css"/>

    -->
<?php
}?>

<table cellspacing="0" class="full-width" id="example">
    <thead>
    <tr>
        <th>Cont.</th>
        <th>Codigo Inter.</th>
        <th>Nombre</th>
        <th>Marca</th>
        <th>Categoría</th>
        <th>Proveedor</th>
        <?php
        if($this->tipousu=="5"||($this->usu=='anny' || $this->usu=='Elena')){
        ?>
        <th>Costo</th>
        <?php
        }?>
        <th>Precio</th>
        <th>Precio Mayoreo</th>
        <th>Exist. Tienda</th>
        <th>Exist. Globales</th>
        <th>Paquete</th>

        <th >Acciones</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $cont=1;
    foreach ($this->query as $key => $obj):// de producto
        

       ?>
        <tr tooltip="true" title="Código de barras: <?php echo $obj["codinter"]; ?>">

            <td><?php echo $key; ?></td>
            <td><?php echo $obj["codinter"]; ?></td>
            <td> 
                <a fancybox="true" href="<?php echo $this->baseUrl("administracion/productos/detallesproducto/id/".$obj["id_producto"]); ?>">
                    <?php echo $obj["nombre"]; ?> </a>
            </td>
            <td><?php echo $obj["marca"]; ?></td>
            <td><?php echo $obj["categoria"]; ?></td>
            <td><?php echo $obj["proveedor"]; ?></td>
            <?php
                if($this->tipousu=="5"||($this->usu=='anny' || $this->usu=='Elena')){
            ?>
                <td>$<?php echo number_format($obj["costo"], 2); ?></td>
            <?php
            }?>
            <td  title="<?php echo "Existentes con este precio: ".$obj["existencias"]; ?>">$<?php echo number_format($obj["precio"], 2); ?></td>
            <td  title="<?php echo "Existentes con este precio: ".$obj["existencias"]; ?>">$<?php echo number_format($obj["preciomayoreo"], 2); ?></td>
            <td><?php echo $obj["existenciastienda"]; ?></td>
            <td><?php echo $obj["existencias"]; ?></td>
            <td><?php
                if($obj["paquete"]=='SI'){
                    echo "<label style='color: #0000cc;'>SI</label><br> "; ?>
                    <a fancybox="true" href="<?php echo $this->baseUrl("administracion/productos/detallespaquete/id/".$obj["id_producto"]); ?>">
                        Mostrar </a>
                <?php
                }else{
                    echo $obj["paquete"];
                }
                // echo $obj["existencias"]; ?></td>

            <td>
                <a  target="_blank" title="Agregar nueva Entrada" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/inventarios/alta/id/" . $obj["id_producto"]); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
                </a>
                <?php
                if($obj["paquete"]=='SI'){ ?>
                    <a  title="Crear un paquete" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/paquete/alta/id/" . $obj["id_producto"]); ?>">
                        <img width="25" height="25" src="<?php echo $this->baseUrl("css/img/box.png") ?>" border="0"/>
                    </a>
            <?php } ?>

                <a target="_blank" title="Editar Producto" href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/editar/id/" . $obj["id_producto"]); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/edit.png") ?>" border="0"/>
                </a>
                <a title="Baja Produco" delete="true"
                href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/borrar/id/" . $obj["id_producto"]); ?>">
                    <img src="<?php echo $this->baseUrl("css/img/delete.png") ?>" border="0"/>
                </a>
            </td>
        </tr>
        <?php 
    endforeach; ?>
    </tbody>
</table>


<script>


    $(".selectnvo").multiselect({
        multiple: false,
        header: "Selecciona una opcion",
        noneSelectedText: "Seleccionar",
        selectedList: 1
    }).multiselectfilter();

    $(function() {

        var table =	$('#example').dataTable( {
            "bJQueryUI": true,
            "scrollY": 200,
            "aaSorting": [[1, "asc"]],
            "scrollX": true,
            "iDisplayLength": 15,
            "bPaginate": true,
            "bAutoWidth": true,
            "sPaginationType": "full_numbers",
            "bSort": true,
            "aLengthMenu": [[5, 10, 15, 25, 50, -1], [5, 10, 15, 25, 50, "All"]]
        } );

    });


</script>