<div class="modal" id="modal" align="center">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true" onclick="$('#modal').modal('Cargando...');">&times;</button>
                <h4 class="modal-title" id="titleModal">&nbsp;</h4>
            </div>
            <div class="modal-body">
                Cargando...
            </div>

        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
<style>
    .modal {
        display: none;
    }
</style>
<style type="text/css">
    .cancelada {
        opacity: .5;
    }
</style>
<section id="section_top" class="panel">
    <header class="panel-heading">
        Kardex
    </header>
    <div class="panel-body">
        <!-- Filtros para listar -->
        <form class="form-inline"  role="form">
            <table style="width: 50%;">
                <tr align="center">
                    <td> <h2>Producto</h2></td>
                    <td> <h2> Sucursal</h2></td>
                </tr>
                <tr align="center">
                    <td>
                        <div class="controls">
                            <?php echo $this->formSelect("id_producto", $this->query->id_producto,
                                array("class" => "form-control selectnvo"),
                                Database_Model_Producto::getAllArr()
                            ); ?>
                        </div>
                    </td>
                    <td>
                        <h3>
                            <div class="controls">
                                <?php echo $this->formSelect("id_sucursal", $this->query->tienda_id_tienda,
                                    array("class" => "form-control selectnvo"),
                                    Database_Model_Tienda::getAllT()
                                ); ?>
                            </div>
                        </h3>
                    </td>
                </tr>
                <tr align="center">
                    <td colspan="2">
                        <input type="submit" class="button"  id="" value="Listar" name=""/>
                    </td>
                </tr>
            </table>
        </form>

        <br>

        <table style="width: 50%;align:center">
            <tr align="center">
                <td> <h2>ACTUAL</h2></td>
                <td> <h2>ENTRADAS</h2></td>
                <td> <h2>SALIDAS</h2></td>
                <td> <h2>KARDEX</h2></td>
            </tr>
            <tr align="center">
                <td>
                    <h3>
                    <span style="color:blue">

                        <?php
                        // echo $this->invactual->getSqlQuery();
                        $actual=0;
                        $id_productotienda=$this->query->id_productotienda;
                        $id_producto=$this->query->id_producto;
                        $id_sucursal=$this->query->tienda_id_tienda;
                            echo $actual=$this->query->existencias;
                        ?>
                        </span><br>
                        <a fancybox="true" href="<?php echo $this->baseUrl("administracion/productos/actualizar/id/".$this->query->id_productotienda); ?>">
                            Actualizar </a>
                    </h3>
                </td>
                <td>
                    <h3>
                    <span style="color:green">
                    <?php
                    $cantidadentr=0;$cantidadsal=0;
                    $cantidadentrpendi=0;
                    //para sacar las Entradas directas
                    $entradasdirectas = Doctrine_Query::create()
                        ->from("Database_Model_EntradaProducto ib,ib.Producto p, ib.Entrada cb, cb.Tienda b")
                        ->where("ib.id_producto = ?",$id_producto)
                        ->andWhere("cb.id_tienda = ?",$id_sucursal)
                        // ->andWhere("ib.status = 1")
                        // ->orWhere("destino = ?",$id_sucursal)
                        ->orderBy("cb.fecha")
                    ;

                    foreach($entradasdirectas->execute() as $objtsal){
                        switch ($objtsal->status) {
                            case '':
                                break;
                            case 'ACTIVO':
                                $cantidadentr+=$objtsal->cantidad;
                                break;
                            case 'PENDIENTE':
                                break;
                        }
                    }
                    //para sacar las Entradas por traspasos
                    $traspasosorigen = Doctrine_Query::create()
                        ->from("Database_Model_TraspasoProducto ib,ib.Producto p, ib.Traspaso cb, cb.Tienda b")
                        ->where("ib.id_producto = ?",$id_producto)
                        ->andWhere("cb.id_tienda = ?",$id_sucursal)
                        // ->andWhere("cb.status = 'ACTIVO'")
                        // ->orWhere("destino = ?",$id_sucursal)
                        ->orderBy("cb.fecha")
                    ;

                    foreach($traspasosorigen->execute() as $objtsal){
                        switch ($objtsal->status) {
                            case '':
                                break;
                            case 'ACTIVO':
                                $cantidadentr+=$objtsal->cantidad;
                                break;
                            case 'PENDIENTE':
                                $cantidadentrpendi+=$objtsal->cantidad;
                                break;
                        }
                    }

                    //para sacar las Entradas por devoluciones
                    $productoscancelados = Doctrine_Query::create()
                        ->from("Database_Model_VentaProductocancelado ib,ib.ProductosVenta pv")
                        ->where("pv.id_productotienda = ?",$id_productotienda)
                        ->andWhere("ib.id_tienda_destino = ?",$id_sucursal)
                        // ->andWhere("ib.status = 1")
                        // ->orWhere("destino = ?",$id_sucursal)
                        ->orderBy("ib.fecha_registro")
                    ;


                    echo $cantidadentr;
                    ?>
                        </span>
                    </h3>
                </td>
                <td>
                    <h3>
                    <span style="color:red">

                        <?php
                        $cantidadsalpendi=0;
                        //para sacar las Salidas por traspasos
                        $traspasosdestino = Doctrine_Query::create()
                            ->from("Database_Model_TraspasoProducto ib,ib.Producto, ib.Traspaso cb, cb.Tienda b")
                            ->where("ib.id_producto = ?",$id_producto)
                            ->andWhere("cb.id_tiendaanterior = ?",$id_sucursal)
                            // ->andWhere("ib.status = 1")
                            // ->orWhere("destino = ?",$id_sucursal)
                            ->orderBy("cb.fecha") ;


                        foreach($traspasosdestino->execute() as $objten){
                            switch ($objten->status) {
                                case '':
                                    break;
                                case 'ACTIVO':
                                    $cantidadsal+=$objten->cantidad;
                                    break;
                                case 'PENDIENTE':
                                    $cantidadsalpendi+=$objten->cantidad;
                                    break;
                            }

                        }

                        //para sacar las Salidas por ventas
                        $productosvendidos = Doctrine_Query::create()
                            ->from("Database_Model_ProductosVenta pv,pv.Venta v, pv.ProductoTienda cb, cb.Producto b")
                            ->where("pv.id_productotienda = ?",$id_productotienda)
                            ->andWhere("pv.cancelado = ?",0)
                            // ->andWhere("ib.status = 1")
                            // ->orWhere("destino = ?",$id_sucursal)
                            ->orderBy("v.fecha")
                        ;
                        $productosvendidos2 = Doctrine_Query::create()
                            ->from("Database_Model_ProductosVenta pv,pv.Venta v, pv.ProductoTienda cb, cb.Producto b")
                            ->where("pv.id_productotienda = ?",$id_productotienda)
                            //->andWhere("pv.cancelado = ?",0)
                            // ->andWhere("ib.status = 1")
                            // ->orWhere("destino = ?",$id_sucursal)
                            ->orderBy("v.fecha")
                        ;
                        //para sacar las Salidas directas
                        $salidadirecta = Doctrine_Query::create()
                            ->from("Database_Model_SalidaProducto pv,pv.Salida v, pv.Producto cb")
                            ->where("pv.id_producto = ?",$id_producto)
                            ->andWhere("v.id_tiendaanterior = ?",$id_sucursal)
                            // ->andWhere("ib.status = 1")
                            // ->orWhere("destino = ?",$id_sucursal)
                            ->orderBy("pv.fechare_gistro")
                        ;
                        foreach($productosvendidos->execute() as $objtv){
                            $cantidadsal+=$objtv->cantidad;
                        }
                        foreach($salidadirecta->execute() as $objtv){
                            $cantidadsal+=$objtv->cantidad;
                        }
                        echo $cantidadsal;
                        ?>
                        </span>
                    </h3>
                </td>
                <td>
                    <h3>
                    <span style="color:orange"><?php
                       $kardex= $cantidadentr-$cantidadsal;

                        echo $kardex;
                        ?>
                        </span>
                    </h3>
                </td>
            </tr>
            <tr align="center">
                <td colspan="4">
                    <?php if($kardex==$actual){ ?>
                        <h3>
                            <span style="color:blue">
                                Empatado
                                </span>
                        </h3>
                    <?php  }?>
                    <?php if($kardex>$actual){ ?>
                        <h3>
                            <span style="color:red">
                                Faltan <? echo $kardex-$actual;  ?> &nbsp; Salidas
                                </span>
                        </h3>
                    <?php  }?>
                    <?php if($kardex<$actual){ ?>
                        <h3>
                            <span style="color:red">
                                Faltan <? echo $actual-$kardex;  ?>&nbsp; Entradas
                                </span>
                        </h3>
                    <?php  }?>

                </td>
            </tr>
        </table>

        <br> <br>
        <h2>Entradas Directas</h2>
        <div class="adv-table">
            <table class="display table table-striped table-hover table-bordered" id="tabla2">
                <thead>
                <tr>
                    <th>FOLIO</th>
                    <th>ID</th>
                    <th>Producto</th>
                    <th>SKU</th>
                    <th>Cantidad</th>
                    <th>Costo</th>
                    <th>Precio</th>
                    <th>Tienda</th>
                    <th>Fecha de Traspaso</th>
                    <th>Manda</th>
                    <th>Validado por</th>
                    <th>Fecha Validacion</th>
                    <th>ESTATUS</th>

                </tr>
                </thead>
                <tbody>
                <?php
                $cantidadentrada=0;
                foreach($entradasdirectas->execute() as $objt){
                    ?>
                    <tr>
                        <td> <?php echo $objt->id_entrada;  ?></td>
                        <td> <?php echo $objt->id_entrada_producto;  ?></td>
                        <td> <?php echo $objt->Producto->nombre;  ?></td>
                        <td> <?php echo $objt->Producto->codinter;  ?></td>
                        <td> <?php echo $objt->cantidad;  ?></td>
                        <td> <?php echo $objt->costo;  ?></td>
                        <td> <?php echo $objt->precio;  ?></td>
                        <td> <?php echo $objt->Entrada->Tienda->nombre; ?> </td>
                        <td> <?php echo $objt->Entrada->fecha; ?>  </td>
                        <td> <?php echo $objt->Entrada->id_usuario;  ?></td>
                        <td> <?php
                            $objv = Doctrine_Core::getTable("Database_Model_Validaentrada")->findOneBy("id_entrada", $objt->id_entrada);
                            echo $objv->id_usuario;  ?></td>
                        <td> <?php echo $objv->fecha_registro;  ?></td>
                        <td>
                            <?php echo $objt->status;
                            $cantidadentrada+=$objt->cantidad;
                            ?>
                        </td>


                    </tr>
                <?php }
                ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td> </td>
                    <td></td>
                    <td> <?php echo $cantidadentrada;  ?></td>
                    <td>       </td> <td>  </td>
                    <td>  </td><td></td><td></td>
                    <td></td><td></td>
                    <td></td>
                </tr>
                </tbody>
            </table>
        </div>
        <br> <br>
        <h2>Traspasos Entrada</h2>
        <div class="adv-table">
            <table class="display table table-striped table-hover table-bordered" id="tabla2">
                <thead>
                <tr>
                    <th>FOLIO</th>
                    <th>ID</th>
                    <th>Producto</th>
                    <th>SKU</th>
                    <th>Cantidad</th>
                    <th>Costo</th>
                    <th>Precio</th>
                    <th>Tienda</th>
                    <th>Fecha de Traspaso</th>
                    <th>Manda</th>
                    <th>Status</th>

                </tr>
                </thead>
                <tbody>
                <?php
                $cantidadentrada=0;
                foreach($traspasosorigen->execute() as $objt){
                    $cantidadentrada+=$objt->cantidad;
                    ?>
                    <tr>
                        <td> <?php echo $objt->id_traspaso;  ?></td>
                        <td> <?php
                            $objv = Doctrine_Core::getTable("Database_Model_Tienda")->findOneBy("id_tienda", $objt->Traspaso->id_tiendaanterior);
                            echo $objv->nombre;  ?></td>
                        <td> <?php echo $objt->Producto->nombre;  ?></td>
                        <td> <?php echo $objt->Producto->codinter;  ?></td>
                        <td> <?php echo $objt->cantidad;  ?></td>
                        <td> <?php echo $objt->costo;  ?></td>
                        <td> <?php echo $objt->precio;  ?></td>
                        <td> <?php echo $objt->Traspaso->Tienda->nombre; ?> </td>
                        <td> <?php echo $objt->Traspaso->fecha; ?>  </td>
                        <td> <?php echo $objt->Traspaso->id_usuario;  ?></td>
                        <td> <?php
                           echo  $objtsal->status;  ?>
                        </td>



                    </tr>
                <?php }
                ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td> </td>
                    <td></td>
                    <td> <?php echo $cantidadentrada;  ?></td>
                    <td>       </td> <td>  </td>
                    <td>  </td><td></td><td></td>
                </tr>
                </tbody>
            </table>
        </div>
        <br> <br>
        <h2>Traspasos Salida</h2>
        <div class="adv-table">
            <table class="display table table-striped table-hover table-bordered" id="tabla2">
                <thead>
                <tr>
                    <th>FOLIO</th>
                    <th>ID</th>
                    <th>Producto</th>
                    <th>SKU</th>
                    <th>Cantidad</th>
                    <th>Costo</th>
                    <th>Precio</th>
                    <th>Tienda</th>
                    <th>Fecha de Traspaso</th>
                    <th>Manda</th>
                    <th>Status</th>

                </tr>
                </thead>
                <tbody>
                <?php
                $cantidadentrada=0;
                foreach($traspasosdestino->execute() as $objt){
                    $cantidadentrada+=$objt->cantidad;
                    ?>
                    <tr>
                        <td> <?php echo $objt->id_traspaso;  ?></td>
                        <td> <?php
                            $objv = Doctrine_Core::getTable("Database_Model_Tienda")->findOneBy("id_tienda", $objt->Traspaso->id_tiendaanterior);
                            echo $objv->nombre;  ?></td>
                        <td> <?php echo $objt->Producto->nombre;  ?></td>
                        <td> <?php echo $objt->Producto->codinter;  ?></td>
                        <td> <?php echo $objt->cantidad;  ?></td>
                        <td> <?php echo $objt->costo;  ?></td>
                        <td> <?php echo $objt->precio;  ?></td>
                        <td> <?php echo $objt->Traspaso->Tienda->nombre; ?> </td>
                        <td> <?php echo $objt->Traspaso->fecha; ?>  </td>
                        <td> <?php echo $objt->Traspaso->id_usuario;  ?></td>
                        <td> <?php
                            echo  $objtsal->status;  ?>
                        </td>



                    </tr>
                <?php }
                ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td> </td>
                    <td></td>
                    <td> <?php echo $cantidadentrada;  ?></td>
                    <td>       </td> <td>  </td>
                    <td>  </td><td></td><td></td>
                </tr>
                </tbody>
            </table>
        </div>

        <br>
        <h2>Salidas Directas</h2>
        <div class="adv-table">
            <table class="display table table-striped table-hover table-bordered" id="tabla2">
                <thead>
                <tr>
                    <th>FOLIO</th>
                    <th>ID</th>
                    <th>Producto</th>
                    <th>SKU</th>
                    <th>Cantidad</th>
                    <th>Origen</th>
                    <th>Destino</th>
                    <th>Fecha de Salida</th>
                    <th>Manda</th>
                    <th>Referencia</th>
                    <th>Comentarios</th>
                    <th>ESTATUS</th>

                </tr>
                </thead>
                <tbody>
                <?php
                $cantidadsalida=0;
                foreach($salidadirecta->execute() as $objt){
                    ?>
                    <tr>
                        <td> <?php echo $objt->id_salida;  ?></td>
                        <td> <?php echo $objt->id_salida_producto;  ?></td>
                        <td> <?php echo $objt->Producto->nombre;  ?></td>
                        <td> <?php echo $objt->Producto->codinter;  ?></td>
                        <td> <?php echo $objt->cantidad;  ?></td>
                        <td> <?php echo $objt->id_tienda; ?>         </td>
                        <td>  <?php        echo "SALIDA DE ALMACEN"; ?>     </td>
                        <td>  <?php   echo $objt->Salida->fecha; ?>  </td>
                        <td> <?php echo $objt->Salida->id_usuario;  ?></td>
                        <td> <?php echo $objt->Salida->referencia;  ?></td>
                        <td> <?php echo $objt->Salida->comentarios;  ?></td>
                        <td>
                            <?php echo $objt->status;
                            $cantidadsalida+=$objt->cantidad;
                            ?>
                        </td>


                    </tr>
                <?php }
                ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td> </td>
                    <td></td>
                    <td> <?php echo $cantidadsalida;  ?></td>
                    <td>       </td> <td>  </td>
                    <td>  </td>
                    <td></td><td></td>
                    <td></td><td></td>
                </tr>
                </tbody>
            </table>
        </div>
        <br>
        <h2>Ventas</h2>
        <div class="adv-table">
            <table class="display table table-striped table-hover table-bordered" id="tabla2">
                <thead>
                <tr>
                    <th>FOLIO</th>
                    <th>ID</th>
                    <th>Producto</th>
                    <th>SKU</th>
                    <th>Cantidad</th>
                    <th>Tienda</th>
                    <th>Cliente</th>
                    <th>Fecha de Venta</th>
                    <th>Vendedor</th>
                    <th>ESTATUS</th>

                </tr>
                </thead>
                <tbody>
                <?php
                $cantidadsalida=0;
                foreach($productosvendidos2->execute() as $objt){
                    ?>
                    <tr <?php  if ($objt->cancelado) {
                        echo "class='cancelada'";
                    }?>>
                        <td> <?php echo $objt->Venta->folio;  ?></td>
                        <td> <?php echo $objt->id_productos_venta;  ?></td>
                        <td> <?php echo $objt->ProductoTienda->Producto->nombre;  ?></td>
                        <td> <?php echo $objt->ProductoTienda->Producto->codinter;  ?></td>
                        <td> <?php echo $objt->cantidad;  ?></td>
                        <td>  <?php      echo $objt->Venta->Tienda->nombre; ?>     </td>
                        <td>  <?php   echo $objt->Venta->Persona->nombre; ?>  </td>
                        <td> <?php echo $objt->Venta->fecha;  ?></td>
                        <td> <?php echo $objt->Venta->id_usuario;  ?></td>
                        <td>
                            <?php echo $objt->status;
                            if (!$objt->cancelado) {
                                $cantidadsalida+=$objt->cantidad;
                            }

                            ?>
                        </td>


                    </tr>
                <?php }
                ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td> </td>
                    <td></td>
                    <td> <?php echo $cantidadsalida;  ?></td>
                    <td>       </td> <td>  </td>
                    <td>  </td>
                    <td></td><td></td>
                </tr>
                </tbody>
            </table>
        </div>
        <br>
        <h2>Cancelaciones</h2>
        <div class="adv-table">
            <table class="display table table-striped table-hover table-bordered" id="tabla2">
                <thead>
                <tr>
                    <th>Folio Venta</th>
                    <th>Id</th>
                    <th>Producto</th>
                    <th>SKU</th>
                    <th>Cantidad</th>
                    <th>Tienda</th>
                    <th>Cliente</th>
                    <th>Fecha de Venta</th>
                    <th>Fecha de Cancelacion</th>
                    <th>Usuario</th>
                    <th>Comentarios</th>

                </tr>
                </thead>
                <tbody>
                <?php
                $cantidadentradaC=0;
                foreach($productoscancelados->execute() as $objt){
                    ?>
                    <tr>
                        <td> <?php echo $objt->ProductosVenta->Venta->folio;  ?></td>
                        <td> <?php echo $objt->id_venta_productocancelado;  ?></td>
                        <td> <?php echo $objt->ProductosVenta->ProductoTienda->Producto->nombre;  ?></td>
                        <td> <?php echo $objt->ProductosVenta->ProductoTienda->Producto->codinter;  ?></td>
                        <td> <?php echo $objt->ProductosVenta->cantidad;  ?></td>
                        <td>  <?php
                            $objti = Doctrine_Core::getTable("Database_Model_Tienda")->findOneBy("id_tienda",$objt->id_tienda_destino);
                            if($objti){
                                echo $objti->nombre;
                            }
                          ?>     </td>
                        <td>  <?php   echo $objt->ProductosVenta->Venta->Persona->nombre; ?>  </td>
                        <td> <?php echo $objt->ProductosVenta->Venta->fecha;  ?></td>
                        <td> <?php echo $objt->fecha_registro;  ?></td>
                        <td> <?php echo $objt->ProductosVenta->Venta->id_usuario;  ?></td>
                        <td>
                            <?php echo $objt->observaciones;
                            $cantidadentradaC+=$objt->ProductosVenta->cantidad;
                            ?>
                        </td>


                    </tr>
                <?php }
                ?>
                <tr>
                    <td></td>
                    <td></td>
                    <td> </td>
                    <td></td>
                    <td> <?php echo $cantidadentradaC;  ?></td>
                    <td>       </td> <td>  </td>
                    <td>  </td>
                    <td></td><td></td><td></td>
                </tr>
                </tbody>
            </table>
        </div>

    </div>


</section>
<script>
$(".selectnvo").multiselect({
        multiple: false,
        header: "Selecciona una opcion",
        noneSelectedText: "Seleccionar",
        selectedList: 1
    }).multiselectfilter();
</script>