
<h3 class="tit">Validar  Inventario</h3>

<form action="http://phpstack-1171-4157-86632.cloudwaysapps.com/cremas/public/sistema/administracion/productos/validainventario" method="post" id="form">

    <table class="full-width">
        <tr>
            <td><label>Usuario</label></td>
            <td>  <?php
                $querysaldo = Doctrine_Query::create()
                    ->from("Database_Model_Usuario")
                    ->Where("status = ?", "ACTIVO")
                    ->execute();
                $arr = array();
                foreach($querysaldo as $s){
                    $arr[$s->id_usuario] = $s->nombre;
                }

                echo $this->formSelect("id_usuario", $this->profile()->id_usuario,
                    array("style"=>"width:460px","disable" => "true"),
                    array($arr)
                );
                ?>
            </td>
        </tr>
        <tr>
            <td><label>Fecha Validacion</label></td>
            <td>

                <input type="date" name="fecha_validacion" value="<?php echo date("Y-m-d");?>">
            </td>
        </tr>
        <tr>
            <td><label>Estatus</label></td>
            <td>  <?php
                echo $this->formSelect("estatus_validacion",$msj,
                    array("style"=>"width:460px","" => ""),
                    array("Correcto"=>'Correcto',"Faltante"=>'Faltante',"Faltante"=>'Faltante')
                );
                ?>
            </td>
        </tr>
        <tr>
            <td><label>Cantidad</label></td>
            <td>  <?php
                echo $this->formText("cantidad","0",
                    array("style"=>"width:460px","class" => "")
                );
                ?>
            </td>
        </tr>

        <tr>
            <td><label>Comentarios</label></td>
            <td>  <?php
                echo $this->formText("comentarios","",
                    array("style"=>"width:460px","class" => "")

                );
                ?>
            </td>
        </tr>
        <tr>
            <td colspan="2">   <input style="width: 100%" type="submit" id="send" class="button" value="Registrar"> </td>

        </tr>

    </table>

</form>