<script type="text/javascript">
    Number.prototype.toMoney = function (decimals, decimal_sep, thousands_sep) {
        var n = this,
            c = isNaN(decimals) ? 2 : Math.abs(decimals), //if decimal is zero we must take it, it means user does not want to show any decimal
            d = decimal_sep || '.', //if no decimal separetor is passed we use the comma as default decimal separator (we MUST use a decimal separator)

        /*
         according to [http://stackoverflow.com/questions/411352/how-best-to-determine-if-an-argument-is-not-sent-to-the-javascript-function]
         the fastest way to check for not defined parameter is to use typeof value === 'undefined'
         rather than doing value === undefined.
         */
            t = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep, //if you don't want ot use a thousands separator you can pass empty string as thousands_sep value

            sign = (n < 0) ? '-' : '',

        //extracting the absolute value of the integer part of the number and converting to string
            i = parseInt(n = Math.abs(n).toFixed(c)) + '',

            j = ((j = i.length) > 3) ? j % 3 : 0;
        return sign + (j ? i.substr(0, j) + t : '') + i.substr(j).replace(/(\d{3})(?=\d)/g, "$1" + t) + (c ? d + Math.abs(n - i).toFixed(c).slice(2) : '');
    }
    $(document).ready(function () {



        var fieldCounter = 1;

        $("#add-fields").click(function (e) {
            e.preventDefault();

            if (fieldCounter < 100) {
                var $articulos = $("#articulos");
                var trHtml = $(".original-row:first").html();

                trHtml = trHtml.replace(/X-X/gi, "" + fieldCounter++);
                $articulos.append("<tr generatedbyme='true'>" + trHtml + "</tr>");
                updateTotal();
            } else {
                alert("Ya sobrepasó el número de conceptos.");
            }

            textareaAutogrow();

        });

        $("#remove-fields").click(function (e) {
            e.preventDefault();

            $("[generatedbyme=true]:last").remove();
            fieldCounter--;

            updateTotal();
        });

        $(".precio_unitario").live("keyup", function () {
            var thisCount = $(this).attr("precio_unitario");
            var montoTotal = parseFloat($("[cantidad=" + thisCount + "]").val()) * $(this).val();
            $("[precio_total=" + thisCount + "]").val(montoTotal);
            updateTotal();
        });

        //Actualizar el total
        updateTotal = function () {
            var precios = $(".precio_total");
            var impuesto = $(".impuesto");
            var subtotal = 0;
            var impuestosexentos=0;
            var impuestosiva=0;
            var impuestosieps=0;



            for (var i = 0, len = precios.length; i < len; i++) {
                if (!isNaN($(precios[i]).val())) {


                        subtotal += parseFloat($(precios[i]).val());
                        if(parseFloat($(impuesto[i]).val())==1.16){
                            impuestosiva+=parseFloat($(precios[i]).val())*0.16;
                        }
                        if(parseFloat($(impuesto[i]).val())==1.08){
                            impuestosieps+=parseFloat($(precios[i]).val())*0.08;
                        }
                        if($(impuesto[i]).val()==1){
                            impuestosexentos+=parseFloat($(precios[i]).val());
                        }



                }
            }
            var iva=$("#iva").val();

            if(iva==0){ iva=1;}
            $("#subtotal").val(subtotal.toMoney(2, ".", ""));
            $("#montoiva").val(impuestosiva);
            $("#montoieps").val(impuestosieps);
            $("#montoexentos").val(impuestosexentos);
            var montoiva=$("#montoiva").val();
            var montoieps=$("#montoieps").val();
            var montosubtotal=$("#subtotal").val();
            var tot=parseFloat(montosubtotal)+parseFloat(montoiva)+parseFloat(montoieps);
            $("#total").val(tot.toMoney(2, ".", ""));

            //calculatotal();
        }

        updateTotal();


        //Cada que cambia, actualizar el total
        $(".update-total").live("change",
            function () {
                updateTotal();
            }).live("keyup", function () {
                updateTotal();
            });

        $(".borrar-linea").click(function (e){
            e.preventDefault();

            $(this).closest("tr").remove();
            updateTotal();
        });
    });
    function calculatotal(){
    /*  var iva=document.getElementById("iva").value;

        var subtotal=document.getElementById("subtotal").value;
        var total=0;
        var ivamonto=0;
        if(iva==0){
            var nuevototal=subtotal;
        }else{
            var nuevototal=subtotal*iva;
            ivamonto=parseFloat(iva-1);
        }
        */
        //document.getElementById("montoiva").value=Math.round(parseFloat(subtotal)*(ivamonto)*100)/100;//a dos decimales
        // document.getElementById("total").value=Math.round(parseFloat(nuevototal)*100)/100;//a dos decimales
        updateTotal();
    }
    function borrarlinea(num){
        document.getElementById("renglon"+num).innerHTML="";
    }
</script>
<style type="text/css">
    .autogrow {
        height: auto !important;
    }

    .tiny-field {
        width: 50px !important;
    }
</style>
<h1>Facturas</h1>
<h3 class="tit">Alta de factura</h3>
<form action="" method="post" id="mainForm" enctype="multipart/form-data">

    <table class="nostyle">
        <tr>
            <td><span class="arial">Cliente</span></td>
            <td colspan="5">  <?php echo $this->form->id_persona; ?></td>
        </tr>
        <tr>
            <td><span class="arial">Serie</span></td>
            <td>    <span class="arial">
     <?php echo $this->form->serie; ?>
    </span></td>
            <td><span class="arial">Folio</span></td>
            <td><span class="arial">
                    <?php echo "<input type='text' name='folio' id='folio' value='".$this->folio."'  style='width:100px' readonly >
                    <input type='hidden'  id='auxfolioi' value='".$this->folio."' readonly >
                    <input type='hidden'  id='auxfolioe' value='".$this->folioe."' readonly >
                    "; ?>

    </span></td>
            <td><span class="arial"></span></td>
            <td><span class="arial">

    </span></td>
        </tr>
        <tr>
            <td><span class="arial">Fecha emision</span></td>
            <td><span class="arial">

      <?php
      $date = new DateTime("now", new DateTimeZone('America/Mexico_City') );
      echo " <input type='text' style='width:170px'  id='fecha' name='fecha' value='".$date->format('Y-m-d\TH:i:s')."' readonly >";
      //echo $this->form->fecha; ?>
    </span></td>
            <td><span class="arial">Tipo</span></td>
            <td><span class="arial">
                     <?php echo $this->form->tipo_comprobante; ?>

    </span></td>
            <td><span class="arial">Moneda</span></td>
            <td><span class="arial">
      <?php echo $this->form->moneda; ?>
    </span></td>
        </tr>
        <tr>
            <td><span class="arial">Condiciones Pago</span></td>
            <td><span class="arial">
      <?php echo $this->form->condiciones_pago; ?>
    </span></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td><span class="arial">Tipo de Cambio</span></td>
            <td><span class="arial">
        <?php echo $this->form->tipo_cambio; ?>
    </span></td>
        </tr>
        <tr>
            <td><span class="arial">Metodo de Pago</span></td>
            <td><span class="arial">
       <?php echo $this->form->tipo; ?>
    </span></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td><span class="arial">
     <?php echo $this->form->digitos; ?>
    </span></td>
            <td><span class="arial">&lt;--Num Cuenta con la que se hace el pago (opcional)</span></td>
        </tr>
        <tr>
            <td><span class="arial">Forma de Pago</span></td>
            <td><span class="arial">
      <?php echo $this->form->forma_pago; ?>
    </span></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td><span class="arial"></span></td>
            <td><span class="arial">

    </span></td>
        </tr>
        <tr>
            <td colspan="6">&nbsp;</td>
        </tr>
    </table>








    <h5 class="tit">Artículos</h5>
    <table class="nostyle" id="articulos">
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td align="right">
                <a href="#" id="remove-fields">
                    <img src="<?php echo $this->baseUrl("css/img/delete.png"); ?>" border="0"/>
                </a>
                <a href="#" id="add-fields">
                    <img src="<?php echo $this->baseUrl("css/img/add.png"); ?>" border="0"/>
                </a>
            </td>
        </tr>
        <?php
      //  var_dump($this->venta);
        if ($this->venta){ ?>
            <?php
            $counter = 0;
            $totalieps=0;
            $totalieps1=0;
            $totaliva=0;
            $cantieps=0;
            $cantiva=0;
            $totalexento=0;
            foreach ($this->venta as $venta) {
               // echo $venta->id_venta;
                $querydesc= Doctrine_Query::create()
                    ->from("Database_Model_Descuentos")
                    ->where("id_venta=?",$venta->id_venta)
                    ->execute();
                $msj="";

                foreach ($venta->ProductosVenta as $obj):
                    $productot = Doctrine_Query::create()
                        ->from("Database_Model_ProductoTienda")
                        ->where("id_productotienda =?",$obj->id_productotienda )
                        ->fetchOne();
                    $impuesto = 1;
                    if($productot->Producto->exento_iva>0){//puede tener ieps o estar exento
                        if($productot->Producto->exento_ieps==0) {//si tiene 0 tiene ieps
                            $impuesto = 1.08;
                            $totalieps1 += $obj->total;
                            $cantieps += $obj->cantidad;
                            if ($productot->Producto->exento_ieps == 0) {
                                $totalieps += (($obj->total) / 1.08) * 0.08;
                                $totalsinimpuestoieps += ($obj->total) / 1.08;
                            }
                        }else{//si excentoipes=1 quiere decir qeu esta excento de impuestos
                            $totalexento += ($obj->total) ;
                        }
                    }else{
                        //echo "iva=";
                        $impuesto=1.16;
                        $cantiva+=$obj->cantidad;
                             $totaliva+=(($obj->total)/1.16)*0.16;
                            $totalsinimpuestoiva+=($obj->total)/1.16;
                    }

                    ?>
                    <tr class="original-row"  id="renglon<?php echo $counter>0?$counter:"0"; ?>">
                        <td>
                            <label>FOLIO</label>
                            <div><?php echo $venta->folio; ?></div>
                        </td>
                        <td>
                            <label>Cantidad</label>
                            <input type="text" name="q[]" cantidad="X-X<?php echo $counter>0?$counter:""; ?>" value="<?php echo $obj->cantidad; ?>"
                                   class="tiny-field cantidad"/>
                        </td>
                        <td>
                            <label>Concepto</label>
                            <textarea concepto="X-X<?php echo $counter>0?$counter:""; ?>" rows="1" class="autogrow"
                                      name="nombre[]"><?php echo trim($obj->nombre); ?></textarea>
                        </td>
                        <td>
                            <label>Precio unitario</label>
                            <input type="text" precio_unitario="X-X<?php echo $counter>0?$counter:""; ?>" name="precio_unitario[]"
                                   value="<?php echo number_format((($obj->total / $obj->cantidad) ) / $impuesto, 2, ".", ""); ?>"
                                   class="small-field update-total precio_unitario"/>
                        </td>
                        <td>
                            <label>Imp.</label>
                            <?php
                                $var=$counter>0?$counter:"";
                            echo "<input type='hidden' name='impuesto[]'  class='small-field  impuesto' impuesto='X-X".$var."' id value='".$impuesto."' >";
                            if($impuesto==1){
                                echo "Excento";
                            }
                            if($impuesto==1.08){
                                echo "IEPS";
                            }
                            if($impuesto==1.16){
                                echo "IVA";
                            }

                            echo $impuesto;?>
                        </td>
                        <td>
                            <?php
                            if($productot->Producto->exento_ieps==0) {

                             } ?>
                        </td>
                        <td>

                            <label>Total Sin Impuesto</label>
                            <input type="text" precio_total="X-X<?php echo $counter>0?$counter:""; ?>" name="precio_total[]"
                                   value="<?php echo number_format(($obj->total) / $impuesto, 2, ".", ""); ?>"
                                   class="small-field update-total precio_total"/>
                        </td>
                        <td>
                            <a href="#" class="borrar-linea" onclick="borrarlinea(<?php echo $counter>0?$counter:"0"; ?>); calculatotal();">Borrar</a>
                        </td>
                    </tr>
                    <?php
                    $counter++;
                endforeach;
                foreach ($querydesc as $objdesc): ?>
                    <tr class="original-row"  id="renglon<?php echo $counter>0?$counter:"0"; ?>">
                        <td>

                        </td>
                        <td>
                            <label>Cantidad</label>
                            <input type="text" name="q[]" cantidad="X-X<?php echo $counter>0?$counter:""; ?>" value="<?php echo 1; ?>"
                                   class="tiny-field cantidad"/>
                        </td>
                        <td>
                            <label>Concepto</label>
                            <textarea concepto="X-X<?php echo $counter>0?$counter:""; ?>" rows="1" class="autogrow"
                                      name="nombre[]"><?php echo trim($objdesc->descripciondesc." Folio:".$objdesc->Venta->folio); ?></textarea>
                        </td>
                        <td>
                            <label>Precio unitario</label>
                            <input type="text" precio_unitario="X-X<?php echo $counter>0?$counter:""; ?>" name="precio_unitario[]"
                                   value="<?php echo "-".number_format($objdesc->montodesc , 2, ".", ""); ?>"
                                   class="small-field update-total precio_unitario"/>
                        </td>
                        <td>
                            <?php
                            $var=$counter>0?$counter:"";
                            echo "<input type='hidden' name=''  class='small-field  impuesto' impuesto='X-X".$var."'  value='0' >";
                                ?>

                        </td>
                        <td></td>
                        <td>

                            <label>Total Sin impuesto</label>
                            <input type="text" precio_total="X-X<?php echo $counter>0?$counter:""; ?>" name="precio_total[]"
                                   value="<?php echo "-".number_format(($objdesc->montodesc) , 2, ".", ""); ?>"
                                   class="small-field update-total precio_total"/>
                        </td>

                        <td>
                            <a href="#" class="borrar-linea" onclick="borrarlinea(<?php echo $counter>0?$counter:"0"; ?>); calculatotal();">Borrar</a>
                        </td>
                    </tr>
                    <?php
                    $counter++;

                endforeach;
            }?>
        <?php
        }else{ ?>
            <tr class="original-row">
                <td>
                </td>
                <td>
                    <label>Cantidad</label>
                    <input type="text" name="q[]" cantidad="X-X" class="tiny-field cantidad"/>
                </td>
                <td>
                    <label>Concepto</label>
                    <textarea concepto="X-X" rows="1" class="autogrow" name="nombre[]"></textarea>
                </td>
                <td>
                    <label>Precio unitario</label>
                    <input type="text" precio_unitario="X-X" name="precio_unitario[]"
                           class="small-field update-total precio_unitario"/>
                </td>
                <td>

                    <label>Total</label>
                    <input type="text" precio_total="X-X" name="precio_total[]"
                           class="small-field update-total precio_total"/>
                </td>
            </tr>
        <?php } ?>
    </table>
    <h5 class="tit">Totales</h5>
    <table  class="form-actions">
        <tr>
            <th>Subtotal:</th>
            <td><?php echo $this->form->subtotal; ?></td>
        </tr>

       <!-- <tr>
            <th>IVA.</th>
            <td>
                <select id="iva" name="iva" onchange="calculatotal();" class="chzn-select">
                    <option value="1.16">16%</option>
                    <option value="0">0%</option>
                    <option value="0">Exento</option>
                </select>
            </td>
        </tr>-->
        <tr>
            <th>Monto IVA.</th>
            <td><input type="text" value="<?php echo number_format(($totaliva),2,".",",");?>"  id="montoiva" name="montoiva"></td>
        </tr>
        <tr>
            <th>Monto IEPS.</th>
            <td><input type="text" value="<?php echo number_format(($totalieps),2,".",",");?>"  id="montoieps" name="montoieps"></td>
        </tr>
        <tr>
            <th>Monto Exento.</th>
            <td><input type="text" value="<?php echo number_format(($totalexento),2,".",",");?>"  id="montoexentos" name="montoexentos"></td>
        </tr>
        <tr>
            <th>Total:</th>
            <td><?php echo  $this->form->total; ?></td>
        </tr>
    </table>
    <dt>
        <?php echo $this->form->Aceptar; ?>
    </dt>
</form>
