<h1>Facturas</h1>
<p class="t-right">
    <a href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/alta"); ?>">
        <img src="<?php echo $this->baseUrl("css/img/add.png") ?>" border="0"/>
    </a>
</p>

<h3 class="tit">Desde ticket</h3>
<form method="get" action="<?php echo $this->baseUrl("facturas/administrar/alta"); ?>">
    <label>Ticket Num:</label>
    <input type="text" style="width: 100px !important;" name="id_venta">
    <div class="control-group" id="tiendaorigen" style="display: ">
        <label class="control-label">Tienda De Venta </label>
        <div class="controls">
            <?php echo $this->formSelect("id_tienda",$this->id_tienda,
                array("style"=>"width:460px","required" => "required"),
                Database_Model_Tienda::getAllT()
            ); ?>
        </div>
    <br />

<fieldset>
    <legend>Facturas del día</legend>

        <label>Desde</label>
        <input type="text" name="desde" datepicker="past" value="<?php echo date("Y-m-d"); ?>">
        <label>Hasta</label>
        <input type="text" name="hasta" datepicker="past" value="<?php echo date("Y-m-d"); ?>">
        <br />
        <label>Efectivo</label>
        <input type="radio" name="tipo_pago" value="Efectivo">

        <label>Tarjeta</label>
        <input type="radio" name="tipo_pago" value="Tarjeta">

        <label>Amex</label>
        <input type="radio" name="tipo_pago" value="AMEX">

        <label>Otro</label>
        <input type="radio" name="tipo_pago" value="Otro">
        <br />
        <br />
        <input type="submit" value="Generar">
    </form>

</fieldset>
<br />
<hr />

<h3 class="tit">Listado / Buscar</h3>
<?php echo $this->form; ?>
<table class="full-width">
    <thead>
    <tr>
        <th></th>
        <th>Num</th>
        <th>Cliente</th>
        <th>ID</th>
        <th>Gravado</th>
        <th>Exento</th>
        <th>Subtotal</th>
        <th>IVA</th>
        <th>IEPS</th>
        <th>Total</th>
        <th>Usuario</th>
        <th>Fecha Registro</th>
		<TH></TH>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->query as $obj): ?>
    <tr
    	<?php if($obj->cancelada){
    		echo 'style="opacity: .5;"';
    	} ?>
    >
        <td nowrap="nowrap">
            <?php if ($obj->urlxml): ?>
            <a target="_blank" href="<?php echo $obj->urlxml; ?>">
                XML
            </a>
            <a target="_blank" href="<?php echo $obj->urlpdf; ?>">
                PDF
            </a>
            <?php endif; ?>
        </td>
        <td><?php echo $obj->serie; ?><?php echo $obj->folio; ?></td>
        <td><?php echo $obj->id_persona; ?> | <?php echo $obj->Persona->nombre; ?></td>
        <td><?php echo $obj->id_factura; ?></td>
        <td>$<?php echo number_format(($obj->subtotal-$obj->exentos), 2); ?></td>
        <td>$<?php echo number_format($obj->exentos, 2); ?></td>
        <td>$<?php echo number_format(($obj->subtotal), 2); ?></td>
        <td>$<?php echo number_format($obj->iva, 2); ?></td>
        <td>$<?php echo number_format($obj->ieps, 2); ?></td>
        <td>$<?php echo number_format($obj->total, 2); ?></td>
        <td><?php echo $obj->id_usuario; ?></td>
        <td><?php echo $obj->fecha_registro; ?></td>
		<td>
			<?php if($obj->cancelada): ?>
			Cancelada por <?php echo $obj->id_usuariocancelacion."<br>".$obj->fecha_cancelacion?>
			<?php else: ?>
		<a delete="true"
               href="<?php echo $this->baseUrl($this->request->getModuleName() . "/" . $this->request->getControllerName() . "/cancelar/id/" . $obj->id_factura); ?>">
                <img src="<?php echo $this->baseUrl("css/img/delete.png") ?>" border="0"/>
            </a>
			<?php endif; ?>
		</td>

        
    </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div id="tnt_pagination">
    <?php echo $this->paginator; ?>
</div>