<?php
$comisiones = Zend_Json::decode($this->obj->detalle_comisiones);
if (!$comisiones["agentes"]) {
    $comisiones["agentes"] = array();
}
$impuestos = Zend_Json::decode($this->obj->impuestos);

?>

<script type="text/javascript">
    $(document).ready(function () {
        $("#toggle-articulos").click(function (e) {
            e.preventDefault();

            $("#articulos").toggle();
        });
    });
</script>
<h1>Ver factura</h1>
<h3 class="tit">No. de factura: <?php echo $this->obj->num_factura; ?></h3>
<table style="min-width: 600px;">
    <tr>
        <th>Empresa</th>
        <td>
            <a fancybox="true"
               href="<?php echo $this->baseUrl("administracion/empresas/ver/id/" . $this->obj->id_empresa); ?>">
                <?php echo $this->obj->Empresa->nombre; ?>
            </a>
        </td>
    </tr>
    <tr>
        <th>Cliente</th>
        <td>
            <a fancybox="true"
               href="<?php echo $this->baseUrl("administracion/clientes/ver/id/" . $this->obj->id_cliente); ?>">
                <?php echo $this->obj->Cliente->nombre; ?>
            </a>

        </td>
    </tr>
    <?php if ($this->obj->archivo_papel): ?>
    <tr>
        <th>Archivo</th>
        <td>
            <a target="_blank"
               href="<?php echo $this->baseUrl("uploads/" . $this->obj->archivo_papel); ?>"><?php echo $this->obj->archivo_papel; ?></a>
        </td>
    </tr>
    <?php endif; ?>

   
   
    <tr>
        <th>Fecha</th>
        <td><?php echo $this->obj->fecha; ?></td>
    </tr>
    <tr>
        <th>Subtotal</th>
        <td>$<?php echo number_format($this->obj->subtotal, 2); ?></td>
    </tr>
    <tr>
        <th>Impuestos</th>
        <td>
            <?php
            foreach ($impuestos AS $age) {
                echo $age["nombre"] . ": $" . number_format($this->obj->subtotal * $age["monto"], 2) . "<br />";
            }
            ?>
        </td>
    </tr>
    <tr>
        <th>Total</th>
        <td><span class="bigger">$<?php echo number_format($this->obj->total, 2); ?></span></td>
    </tr>
    <tr>
        <th>Total con letra</th>
        <td><?php echo $this->obj->total_letra; ?></td>
    </tr>
    

</table>
<a href="#" id="toggle-articulos">Mostrar/esconder artículos</a>
<div id="articulos">
    <h3 class="tit">Artículos</h3>
    <table class="full-width">
        <tr>
            <th>Cantidad</th>
            <th>Artículo</th>
            <th>Precio unitario</th>
            <th>Total</th>
        </tr>
        <?php
        $articulos = Zend_Json::decode($this->obj->items);

        foreach ($articulos as $obj):
            ?>
            <tr>
                <td><?php echo $obj["cantidad"]; ?></td>
                <td><?php echo $obj["nombre"]; ?></td>
                <td>$<?php echo number_format($obj["precio_unitario"], 2); ?></td>
                <td>$<?php echo number_format($obj["precio_total"], 2); ?></td>
            </tr>
            <?php endforeach; ?>
    </table>
</div>