<div class="row">
  <div class="col-lg-6">
    <section class="panel">
      <header class="panel-heading">
        Cambiar sucursal del usuario
      </header>
      <div class="panel-body">

        <?php 
        $this->form->getElement('submit')->setLabel('Guardar');
        echo $this->form;
        ?>
        
        <a href="<?php echo $this->baseUrl('administracion/usuarios');?>" class="btn btn-danger">
          Cancelar
        </a>
        
      </div>
    </section>
  </div>
</div>

<?php
///////////// chosen
$this->inlineScript()->appendFile($this->baseUrl('js/chosen.js'));
$this->inlineScript()->appendScript('
  jQuery(document).ready(function() {
    $(".chosen-select").chosen({no_results_text: "No hay coincidencias"}); 
  });
');
$this->headLink()->appendStylesheet($this->baseUrl('css/chosen.css'));
?>

<script>
    f($(".form-full-event #event-content").val("calEvent.category")=='birthday'){
        $('#button-mail').show();
    }else{
        $('#button-mail').hide();
    }
</script>