<section id="section_top" class="panel">
    <header class="panel-heading">
        Lista de usuarios
    </header>

    <form method="post">
        <table id="list-datatable" class="datatable-static table table-striped table-bordered table-hover">

              <th>Modulo</th>
              <th>Controlador</th>
              <th>Acción</th>
             <th>Nombre Pagina</th>
            <th>Nombre del Modulo</th>
              <th>

                  <label>

                      <input type="checkbox" id="all"/>

                      <span class="lbl"></span>

                  </label>
              </th>

            <tbody>
        <?php
        $permisos = array();
        $qryacusu=   Doctrine_Query::create()
            ->from("Database_Model_UsuarioAccion")
            ->where('id_usuario=?',$this->usuario->id_usuario)
            ->execute();
        foreach ($qryacusu as $foo) {
          $permisos[] = $foo->id_accion;
        }

        $perms = Doctrine_Query::create()
        ->from("Database_Model_Accion")
        ->orderBy("nombremodulo ASC, controlador ASC, accion ASC")
        ->execute();

        $modulo = "";
        $controlador = "";

        foreach ($perms as $perm):?>
            <?php
            if($perm->modulo!=$modulo || $perm->controlador!=$controlador):
                $modulo=$perm->modulo;
                $controlador=$perm->controlador;?>
                <tr>
                     <td><strong><?php echo ucwords($perm->modulo); ?></strong></td>
                     <td><strong><?php echo ucwords($perm->controlador); ?></strong></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            <?php
            endif; ?>
                <tr>
                  <td><?php echo ucwords($perm->modulo); ?></td>
                  <td><?php echo ucwords($perm->controlador); ?></td>
                  <td><?php echo ucwords($perm->accion); ?></td>
                    <td><?php echo ucwords($perm->nombre); ?></td>
                    <td><?php echo ucwords($perm->nombremodulo); ?></td>
                    <td class="center">
                        <label>
                            <input type="checkbox" name="perm[]" class="perm-check"
                                <?php if (in_array($perm->id_accion, $permisos)) {
                                    echo " checked='checked' ";
                                } ?>
                                   value="<?php echo $perm->id_accion; ?>"/>

                            <span class="lbl"></span>

                        </label>

                    </td>

                </tr>
                    <?php endforeach; ?>
            </tbody>
      </table>
      <br>
      <input type="submit" class="btn btn-success" value="Guardar"><br><br>
      <a href="<?php echo $this->baseUrl('usuarios/usuarios');?>" class="btn btn-danger">
        Cancelar
      </a>
    </form>

</section>


<script>

    $("#all").change(function () {
        if ($(this).is(':checked')) {
            $(".perm-check").prop("checked", $(this).prop("checked") == true);
        }else{
            $(".perm-check").prop("checked", $(this).prop("checked") == "checked");

        }
    });
</script>

