
        <section id="section_top" class="panel">
            <div class="page-header position-relative">
                <h1>
                    <h3 class="tit">  Editar Usuario</h3>
                </h1>
            </div>
            <div class="panel-body">
                <div class="step-pane active">
                    <div class="col-lg-8 col-lg-offset-2">
                        <form id="defaultForm" method="post" class="form-horizontal" action="">
                            <div class="control-group">
                                <label class="control-label">Usuario ID</label>
                                <div class="controls">
                                <?php
                                echo $this->formText("id_usuario", Sistema_Class_Constants::_htmlspecial($this->data["id_usuario"]),
                                array("disabled","disabled")); ?>
                            </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Nombre</label>
                                <div class="controls">
                                <?php
                                echo $this->formText("nombre", Sistema_Class_Constants::_htmlspecial($this->data["nombre"])
                                ); ?>
                            </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Email</label>
                                <div class="controls">
                                    <?php
                                    echo $this->formText("email", Sistema_Class_Constants::_htmlspecial($this->data["email"])
                                    ); ?>
                            </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Responsable</label>
                                <div class="controls">
                                    <?php
                                    echo $this->formText("responsable", Sistema_Class_Constants::_htmlspecial($this->data["responsable"])
                                    ); ?>
                            </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Password</label>
                                <div class="controls">
                                    <input type="password" class="form-control" name="password" id="password" placeholder="Password"  />
                            </div>
                            </div>

                            <div class="control-group">
                                <label class="control-label">Retype password</label>
                                <div class="controls">
                                    <input type="password" class="form-control"  onpaste="return false;" name="confirmPassword" id="confirmPassword" placeholder="Retype Password" />
                            </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">Es Capitan </label>
                                <div class="controls">
                                    <?php
                                    $arrusercom= array();

                                        $arrusercom["0"] = "NO";
                                        $arrusercom["1"] = "Si";
                                    $emb=0;
                                    if($this->data["embarcacion_usuario"]){
                                        $emb=1;
                                    }

                                    echo $this->formSelect("embarcacion_usuario", $emb,
                                        array("onchange" => ""),
                                        $arrusercom
                                    ); ?>
                            </div>
                            </div>
                            <div id="contenedor">

                                <fileset>
                                    <legend>Embarcacion Usuario</legend>
                                    <div class="control-group">
                                        <label class="control-label">Selecciona el numero de Embarcaciones</label>
                                        <div class="controls">
                                            <select id="numeroembarcacion_usuario" name="numeroembarcacion_usuario">
                                                <option value=''>Selecciona</option>
                                                <?php
                                                for($i=1;$i<=5;$i++){
                                                    $check="";
                                                    if($i==$this->data["embarcacion_usuario"]){
                                                        $check="selected";
                                                    }
                                                    echo "<option $check value='$i'>".$i."</option>";
                                                }
                                                ?>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="control-group"  id="tablacontratos">

                                        <table   width="800px" class="table">
                                            <thead>
                                            <tr>
                                                <th style="width: 200px;">Embarcacion</th>

                                            </tr>
                                            </thead>
                                        </table>
                                        <table   width="800px" class="table">

                                            <tbody>
                                            <?php
                                            $queryper= Doctrine_Query::create()
                                                ->from("Database_Model_EmbarcacionUsuario")
                                                ->where("id_usuario= ?", $this->data["id_usuario"])
                                                ->execute();
                                            foreach($queryper as $i => $objemusu){
                                                $i++;
                                                ?>

                                                <tr id="tablafs<?php echo $i?>" style="">

                                                    <td>

                                                        <select name="id_embarcacion[]" id="id_embarcacion<?php echo $i;?>" class="" style="width: 200px;">
                                                            <?php

                                                            $ca= Doctrine_Query::create()
                                                                ->from("Database_Model_Embarcacion")
                                                                ->where("status = 'ACTIVO'")
                                                                ->andwhere("es_tierra = '0'")
                                                                ->execute();
                                                            foreach ($ca as $per) {

                                                                $check="";
                                                                if($per->id_embarcacion==$objemusu->id_embarcacion){
                                                                    $check="selected";
                                                                }
                                                                echo "<option  $check value='".$per->id_embarcacion."'>".$per->nombre."</option>";
                                                            }
                                                            ?>
                                                        </select>

                                                    </td>

                                                </tr>

                                            <?php }?>
                                            <?php for($i=count($queryper)+1;$i<=5;$i++){
                                                ?>

                                                <tr id="tablafs<?php echo $i?>" style="display:none">

                                                    <td>

                                                        <select name="id_embarcacion[]" id="id_embarcacion<?php echo $i;?>" class="" style="width: 200px;">
                                                            <?php
                                                            echo "<option value=''>Selecciona</option>";

                                                            $ca= Doctrine_Query::create()
                                                                ->from("Database_Model_Embarcacion")
                                                                ->where("status = 'ACTIVO'")
                                                                ->execute();
                                                            foreach ($ca as $per) {
                                                                echo "<option   value='".$per->id_embarcacion."'>".$per->nombre."</option>";
                                                            }
                                                            ?>
                                                        </select>

                                                    </td>
                                                </tr>

                                            <?php }?>
                                            </tbody>
                                        </table>

                                    </div>
                                </fileset>
                            </div>
                            <div class="form-actions">
                                <button class="btn btn-info" type="submit">
                                    <i class="icon-ok bigger-110"></i> Aceptar
                                </button>
                                <button class="btn"  onclick="window.history.go(-1); return false;">
                                    <i class="icon-undo bigger-110"></i> Cancelar
                                </button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </section>
<script>
    $(document).ready(function() {
        //sin espacios el password
        $("#password").keypress(function (key) {
            window.console.log(key.charCode)
            if (key.charCode == 32)
                return false;
        });
        $("#embarcacion_usuario").change(function () {
            var frec=$("#embarcacion_usuario").val();
            if(frec=="1"){
                $("#contenedor").show();
            }else{
                $("#contenedor").hide();
            }
        }).change();
        $("#numeroembarcacion_usuario").change(function () {
            for(var i=1;i<=5;i++){
                var aux="tablafs"+i;
                $("#"+aux).hide();
            }
            var numarchflet= document.getElementById("numeroembarcacion_usuario").value;

            for(var i=1;i<=numarchflet;i++){
                var aux="tablafs"+i;
                $("#"+aux).show();
            }
        }).change();
    });

</script>