<section id="section_top" class="panel">
  <header class="panel-heading">
    Lista de usuarios
  </header>
  <div class="panel-body">
    <a href="<?php echo $this->baseUrl('usuarios/usuarios/agregar');?>">
      <button class="btn btn-success">
        Agregar<i class="icon-plus"></i>
      </button>
    </a>
    <br>
    <br>

    <!-- Filtros para listar -->
    <br>
    <div class="adv-table">
        <table id="list-datatable" class="datatable-static table table-striped table-bordered table-hover">
        <thead>
          <tr>
            <th>ID Usuario</th>
            <th>Username</th>
            <th>Modulo</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <?php
          foreach($this->usuarios as $usuario){
            echo '<tr>';
            echo '<td>',$usuario->id_usuario,'</td>';
            echo '<td>',$usuario->responsable,'</td>';
            echo '<td>',$usuario->nombre,'</td>',
            '<td><a href="'.$this->baseUrl('usuarios/usuarios/editar/id/'.$usuario->id_usuario).'">Editar</a></td>',
            '<td><a href="'.$this->baseUrl('usuarios/usuarios/editarpermisos/id/'.$usuario->id_usuario).'">Permisos</a></td>',
            '<td><a href="javascript: borrar(\''.$this->baseUrl('usuarios/usuarios/desactivar/id/'.$usuario->id_usuario).'\')">Eliminar</a></td>',
            '</tr>';
          }
          ?>
        </tbody>
      </table>
    </div>
  </div>
</section>
