<link rel='stylesheet' type='text/css' href='<?php echo $this->baseUrl(); ?>/fullcalendar/fullcalendar.css'/>
<script type='text/javascript' src='<?php echo $this->baseUrl(); ?>/fullcalendar/fullcalendar.js'></script>

<script type="text/javascript">
    $(document).ready(function () {

        $("#calendar").fullCalendar({
            header: {
				left: 'prev,next today',
				center: 'title',
				right: 'month,agendaWeek,agendaDay'
			},
            eventSources: [
                // your event source
                {
                    url: _root + "/asistencia/reportes/feed",
                    type: 'GET',
                    data: {
                        id_usuario: $("#id_usuario").val()
                    },
                    error: function() {
                        alert('Ocurrió un error :( Lo sentimos');
                    }
                }

                // any other sources...

            ]
        });

    });
</script>

<?php echo $this->form; ?>
<div id="calendar"></div>