<h1>Reportes</h1>
<h3 class="tit">Asistencia</h3>
<?php echo $this->form; ?>
<h3 class="tit">Resultado</h3>
<table>
    <tr>
        <th>Tipo</th>
        <th>Hora</th>
        <th>Usuario</th>
    </tr>
    <?php foreach ($this->query as $obj): ?>
        <tr>
            <td><?php echo $obj->tipo; ?></td>
            <td><?php echo $obj->hora; ?></td>
            <td><?php echo $obj->id_usuario; ?> | <?php echo $obj->Usuario->nombre; ?></td>
        </tr>
    <?php endforeach; ?>
</table>